# -*- coding: utf-8 -*-
"""واژگان دروس ۱۱ تا ۲۰ سطح B1 — شرط و احتیاط، مدال‌های گذشته، نقل قول."""

V = {}

V[11] = [
 ("unless","conjunction","/ənˈles/","مگر اینکه","We'll go unless it rains.","می‌رویم مگر اینکه باران ببارد.","two adults in their thirties looking at a cloudy sky before setting off"),
 ("as long as","phrase","/əz lɒŋ əz/","تا وقتی که","It's fine as long as you're careful.","تا وقتی مراقب باشی مشکلی نیست.","a person in their thirties carrying a fragile box carefully"),
 ("in case","phrase","/ɪn keɪs/","در صورتی که، محض احتیاط","Take a coat in case it's cold.","محض احتیاط کت بردار.","a coat folded over an arm on a mild day"),
 ("provided that","phrase","/prəˈvaɪdɪd ðæt/","به شرط اینکه","You can go provided that you finish.","به شرط اینکه تمام کنی می‌توانی بروی.","a finished task beside an open door"),
 ("even if","phrase","/ˈiːvn ɪf/","حتی اگر","I'll come even if it's late.","حتی اگر دیر باشد می‌آیم.","a person in their thirties arriving at a doorway at night"),
 ("backup","noun","/ˈbækʌp/","پشتیبان","We need a backup.","به پشتیبان نیاز داریم.","a second copy of a document on a desk"),
 ("precaution","noun","/prɪˈkɔːʃn/","احتیاط","It's just a precaution.","فقط یک احتیاط است.","a safety helmet placed ready on a bench"),
 ("emergency exit","phrase","/ɪˈmɜːdʒənsi ˈeksɪt/","خروج اضطراری","Where's the emergency exit?","خروج اضطراری کجاست؟","a lit exit doorway at the end of a corridor"),
 ("insurance","noun","/ɪnˈʃʊərəns/","بیمه","Do you have travel insurance?","بیمه سفر داری؟","a plain policy folder on a desk"),
 ("guarantee","noun","/ˌɡærənˈtiː/","ضمانت","There's a two-year guarantee.","دو سال ضمانت دارد.","a small sealed card attached to a product"),
 ("warn","verb","/wɔːn/","هشدار دادن","She warned me about the traffic.","درباره ترافیک هشدارم داد.","a woman in her early thirties pointing seriously at a road"),
 ("prevent","verb","/prɪˈvent/","جلوگیری کردن","This prevents accidents.","این از حادثه جلوگیری می‌کند.","a safety barrier placed across an open edge"),
 ("avoid","verb","/əˈvɔɪd/","اجتناب کردن","We avoided the main road.","از جاده اصلی اجتناب کردیم.","a car taking a quieter side road"),
 ("check twice","phrase","/tʃek twaɪs/","دو بار بررسی کردن","Check twice before you send it.","قبل از فرستادن دو بار بررسی کن.","a hand rereading a page with a pen"),
 ("be prepared","phrase","/bi prɪˈpeəd/","آماده بودن","Be prepared for delays.","برای تأخیر آماده باش.","a packed bag standing ready by a door"),
 ("worst case","phrase","/wɜːst keɪs/","بدترین حالت","In the worst case, we'll walk.","در بدترین حالت پیاده می‌رویم.","two adults in their thirties setting off on foot"),
 ("safe side","phrase","/seɪf saɪd/","محض احتیاط","Let's be on the safe side.","بیا محض احتیاط عمل کنیم.","an extra spare item packed into a bag"),
 ("careless","adjective","/ˈkeələs/","بی‌دقت","That was careless.","بی‌دقتی بود.","a spilled cup beside scattered papers"),
 ("cautious","adjective","/ˈkɔːʃəs/","محتاط","He's a cautious driver.","راننده محتاطی است.","a driver in their thirties checking mirrors carefully"),
 ("just in time","phrase","/dʒʌst ɪn taɪm/","درست به‌موقع","We arrived just in time.","درست به‌موقع رسیدیم.","two adults in their thirties stepping through closing doors"),
]

V[12] = [
 ("must have","phrase","/mʌst həv/","حتماً … بوده","He must have forgotten.","حتماً فراموش کرده.","an unopened message on a phone left on a desk"),
 ("can't have","phrase","/kɑːnt həv/","محال است … بوده باشد","She can't have known.","محال است می‌دانسته.","a woman in her early thirties looking genuinely surprised"),
 ("might have","phrase","/maɪt həv/","شاید … بوده","They might have left early.","شاید زود رفته باشند.","an empty room with two chairs pushed back"),
 ("could have","phrase","/kʊd həv/","ممکن بود","It could have been worse.","می‌توانست بدتر باشد.","a small dent on an otherwise undamaged car"),
 ("guess","verb","/ɡes/","حدس زدن","I'm only guessing.","فقط حدس می‌زنم.","a man in his early thirties shrugging thoughtfully"),
 ("suspect","verb","/səˈspekt/","گمان بردن","I suspect he forgot.","گمان می‌کنم فراموش کرده.","a woman in her early thirties looking doubtfully at a closed door"),
 ("explanation","noun","/ˌekspləˈneɪʃn/","توضیح","There must be an explanation.","حتماً توضیحی هست.","two adults in their thirties studying a puzzling object"),
 ("clue","noun","/kluː/","سرنخ","We have no clue.","سرنخی نداریم.","a single unexplained item on an empty table"),
 ("possibility","noun","/ˌpɒsəˈbɪləti/","احتمال","That's one possibility.","این یک احتمال است.","two paths branching in a wood"),
 ("theory","noun","/ˈθɪəri/","فرضیه","I have a theory.","فرضیه‌ای دارم.","a diagram sketched on a notepad"),
 ("obvious","adjective","/ˈɒbviəs/","بدیهی","The answer is obvious.","جواب بدیهی است.","a single clear mark on an otherwise blank page"),
 ("unlikely","adjective","/ʌnˈlaɪkli/","بعید","That's unlikely.","بعید است.","a person in their thirties shaking their head at a suggestion"),
 ("certain","adjective","/ˈsɜːtn/","مطمئن","I'm certain about it.","درباره‌اش مطمئنم.","a man in his early thirties nodding firmly"),
 ("doubt","noun","/daʊt/","تردید","I have my doubts.","تردید دارم.","a woman in her early thirties pausing over a decision"),
 ("evidently","adverb","/ˈevɪdəntli/","ظاهراً، آشکارا","Evidently, nobody came.","آشکارا کسی نیامد.","an untouched table set for guests"),
 ("presumably","adverb","/prɪˈzjuːməbli/","احتمالاً","Presumably he's still working.","احتمالاً هنوز کار می‌کند.","a lit office window at night"),
 ("make sense","phrase","/meɪk sens/","منطقی بودن","That makes sense.","منطقی است.","two adults in their thirties nodding over a diagram"),
 ("figure out","phrase","/ˈfɪɡər aʊt/","سر در آوردن","I can't figure it out.","سر در نمی‌آورم.","a man in his early thirties frowning at a complex device"),
 ("turn out","phrase","/tɜːn aʊt/","از آب درآمدن","It turned out to be simple.","ساده از آب درآمد.","a simple solution revealed on an opened box"),
 ("no wonder","phrase","/nəʊ ˈwʌndə/","جای تعجب نیست","No wonder he was tired.","جای تعجب نیست که خسته بود.","a man in his early thirties asleep beside a long finished task"),
]

V[13] = [
 ("should have","phrase","/ʃʊd həv/","باید … می‌کردی","You should have told me.","باید بهم می‌گفتی.","a woman in her early thirties looking reproachfully at a colleague"),
 ("shouldn't have","phrase","/ˈʃʊdnt həv/","نباید … می‌کردی","I shouldn't have waited.","نباید صبر می‌کردم.","a man in his early thirties looking at a closed office door"),
 ("resent","verb","/rɪˈzent/","دلخور بودن","She resented the remark.","از آن حرف دلخور شد.","a woman in her early thirties turning away with a hurt expression"),
 ("blame","verb","/bleɪm/","سرزنش کردن","Don't blame yourself.","خودت را سرزنش نکن.","one adult in their thirties reassuring another"),
 ("criticise","verb","/ˈkrɪtɪsaɪz/","انتقاد کردن","He criticised the plan.","از برنامه انتقاد کرد.","a man in his early thirties pointing at a flaw on a chart"),
 ("apologise","verb","/əˈpɒlədʒaɪz/","عذرخواهی کردن","She apologised at once.","فوراً عذرخواهی کرد.","a woman in her early thirties speaking with a regretful gesture"),
 ("warn in advance","phrase","/wɔːn ɪn ədˈvɑːns/","از پیش خبر دادن","You should have warned me in advance.","باید از پیش خبرم می‌کردی.","a calendar with an unmarked but important day"),
 ("fault","noun","/fɔːlt/","تقصیر","It wasn't my fault.","تقصیر من نبود.","two adults in their thirties in a tense discussion"),
 ("excuse","noun","/ɪkˈskjuːs/","بهانه","That's not an excuse.","این بهانه نیست.","a man in his early thirties spreading his hands defensively"),
 ("complaint","noun","/kəmˈpleɪnt/","شکایت","We received a complaint.","شکایتی دریافت کردیم.","a written note handed across a counter"),
 ("criticism","noun","/ˈkrɪtɪsɪzəm/","انتقاد","It was fair criticism.","انتقاد منصفانه‌ای بود.","a marked-up page with careful notes"),
 ("responsibility for","phrase","/rɪˌspɒnsəˈbɪləti fɔː/","مسئولیتِ","He took responsibility for it.","مسئولیتش را پذیرفت.","a man in his early thirties signing a document calmly"),
 ("admit fault","phrase","/ədˈmɪt fɔːlt/","پذیرفتن اشتباه","It's hard to admit fault.","پذیرفتن اشتباه سخت است.","two adults in their thirties in an honest conversation"),
 ("make up for","phrase","/meɪk ʌp fɔː/","جبران کردن","I'll make up for it.","جبرانش می‌کنم.","a person in their thirties working late to finish a task"),
 ("let down","phrase","/let daʊn/","ناامید کردن","I don't want to let you down.","نمی‌خواهم ناامیدت کنم.","a man in his early thirties looking earnestly at a colleague"),
 ("unfair","adjective","/ʌnˈfeə/","ناعادلانه","That seems unfair.","ناعادلانه به‌نظر می‌رسد.","two unequal piles of work on one desk"),
 ("harsh","adjective","/hɑːʃ/","تند، خشن","That was a harsh reply.","پاسخ تندی بود.","a woman in her early thirties reacting to a blunt remark"),
 ("thoughtless","adjective","/ˈθɔːtləs/","بی‌ملاحظه","It was a thoughtless remark.","حرف بی‌ملاحظه‌ای بود.","a man in his early thirties looking away after speaking"),
 ("with hindsight","phrase","/wɪð ˈhaɪndsaɪt/","حالا که فکر می‌کنم","With hindsight, I was wrong.","حالا که فکر می‌کنم اشتباه می‌کردم.","a person in their thirties reviewing an old note"),
 ("lesson learned","phrase","/ˈlesn lɜːnd/","درس گرفته شد","Lesson learned.","درسش را گرفتم.","a closed notebook with a single underlined line"),
]

V[14] = [
 ("outcome","noun","/ˈaʊtkʌm/","نتیجه نهایی","The outcome was good.","نتیجه نهایی خوب بود.","a finished project displayed on a table"),
 ("alternative plan","phrase","/ɔːlˈtɜːnətɪv plæn/","برنامه جایگزین","We had an alternative plan.","برنامه جایگزین داشتیم.","two written plans side by side on a desk"),
 ("judgement","noun","/ˈdʒʌdʒmənt/","قضاوت","It was a matter of judgement.","مسئله قضاوت بود.","a two-pan balance on a desk"),
 ("hesitate","verb","/ˈhezɪteɪt/","تردید کردن","I hesitated too long.","زیادی تردید کردم.","a person in their thirties pausing before a doorway"),
 ("delay a decision","phrase","/dɪˈleɪ ə dɪˈsɪʒn/","تصمیم را عقب انداختن","We delayed the decision.","تصمیم را عقب انداختیم.","an unopened folder left on a desk"),
 ("act quickly","phrase","/ækt ˈkwɪkli/","سریع عمل کردن","We should have acted quickly.","باید سریع عمل می‌کردیم.","a person in their thirties moving decisively at a workbench"),
 ("timing","noun","/ˈtaɪmɪŋ/","زمان‌بندی","The timing was wrong.","زمان‌بندی اشتباه بود.","a clock beside an unfinished plan"),
 ("estimate","verb","/ˈestɪmeɪt/","تخمین زدن","We estimated the cost.","هزینه را تخمین زدیم.","a hand writing figures on a notepad"),
 ("underestimate","verb","/ˌʌndərˈestɪmeɪt/","دست‌کم گرفتن","We underestimated the work.","کار را دست‌کم گرفتیم.","a much larger pile of tasks than expected"),
 ("predict","verb","/prɪˈdɪkt/","پیش‌بینی کردن","Nobody predicted this.","کسی این را پیش‌بینی نکرد.","a weather chart with an unexpected pattern"),
 ("expectation","noun","/ˌekspekˈteɪʃn/","انتظار","It exceeded our expectations.","از انتظار ما فراتر رفت.","a chart with a line rising above a marked target"),
 ("assumption","noun","/əˈsʌmpʃn/","فرض","That was a wrong assumption.","فرض اشتباهی بود.","a crossed-out line on a plan"),
 ("in retrospect","phrase","/ɪn ˈretrəspekt/","حالا که برمی‌گردم","In retrospect, it was fine.","حالا که برمی‌گردم خوب بود.","a person in their thirties calmly reviewing old notes"),
 ("on balance","phrase","/ɒn ˈbæləns/","روی هم رفته","On balance, it worked.","روی هم رفته جواب داد.","a balance scale settling level"),
 ("better off","phrase","/ˈbetər ɒf/","بهتر بودن حال","We're better off now.","حالا حالمان بهتر است.","two adults in their thirties in a brighter, tidier workspace"),
 ("worth trying","phrase","/wɜːθ ˈtraɪɪŋ/","ارزش امتحان دارد","It was worth trying.","ارزش امتحان داشت.","a man in his early thirties testing a new tool"),
 ("effective","adjective","/ɪˈfektɪv/","مؤثر","It was an effective method.","روش مؤثری بود.","a clean result produced by a simple process"),
 ("pointless","adjective","/ˈpɔɪntləs/","بی‌فایده","That would be pointless.","بی‌فایده می‌بود.","a person in their thirties setting aside an unused tool"),
 ("inevitable","adjective","/ɪnˈevɪtəbl/","اجتناب‌ناپذیر","The delay was inevitable.","تأخیر اجتناب‌ناپذیر بود.","heavy rain falling on a closed worksite"),
 ("all things considered","phrase","/ɔːl θɪŋz kənˈsɪdəd/","با در نظر گرفتن همه‌چیز","All things considered, it went well.","با در نظر گرفتن همه‌چیز خوب پیش رفت.","two adults in their thirties nodding over completed work"),
]

V[15] = [
 ("experience","noun","/ɪkˈspɪəriəns/","تجربه","It was a useful experience.","تجربه مفیدی بود.","a woman in her early thirties confidently guiding a colleague"),
 ("lesson","noun","/ˈlesn/","درس، عبرت","That was a hard lesson.","درس سختی بود.","an underlined note in a well-used notebook"),
 ("turning point","phrase","/ˈtɜːnɪŋ pɔɪnt/","نقطه عطف","It was a turning point.","نقطه عطف بود.","a sharp bend in a mountain road"),
 ("look back on","phrase","/lʊk bæk ɒn/","به … نگاه کردن (گذشته)","I look back on it fondly.","با خوشی به آن نگاه می‌کنم.","a person in their thirties smiling at an old photograph"),
 ("milestone","noun","/ˈmaɪlstəʊn/","نقطه مهم","It was an important milestone.","نقطه مهمی بود.","a marked stone beside a long path"),
 ("failure","noun","/ˈfeɪljə/","شکست","Failure teaches a lot.","شکست چیزهای زیادی یاد می‌دهد.","a man in his early thirties starting again at a workbench"),
 ("setback","noun","/ˈsetbæk/","عقبگرد","It was a small setback.","عقبگرد کوچکی بود.","a chart dipping briefly then rising again"),
 ("recovery","noun","/rɪˈkʌvəri/","بازیابی","The recovery took months.","بازیابی ماه‌ها طول کشید.","a plant regrowing after being cut back"),
 ("determination","noun","/dɪˌtɜːmɪˈneɪʃn/","عزم","She showed real determination.","عزم واقعی نشان داد.","a woman in her early thirties climbing a steep path"),
 ("motivation","noun","/ˌməʊtɪˈveɪʃn/","انگیزه","I lost motivation for a while.","مدتی انگیزه‌ام را از دست دادم.","an unopened notebook on a dusty desk"),
 ("give up","phrase","/ɡɪv ʌp/","تسلیم شدن","I almost gave up.","نزدیک بود تسلیم شوم.","a person in their thirties pausing halfway up a hill"),
 ("keep going","phrase","/kiːp ˈɡəʊɪŋ/","ادامه دادن","I kept going anyway.","با این حال ادامه دادم.","a walker in their thirties continuing up a path"),
 ("stick with","phrase","/stɪk wɪð/","پای … ماندن","I stuck with it.","پایش ماندم.","a man in his early thirties returning to the same task each day"),
 ("pay off","phrase","/peɪ ɒf/","نتیجه دادن","The effort paid off.","تلاش نتیجه داد.","a completed project beside a stack of drafts"),
 ("worthwhile","adjective","/ˌwɜːθˈwaɪl/","ارزشمند","It was worthwhile.","ارزشمند بود.","a woman in her early thirties looking satisfied at finished work"),
 ("tough","adjective","/tʌf/","دشوار","It was a tough year.","سال دشواری بود.","a steep path under a grey sky"),
 ("valuable","adjective","/ˈvæljuəbl/","باارزش","It was valuable advice.","نصیحت باارزشی بود.","two adults in their thirties in a serious helpful conversation"),
 ("in hindsight","phrase","/ɪn ˈhaɪndsaɪt/","حالا که نگاه می‌کنم","In hindsight, it helped.","حالا که نگاه می‌کنم کمک کرد.","a person in their thirties reviewing old pages with a calm smile"),
 ("no regrets","phrase","/nəʊ rɪˈɡrets/","بدون پشیمانی","I have no regrets.","پشیمان نیستم.","a man in his early thirties looking back calmly along a path"),
 ("proud moment","phrase","/praʊd ˈməʊmənt/","لحظه افتخار","It was a proud moment.","لحظه افتخار بود.","colleagues in their thirties applauding one of them"),
]

V[16] = [
 ("interview","noun","/ˈɪntəvjuː/","مصاحبه","The interview went well.","مصاحبه خوب پیش رفت.","two adults in their thirties seated across a desk in a formal conversation"),
 ("candidate","noun","/ˈkændɪdət/","داوطلب","There were five candidates.","پنج داوطلب بودند.","several adults in their thirties waiting in a corridor"),
 ("question","verb","/ˈkwestʃən/","پرسیدن، بازپرسی","They questioned him for an hour.","یک ساعت از او پرسیدند.","a man in his early thirties answering across a plain table"),
 ("enquire","verb","/ɪnˈkwaɪə/","پرس‌وجو کردن","She enquired about the job.","درباره شغل پرس‌وجو کرد.","a woman in her early thirties speaking at a reception desk"),
 ("wonder","verb","/ˈwʌndə/","کنجکاو بودن","I wondered where he lived.","کنجکاو بودم کجا زندگی می‌کند.","a person in their thirties looking thoughtfully out of a window"),
 ("clarify","verb","/ˈklærɪfaɪ/","روشن کردن","Could you clarify that?","می‌شود آن را روشن کنید؟","a hand underlining a line on a page"),
 ("qualification","noun","/ˌkwɒlɪfɪˈkeɪʃn/","مدرک، صلاحیت","What qualifications do you have?","چه مدارکی دارید؟","a plain framed certificate on a wall"),
 ("background check","phrase","/ˈbækɡraʊnd tʃek/","بررسی سوابق","They did a background check.","سوابق را بررسی کردند.","a folder of documents open on a desk"),
 ("previous job","phrase","/ˈpriːviəs dʒɒb/","شغل قبلی","Tell me about your previous job.","درباره شغل قبلی‌ات بگو.","a man in his early thirties describing his work to a listener"),
 ("strength","noun","/streŋθ/","نقطه قوت","What's your main strength?","نقطه قوت اصلی‌ات چیست؟","a woman in her early thirties speaking confidently in an interview"),
 ("weakness","noun","/ˈwiːknəs/","نقطه ضعف","Everyone has weaknesses.","هرکسی نقطه ضعف دارد.","a man in his early thirties speaking honestly across a table"),
 ("salary expectation","phrase","/ˈsæləri ˌekspekˈteɪʃn/","انتظار حقوقی","What's your salary expectation?","انتظار حقوقی‌ات چقدر است؟","a payslip and a pen on a desk"),
 ("nervous","adjective","/ˈnɜːvəs/","مضطرب","I was nervous at first.","اول مضطرب بودم.","a woman in her early thirties waiting with clasped hands"),
 ("prepared","adjective","/prɪˈpeəd/","آماده","I felt well prepared.","احساس آمادگی می‌کردم.","a man in his early thirties reviewing notes before a meeting"),
 ("impressed","adjective","/ɪmˈprest/","تحت تأثیر","They were impressed.","تحت تأثیر قرار گرفتند.","two adults in their thirties nodding approvingly"),
 ("follow up","phrase","/ˈfɒləʊ ʌp/","پیگیری کردن","I'll follow up next week.","هفته آینده پیگیری می‌کنم.","a person in their thirties writing a reminder in a planner"),
 ("get back to","phrase","/ɡet bæk tuː/","جواب دادن به","We'll get back to you.","به شما جواب می‌دهیم.","a woman in her early thirties closing a folder with a polite smile"),
 ("turn down","phrase","/tɜːn daʊn/","رد کردن","They turned down my offer.","پیشنهادم را رد کردند.","a returned envelope on a desk"),
 ("accept an offer","phrase","/əkˈsept ən ˈɒfə/","پذیرفتن پیشنهاد","She accepted the offer.","پیشنهاد را پذیرفت.","a woman in her early thirties signing a document with a smile"),
 ("in writing","phrase","/ɪn ˈraɪtɪŋ/","کتبی","Please send it in writing.","لطفاً کتبی بفرستید.","a printed letter on a desk"),
]

V[17] = [
 ("suggest","verb","/səˈdʒest/","پیشنهاد دادن","He suggested waiting.","پیشنهاد داد صبر کنیم.","a man in his early thirties raising a point at a meeting table"),
 ("recommend","verb","/ˌrekəˈmend/","توصیه کردن","She recommended a different method.","روش دیگری توصیه کرد.","a woman in her early thirties pointing at an option on a chart"),
 ("advise","verb","/ədˈvaɪz/","سفارش کردن","They advised us to wait.","به ما سفارش کردند صبر کنیم.","two adults in their thirties in a serious advisory conversation"),
 ("agree to","phrase","/əˈɡriː tuː/","موافقت کردن با","We agreed to postpone it.","موافقت کردیم عقبش بیندازیم.","two adults in their thirties nodding over a shared plan"),
 ("offer to","phrase","/ˈɒfə tuː/","پیشنهاد دادن به","He offered to help.","پیشنهاد داد کمک کند.","a man in his early thirties reaching to take a heavy box"),
 ("promise to","phrase","/ˈprɒmɪs tuː/","قول دادن به","She promised to check it.","قول داد بررسی‌اش کند.","two adults in their thirties in a firm handshake"),
 ("remind","verb","/rɪˈmaɪnd/","یادآوری کردن","Remind me to call him.","یادم بیاور بهش زنگ بزنم.","a note stuck on a monitor"),
 ("agenda","noun","/əˈdʒendə/","دستور جلسه","What's on the agenda?","دستور جلسه چیست؟","a printed list on a meeting table"),
 ("minutes","noun","/ˈmɪnɪts/","صورت‌جلسه","Who's taking the minutes?","صورت‌جلسه را چه کسی می‌نویسد؟","a person in their thirties writing during a meeting"),
 ("proposal","noun","/prəˈpəʊzl/","پیشنهاد (رسمی)","The proposal was accepted.","پیشنهاد پذیرفته شد.","a bound document on a meeting table"),
 ("summary","noun","/ˈsʌməri/","خلاصه","Here's a short summary.","این خلاصه کوتاهی است.","a single page with a few lines on a desk"),
 ("point out","phrase","/pɔɪnt aʊt/","خاطرنشان کردن","She pointed out the risk.","خطر را خاطرنشان کرد.","a woman in her early thirties indicating a mark on a chart"),
 ("bring up","phrase","/brɪŋ ʌp/","مطرح کردن","He brought up the cost.","هزینه را مطرح کرد.","a man in his early thirties speaking at a meeting"),
 ("sum up","phrase","/sʌm ʌp/","جمع‌بندی کردن","Let me sum up.","بگذارید جمع‌بندی کنم.","a person in their thirties closing a meeting with a final note"),
 ("go over","phrase","/ɡəʊ ˈəʊvə/","مرور کردن","Let's go over it again.","بیا دوباره مرورش کنیم.","two adults in their thirties rereading a document together"),
 ("look into","phrase","/lʊk ˈɪntuː/","بررسی کردن","We'll look into it.","بررسی‌اش می‌کنیم.","a person in their thirties examining a report closely"),
 ("productive","adjective","/prəˈdʌktɪv/","پربار","It was a productive meeting.","جلسه پرباری بود.","a whiteboard filled with organised notes"),
 ("brief","adjective","/briːf/","کوتاه","Keep it brief, please.","لطفاً کوتاه نگه دار.","a single short note on a desk"),
 ("unanimous","adjective","/juˈnænɪməs/","اتفاق‌نظر","The decision was unanimous.","تصمیم به اتفاق‌نظر گرفته شد.","several adults in their thirties raising hands together"),
 ("action point","phrase","/ˈækʃn pɔɪnt/","اقدام لازم","There are three action points.","سه اقدام لازم هست.","a checklist with three unticked boxes"),
]

V[18] = [
 ("refuse","verb","/rɪˈfjuːz/","رد کردن","They refused to accept it.","نپذیرفتند.","a man in his early thirties raising a hand in refusal"),
 ("object to","phrase","/əbˈdʒekt tuː/","مخالفت کردن با","She objected to the change.","با تغییر مخالفت کرد.","a woman in her early thirties speaking firmly at a meeting"),
 ("disagree with","phrase","/ˌdɪsəˈɡriː wɪð/","مخالف بودن با","I disagree with that.","با آن مخالفم.","two adults in their thirties in a respectful disagreement"),
 ("argue","verb","/ˈɑːɡjuː/","بحث کردن","They argued for an hour.","یک ساعت بحث کردند.","two adults in their thirties in an animated discussion"),
 ("negotiate","verb","/nɪˈɡəʊʃieɪt/","مذاکره کردن","We negotiated a better price.","قیمت بهتری مذاکره کردیم.","two adults in their thirties across a table with documents"),
 ("persuade","verb","/pəˈsweɪd/","متقاعد کردن","He persuaded us to wait.","متقاعدمان کرد صبر کنیم.","a man in his early thirties explaining with an open convincing gesture"),
 ("insist on","phrase","/ɪnˈsɪst ɒn/","اصرار کردن بر","She insisted on a written reply.","بر پاسخ کتبی اصرار کرد.","a woman in her early thirties tapping a document firmly"),
 ("give in","phrase","/ɡɪv ɪn/","کوتاه آمدن","In the end he gave in.","آخر کوتاه آمد.","a man in his early thirties nodding reluctantly"),
 ("meet halfway","phrase","/miːt ˈhɑːfweɪ/","به توافق میانه رسیدن","Let's meet halfway.","بیا به توافق میانه برسیم.","two adults in their thirties shaking hands over a divided page"),
 ("dispute","noun","/dɪˈspjuːt/","اختلاف","It was a small dispute.","اختلاف کوچکی بود.","two adults in their thirties with differing notes on a table"),
 ("condition","noun","/kənˈdɪʃn/","شرط","We accepted on one condition.","با یک شرط پذیرفتیم.","a single underlined line in a contract"),
 ("agreement","noun","/əˈɡriːmənt/","توافق","We reached an agreement.","به توافق رسیدیم.","two adults in their thirties signing the same page"),
 ("contract","noun","/ˈkɒntrækt/","قرارداد","Read the contract carefully.","قرارداد را با دقت بخوان.","a multi-page document with a pen resting on it"),
 ("terms","noun","/tɜːmz/","شرایط","The terms are clear.","شرایط روشن است.","a printed list of numbered clauses"),
 ("firm","adjective","/fɜːm/","محکم","He was firm about it.","درباره‌اش محکم بود.","a man in his early thirties with a steady unmoving posture"),
 ("flexible","adjective","/ˈfleksəbl/","انعطاف‌پذیر","We can be flexible.","می‌توانیم انعطاف‌پذیر باشیم.","a woman in her early thirties adjusting entries in a planner"),
 ("stubborn","adjective","/ˈstʌbən/","لجباز","He can be stubborn.","می‌تواند لجباز باشد.","a man in his early thirties with folded arms"),
 ("reasonable offer","phrase","/ˈriːznəbl ˈɒfə/","پیشنهاد منصفانه","It was a reasonable offer.","پیشنهاد منصفانه‌ای بود.","a written figure shown across a table"),
 ("break down","phrase","/breɪk daʊn/","شکست خوردن (مذاکره)","The talks broke down.","مذاکرات شکست خورد.","two adults in their thirties leaving a table in opposite directions"),
 ("come to terms","phrase","/kʌm tə tɜːmz/","به توافق رسیدن","They finally came to terms.","سرانجام به توافق رسیدند.","two adults in their thirties shaking hands over a signed page"),
]

V[19] = [
 ("in other words","phrase","/ɪn ˈʌðə wɜːdz/","به عبارت دیگر","In other words, we can't go.","به عبارت دیگر نمی‌توانیم برویم.","a woman in her early thirties rephrasing with a clear gesture"),
 ("that is to say","phrase","/ðæt ɪz tə seɪ/","یعنی","That is to say, it's finished.","یعنی تمام شده.","a hand underlining a single line on a page"),
 ("for example","phrase","/fər ɪɡˈzɑːmpl/","برای مثال","For example, take this case.","برای مثال این مورد را ببین.","a single item picked out from a group on a table"),
 ("such as","phrase","/sʌtʃ əz/","مانند","Tools such as this one.","ابزارهایی مانند این.","several similar tools laid out with one highlighted"),
 ("rephrase","verb","/ˌriːˈfreɪz/","بازگویی کردن","Let me rephrase that.","بگذار دوباره بگویم.","a person in their thirties rewriting a line on a notepad"),
 ("simplify","verb","/ˈsɪmplɪfaɪ/","ساده کردن","Can you simplify it?","می‌شود ساده‌اش کنی؟","a complex diagram beside a simpler version"),
 ("emphasise","verb","/ˈemfəsaɪz/","تأکید کردن","I want to emphasise this point.","می‌خواهم بر این نکته تأکید کنم.","a hand pressing a marker on one line"),
 ("illustrate","verb","/ˈɪləstreɪt/","نشان دادن با مثال","Let me illustrate with an example.","بگذار با مثالی نشان دهم.","a person in their thirties sketching a quick diagram"),
 ("main point","phrase","/meɪn pɔɪnt/","نکته اصلی","What's the main point?","نکته اصلی چیست؟","a single bold line at the top of a page"),
 ("in short","phrase","/ɪn ʃɔːt/","خلاصه اینکه","In short, we agreed.","خلاصه اینکه توافق کردیم.","a short handwritten note on a desk"),
 ("in general","phrase","/ɪn ˈdʒenrəl/","به‌طور کلی","In general, it works well.","به‌طور کلی خوب کار می‌کند.","a wide view of a smoothly running workshop"),
 ("specifically","adverb","/spəˈsɪfɪkli/","به‌طور مشخص","Specifically, this part failed.","به‌طور مشخص این بخش خراب شد.","a finger pointing at one component"),
 ("roughly","adverb","/ˈrʌfli/","تقریباً","Roughly two hundred people came.","تقریباً دویست نفر آمدند.","a large gathering seen from above"),
 ("basically","adverb","/ˈbeɪsɪkli/","اساساً","Basically, it's the same.","اساساً یکی است.","two nearly identical items side by side"),
 ("clarification","noun","/ˌklærɪfɪˈkeɪʃn/","شفاف‌سازی","I need some clarification.","کمی شفاف‌سازی لازم دارم.","a person in their thirties asking a question at a meeting"),
 ("misunderstand","verb","/ˌmɪsʌndəˈstænd/","بد فهمیدن","Don't misunderstand me.","بد برداشت نکن.","two adults in their thirties clarifying something across a table"),
 ("get the point","phrase","/ɡet ðə pɔɪnt/","منظور را گرفتن","I get the point.","منظورت را گرفتم.","a man in his early thirties nodding with sudden understanding"),
 ("make it clear","phrase","/meɪk ɪt klɪə/","روشن کردن","Let me make it clear.","بگذار روشنش کنم.","a hand drawing a clean line under a heading"),
 ("as I said","phrase","/əz aɪ sed/","همان‌طور که گفتم","As I said, it's finished.","همان‌طور که گفتم تمام شده.","a person in their thirties gesturing back to an earlier note"),
 ("to put it simply","phrase","/tə pʊt ɪt ˈsɪmpli/","ساده بگویم","To put it simply, it failed.","ساده بگویم، شکست خورد.","a simple diagram replacing a complicated one"),
]

V[20] = [
 ("report","noun","/rɪˈpɔːt/","گزارش","The report was written last month.","گزارش ماه پیش نوشته شد.","a bound document on an office desk"),
 ("author","noun","/ˈɔːθə/","نویسنده","The author is unknown.","نویسنده‌اش نامعلوم است.","an unsigned page on a desk"),
 ("publish","verb","/ˈpʌblɪʃ/","به چاپ رساندن","It was published in May.","در اردیبهشت به چاپ رسید.","printed copies stacked on a table"),
 ("submit","verb","/səbˈmɪt/","ارائه دادن","The form was submitted online.","فرم آنلاین ارائه شد.","a hand placing a completed form in a tray"),
 ("review","verb","/rɪˈvjuː/","بازبینی کردن","The plan is being reviewed.","برنامه در حال بازبینی است.","two adults in their thirties reading a document together"),
 ("release","verb","/rɪˈliːs/","منتشر کردن","The figures were released today.","ارقام امروز منتشر شد.","a chart displayed on a screen in an office"),
 ("announce","verb","/əˈnaʊns/","اعلام کردن","The result was announced.","نتیجه اعلام شد.","a person in their thirties speaking to a gathered group"),
 ("appoint","verb","/əˈpɔɪnt/","منصوب کردن","A new manager was appointed.","مدیر تازه‌ای منصوب شد.","a person in their thirties being welcomed into an office"),
 ("figure","noun","/ˈfɪɡə/","رقم","The figures are accurate.","ارقام دقیق‌اند.","a printed table of numbers"),
 ("survey","noun","/ˈsɜːveɪ/","نظرسنجی","A survey was carried out.","نظرسنجی انجام شد.","a clipboard with a plain response sheet"),
 ("committee","noun","/kəˈmɪti/","کمیته","The committee has decided.","کمیته تصمیم گرفته.","several adults in their thirties seated around a long table"),
 ("authority","noun","/ɔːˈθɒrəti/","مرجع، مقام","The local authority approved it.","مقام محلی تأییدش کرد.","an official-looking building entrance"),
 ("regulation","noun","/ˌreɡjuˈleɪʃn/","مقررات","New regulations were introduced.","مقررات تازه‌ای وضع شد.","a printed rule book on a desk"),
 ("bulletin","noun","/ˈbʊlətɪn/","اطلاعیه","A bulletin was posted.","اطلاعیه‌ای نصب شد.","a printed sheet pinned to a public board"),
 ("official","adjective","/əˈfɪʃl/","رسمی","It's an official document.","سند رسمی‌ای است.","a stamped page in a folder"),
 ("formal","adjective","/ˈfɔːml/","رسمی (سبک)","The tone is formal.","لحن رسمی است.","a neatly typed letter on headed paper"),
 ("anonymous","adjective","/əˈnɒnɪməs/","ناشناس","The complaint was anonymous.","شکایت ناشناس بود.","an unsigned letter on a desk"),
 ("be given","phrase","/bi ˈɡɪvn/","داده شدن","We were given two weeks.","به ما دو هفته داده شد.","a calendar with a two-week span marked"),
 ("be told","phrase","/bi təʊld/","گفته شدن به","We were told to wait.","به ما گفته شد صبر کنیم.","adults in their thirties seated in a waiting area"),
 ("be asked","phrase","/bi ɑːskt/","خواسته شدن از","We were asked to sign.","از ما خواسته شد امضا کنیم.","a pen resting on a signature line"),
]
