# -*- coding: utf-8 -*-
"""
واژگان دروس ۴ تا ۱۰ سطح A2 — گذشته با جزئیات، و آینده.

قاعده انتخاب همان `data_a2_01_10.py`: هیچ واژه‌ای از A1 تکرار نمی‌شود،
و هر واژه باید با گرامر همان درس قابل استفاده باشد.
"""

V = {}

V[4] = [
 ("while","conjunction","/waɪl/","در حالی که","She called while I was cooking.","وقتی داشتم آشپزی می‌کردم زنگ زد.","a woman in her early thirties answering a phone with one hand while stirring a pot"),
 ("suddenly","adverb","/ˈsʌdnli/","ناگهان","Suddenly the lights went out.","ناگهان برق رفت.","a dim room lit only by a window, a person pausing mid-action"),
 ("happen","verb","/ˈhæpən/","اتفاق افتادن","What happened yesterday?","دیروز چه اتفاقی افتاد؟","two adults in their thirties talking with concerned expressions"),
 ("break","verb","/breɪk/","شکستن","I broke a glass this morning.","امروز صبح یک لیوان شکستم.","broken glass pieces on a kitchen floor beside a dustpan"),
 ("drop","verb","/drɒp/","انداختن","He dropped his keys.","کلیدهایش را انداخت.","a set of keys on the pavement beside a person's shoe"),
 ("fall","verb","/fɔːl/","افتادن","She fell on the stairs.","روی پله‌ها افتاد.","a woman in her early thirties holding a stair rail carefully"),
 ("shout","verb","/ʃaʊt/","فریاد زدن","Someone shouted outside.","کسی بیرون فریاد زد.","a man in his early thirties turning sharply towards an open window"),
 ("knock","verb","/nɒk/","در زدن","Someone knocked at the door.","کسی در زد.","a hand knocking on a wooden apartment door"),
 ("ring","verb","/rɪŋ/","زنگ خوردن","The phone rang twice.","تلفن دو بار زنگ خورد.","a mobile phone lighting up on a table"),
 ("wait for","verb","/ˈweɪt fɔː/","منتظر ماندن","I was waiting for the bus.","منتظر اتوبوس بودم.","a woman in her early thirties standing at a bus stop looking down the road"),
 ("rain","verb","/reɪn/","باریدن","It was raining hard.","باران شدیدی می‌بارید.","heavy rain falling on a city street with wet pavement"),
 ("traffic","noun","/ˈtræfɪk/","ترافیک","We were stuck in traffic.","در ترافیک گیر کرده بودیم.","a line of cars stopped bumper to bumper on a city road"),
 ("accident","noun","/ˈæksɪdənt/","حادثه","There was a small accident.","حادثه کوچکی رخ داد.","a traffic cone and warning triangle placed on a road"),
 ("smoke","noun","/sməʊk/","دود","I smelled smoke.","بوی دود آمد.","thin smoke rising from a pan on a stove"),
 ("electricity","noun","/ɪlekˈtrɪsəti/","برق","The electricity went off.","برق رفت.","a dark room with a torch beam on a wall"),
 ("candle","noun","/ˈkændl/","شمع","We lit a candle.","شمعی روشن کردیم.","a lit candle on a table in a dim room"),
 ("just then","phrase","/ˈdʒʌst ðen/","درست همان موقع","Just then, the door opened.","درست همان موقع در باز شد.","a door swinging open into a lit hallway"),
 ("luckily","adverb","/ˈlʌkɪli/","خوشبختانه","Luckily, nobody was hurt.","خوشبختانه کسی آسیب ندید.","two adults in their thirties looking relieved on a pavement"),
 ("dangerous","adjective","/ˈdeɪndʒərəs/","خطرناک","The road was dangerous.","جاده خطرناک بود.","a narrow mountain road with a steep drop beside it"),
 ("careful","adjective","/ˈkeəfl/","مراقب","Be careful on the stairs.","روی پله‌ها مراقب باش.","a woman in her early thirties holding a handrail while descending stairs"),
]

V[5] = [
 ("story","noun","/ˈstɔːri/","داستان","Tell me the whole story.","کل داستان را برایم بگو.","two adults in their thirties talking closely over cups of tea"),
 ("beginning","noun","/bɪˈɡɪnɪŋ/","آغاز","At the beginning, I was nervous.","اولش مضطرب بودم.","a woman in her early thirties taking a deep breath before entering a room"),
 ("end","noun","/end/","پایان","In the end, everything was fine.","در پایان همه‌چیز خوب شد.","two adults in their thirties smiling with relief"),
 ("then","adverb","/ðen/","بعد","Then we went home.","بعد به خانه رفتیم.","two adults in their thirties walking towards a lit doorway at dusk"),
 ("after that","phrase","/ˈɑːftə ðæt/","بعد از آن","After that, we had dinner.","بعد از آن شام خوردیم.","a set dinner table with two chairs pulled out"),
 ("finally","adverb","/ˈfaɪnəli/","سرانجام","Finally, the bus arrived.","سرانجام اتوبوس رسید.","a bus pulling up to a stop where a person is waiting"),
 ("realise","verb","/ˈrɪəlaɪz/","متوجه شدن","I realised I was late.","متوجه شدم دیرم شده.","a man in his early thirties glancing at a watch with a startled expression"),
 ("decide","verb","/dɪˈsaɪd/","تصمیم گرفتن","We decided to walk.","تصمیم گرفتیم پیاده برویم.","two adults in their thirties setting off on foot along a path"),
 ("explain","verb","/ɪkˈspleɪn/","توضیح دادن","She explained everything.","همه‌چیز را توضیح داد.","a woman in her early thirties gesturing while speaking to a listener"),
 ("promise","verb","/ˈprɒmɪs/","قول دادن","He promised to come.","قول داد بیاید.","two adults in their thirties shaking hands warmly"),
 ("laugh","verb","/lɑːf/","خندیدن","We all laughed.","همه خندیدیم.","three adults in their thirties laughing together around a table"),
 ("cry","verb","/kraɪ/","گریه کردن","She almost cried.","نزدیک بود گریه کند.","a woman in her early thirties wiping her eye with a tissue"),
 ("worry","verb","/ˈwʌri/","نگران بودن","Don't worry about it.","نگرانش نباش.","a man in his early thirties placing a reassuring hand on a friend's shoulder"),
 ("surprise","noun","/səˈpraɪz/","سورپرایز","It was a nice surprise.","سورپرایز خوبی بود.","a woman in her early thirties opening a wrapped gift with delight"),
 ("problem","noun","/ˈprɒbləm/","مشکل","We had a small problem.","مشکل کوچکی داشتیم.","two adults in their thirties looking at a broken object together"),
 ("solution","noun","/səˈluːʃn/","راه‌حل","We found a solution.","راه‌حلی پیدا کردیم.","two adults in their thirties nodding in agreement over a notebook"),
 ("luck","noun","/lʌk/","شانس","It was pure luck.","خالص شانس بود.","a man in his early thirties smiling in disbelief at something in his hand"),
 ("nervous","adjective","/ˈnɜːvəs/","مضطرب","I was very nervous.","خیلی مضطرب بودم.","a woman in her early thirties clasping her hands before an interview"),
 ("excited","adjective","/ɪkˈsaɪtɪd/","هیجان‌زده","We were so excited.","خیلی هیجان‌زده بودیم.","two adults in their thirties with bright eager expressions"),
 ("strange","adjective","/streɪndʒ/","عجیب","It was a strange day.","روز عجیبی بود.","a man in his early thirties looking around with a puzzled expression"),
]

V[6] = [
 ("will","modal verb","/wɪl/","خواهد","I'll help you.","کمکت می‌کنم.","a man in his early thirties reaching out to carry a heavy bag for someone"),
 ("definitely","adverb","/ˈdefɪnətli/","قطعاً","I'll definitely be there.","قطعاً آنجا خواهم بود.","a man in his early thirties nodding firmly with a confident expression"),
 ("offer","verb","/ˈɒfə/","پیشنهاد دادن","She offered to drive.","پیشنهاد داد رانندگی کند.","a woman in her early thirties holding up car keys towards a friend"),
 ("carry","verb","/ˈkæri/","حمل کردن","I'll carry that for you.","آن را برایت می‌برم.","a man in his early thirties lifting a box for another person"),
 ("open","verb","/ˈəʊpən/","باز کردن","I'll open the window.","پنجره را باز می‌کنم.","a woman in her early thirties pushing a window open"),
 ("close","verb","/kləʊz/","بستن","I'll close the door.","در را می‌بندم.","a hand pushing a door closed"),
 ("bring","verb","/brɪŋ/","آوردن","I'll bring some tea.","کمی چای می‌آورم.","a man in his early thirties carrying a tray with two tea glasses"),
 ("send","verb","/send/","فرستادن","I'll send you the address.","نشانی را برایت می‌فرستم.","a woman in her early thirties typing a message on a phone"),
 ("check","verb","/tʃek/","بررسی کردن","I'll check the time.","ساعت را بررسی می‌کنم.","a man in his early thirties looking at a wall clock"),
 ("probably","adverb","/ˈprɒbəbli/","احتمالاً","It'll probably rain.","احتمالاً باران می‌بارد.","grey clouds gathering over a city skyline"),
 ("maybe","adverb","/ˈmeɪbi/","شاید","Maybe I'll come later.","شاید بعداً بیایم.","a woman in her early thirties with an uncertain thoughtful expression"),
 ("sure","adjective","/ʃɔː/","مطمئن","I'm sure it'll be fine.","مطمئنم خوب می‌شود.","a man in his early thirties nodding confidently"),
 ("future","noun","/ˈfjuːtʃə/","آینده","Nobody knows the future.","هیچ‌کس آینده را نمی‌داند.","a long open road stretching towards a bright horizon"),
 ("help","noun","/help/","کمک","Do you need any help?","کمکی لازم داری؟","a woman in her early thirties offering a hand to someone with bags"),
 ("favour","noun","/ˈfeɪvə/","لطف","Can I ask you a favour?","می‌توانم لطفی بخواهم؟","two adults in their thirties talking with friendly open gestures"),
 ("later","adverb","/ˈleɪtə/","بعداً","I'll call you later.","بعداً بهت زنگ می‌زنم.","a man in his early thirties waving goodbye while holding a phone"),
 ("soon","adverb","/suːn/","به‌زودی","I'll be there soon.","به‌زودی آنجا خواهم بود.","a woman in her early thirties walking briskly towards a building"),
 ("of course","phrase","/əv ˈkɔːs/","البته","Of course I'll help.","البته که کمک می‌کنم.","a man in his early thirties nodding warmly with an open gesture"),
 ("worried","adjective","/ˈwʌrid/","نگران","Don't be worried.","نگران نباش.","a woman in her early thirties comforting a friend with a hand on the arm"),
 ("ready","adjective","/ˈredi/","آماده","I'll be ready at six.","ساعت شش آماده‌ام.","a man in his early thirties standing with a coat and bag by the door"),
]

V[7] = [
 ("meeting","noun","/ˈmiːtɪŋ/","جلسه","We have a meeting at six.","ساعت شش جلسه داریم.","several adults in their thirties seated around a conference table"),
 ("appointment","noun","/əˈpɔɪntmənt/","قرار ملاقات","I have an appointment tomorrow.","فردا قرار ملاقات دارم.","a plain wall calendar with a marked day"),
 ("plan","noun","/plæn/","برنامه","What are your plans?","برنامه‌هایت چیست؟","a woman in her early thirties writing on a blank notepad"),
 ("invite","verb","/ɪnˈvaɪt/","دعوت کردن","She invited us for dinner.","ما را برای شام دعوت کرد.","a woman in her early thirties welcoming guests at her door"),
 ("join","verb","/dʒɔɪn/","ملحق شدن","Will you join us?","به ما ملحق می‌شوی؟","a group of adults in their thirties making room at a table for another"),
 ("book","verb","/bʊk/","رزرو کردن","I'm booking a table.","دارم میز رزرو می‌کنم.","a man in his early thirties making a reservation on a laptop"),
 ("cancel","verb","/ˈkænsl/","لغو کردن","I had to cancel it.","مجبور شدم لغوش کنم.","a crossed-out mark on a plain paper planner"),
 ("postpone","verb","/pəˈspəʊn/","به تعویق انداختن","We postponed the trip.","سفر را عقب انداختیم.","a packed suitcase left unopened beside a door"),
 ("arrange","verb","/əˈreɪndʒ/","ترتیب دادن","I'll arrange everything.","همه‌چیز را ترتیب می‌دهم.","a woman in her early thirties organising items on a desk"),
 ("confirm","verb","/kənˈfɜːm/","تأیید کردن","Please confirm the time.","لطفاً ساعت را تأیید کن.","a man in his early thirties giving a thumbs up while on a phone call"),
 ("free","adjective","/friː/","آزاد","Are you free on Friday?","جمعه آزادی؟","a woman in her early thirties relaxing with nothing scheduled"),
 ("busy","adjective","/ˈbɪzi/","گرفتار","I'm busy that day.","آن روز گرفتارم.","a man in his early thirties surrounded by work at a desk"),
 ("weekend","noun","/ˌwiːkˈend/","آخر هفته","We're meeting at the weekend.","آخر هفته همدیگر را می‌بینیم.","two adults in their thirties relaxing outdoors on a bright day"),
 ("guest","noun","/ɡest/","مهمان","We have guests tonight.","امشب مهمان داریم.","a set table with extra chairs for visitors"),
 ("party","noun","/ˈpɑːti/","مهمانی","There's a party on Friday.","جمعه مهمانی هست.","adults in their thirties gathered around a table with refreshments"),
 ("dinner","noun","/ˈdɪnə/","شام","We're having dinner together.","با هم شام می‌خوریم.","a warm dinner spread on a table in evening light"),
 ("time","noun","/taɪm/","زمان","What time works for you?","چه ساعتی برایت خوب است؟","a hand pointing at a wall clock"),
 ("date","noun","/deɪt/","تاریخ","Let's fix a date.","بیا تاریخی تعیین کنیم.","a plain paper calendar page on a desk"),
 ("invitation","noun","/ˌɪnvɪˈteɪʃn/","دعوت‌نامه","I sent the invitation.","دعوت‌نامه را فرستادم.","a plain card handed from one adult to another"),
 ("everyone","pronoun","/ˈevriwʌn/","همه","Everyone is coming.","همه می‌آیند.","a group of adults in their thirties arriving at a doorway together"),
]

V[8] = [
 ("might","modal verb","/maɪt/","ممکن است","It might rain tomorrow.","ممکن است فردا باران ببارد.","heavy grey clouds over a street with people carrying umbrellas"),
 ("perhaps","adverb","/pəˈhæps/","شاید","Perhaps he's still working.","شاید هنوز مشغول کار باشد.","a lit office window at night seen from outside"),
 ("forecast","noun","/ˈfɔːkɑːst/","پیش‌بینی هوا","The forecast says snow.","پیش‌بینی می‌گوید برف می‌آید.","a plain weather display showing cloud shapes without any text"),
 ("chance","noun","/tʃɑːns/","احتمال، شانس","There's a chance of rain.","احتمال باران هست.","a partly cloudy sky with sun breaking through"),
 ("storm","noun","/stɔːm/","طوفان","A storm is coming.","طوفان در راه است.","dark clouds and bending trees before a storm"),
 ("fog","noun","/fɒɡ/","مه","There's thick fog today.","امروز مه غلیظی هست.","a road disappearing into thick morning fog"),
 ("wind","noun","/wɪnd/","باد","The wind is getting stronger.","باد دارد شدیدتر می‌شود.","tree branches bending under strong wind"),
 ("temperature","noun","/ˈtemprətʃə/","دما","The temperature is falling.","دما دارد پایین می‌آید.","a plain outdoor thermometer on a wall"),
 ("umbrella","noun","/ʌmˈbrelə/","چتر","Take an umbrella, just in case.","محض احتیاط چتر بردار.","a folded umbrella hanging by a front door"),
 ("delay","noun","/dɪˈleɪ/","تأخیر","There might be a delay.","ممکن است تأخیر باشد.","travellers in their thirties waiting on a station platform"),
 ("traffic jam","noun","/ˈtræfɪk dʒæm/","راه‌بندان","We might hit a traffic jam.","ممکن است به راه‌بندان بخوریم.","a long queue of stationary cars on a road"),
 ("expect","verb","/ɪkˈspekt/","انتظار داشتن","I expect she'll come.","انتظار دارم بیاید.","a woman in her early thirties glancing towards a door"),
 ("guess","verb","/ɡes/","حدس زدن","I guess it's fine.","حدس می‌زنم مشکلی نباشد.","a man in his early thirties shrugging with an uncertain smile"),
 ("hope","verb","/həʊp/","امیدوار بودن","I hope it doesn't rain.","امیدوارم باران نبارد.","a woman in her early thirties looking hopefully at a cloudy sky"),
 ("depend","verb","/dɪˈpend/","بستگی داشتن","It depends on the weather.","به هوا بستگی دارد.","a person standing at a doorway looking at the sky before leaving"),
 ("possible","adjective","/ˈpɒsəbl/","ممکن","Is that possible?","این ممکن است؟","two adults in their thirties discussing with open questioning gestures"),
 ("certain","adjective","/ˈsɜːtn/","قطعی","Nothing is certain.","هیچ‌چیز قطعی نیست.","a man in his early thirties with an ambivalent expression"),
 ("unlikely","adjective","/ʌnˈlaɪkli/","بعید","It's unlikely to snow.","بعید است برف بیاید.","a mild clear sky over rooftops"),
 ("just in case","phrase","/dʒʌst ɪn ˈkeɪs/","محض احتیاط","Take a coat just in case.","محض احتیاط کت بردار.","a woman in her early thirties putting a light coat over her arm"),
 ("weather","noun","/ˈweðə/","هوا","The weather might change.","هوا ممکن است عوض شود.","a sky with both sun and dark clouds"),
]

V[9] = [
 ("if","conjunction","/ɪf/","اگر","If it rains, we'll stay.","اگر باران ببارد، می‌مانیم.","a person watching rain through a window from a warm room"),
 ("stay","verb","/steɪ/","ماندن","We'll stay at home.","خانه می‌مانیم.","two adults in their thirties relaxing indoors on a rainy day"),
 ("go out","verb","/ˌɡəʊ ˈaʊt/","بیرون رفتن","If it's sunny, we'll go out.","اگر آفتابی باشد، بیرون می‌رویم.","two adults in their thirties stepping out into bright sunshine"),
 ("miss","verb","/mɪs/","از دست دادن","If we're late, we'll miss it.","اگر دیر کنیم از دستش می‌دهیم.","a train pulling away from a platform as a person arrives"),
 ("catch","verb","/kætʃ/","گرفتن، رسیدن به","We'll catch the early bus.","اتوبوس زود را می‌گیریم.","a woman in her early thirties boarding a bus just in time"),
 ("save","verb","/seɪv/","صرفه‌جویی کردن","If we walk, we'll save money.","اگر پیاده برویم پول صرفه‌جویی می‌کنیم.","two adults in their thirties walking instead of taking a taxi"),
 ("spend","verb","/spend/","خرج کردن","We'll spend less this way.","اینطوری کمتر خرج می‌کنیم.","a hand counting a few banknotes carefully"),
 ("prepare","verb","/prɪˈpeə/","آماده کردن","I'll prepare everything.","همه‌چیز را آماده می‌کنم.","a woman in her early thirties laying items out on a table"),
 ("bring back","verb","/ˌbrɪŋ ˈbæk/","برگرداندن","If you take it, bring it back.","اگر بردی، برش گردان.","a man in his early thirties returning a borrowed book"),
 ("choice","noun","/tʃɔɪs/","انتخاب","We have two choices.","دو انتخاب داریم.","two different paths branching in a park"),
 ("result","noun","/rɪˈzʌlt/","نتیجه","What will the result be?","نتیجه چه خواهد بود؟","a woman in her early thirties looking expectantly at a closed envelope"),
 ("reason","noun","/ˈriːzn/","دلیل","There's a good reason.","دلیل خوبی هست.","a man in his early thirties explaining with a calm gesture"),
 ("risk","noun","/rɪsk/","خطر، ریسک","It's not worth the risk.","ارزش ریسکش را ندارد.","a person hesitating at the edge of a wet slippery path"),
 ("safe","adjective","/seɪf/","امن","It's safer to wait.","صبر کردن امن‌تر است.","two adults in their thirties waiting under a sheltered doorway"),
 ("cheaper","adjective","/ˈtʃiːpə/","ارزان‌تر","The train is cheaper.","قطار ارزان‌تر است.","a train beside a taxi rank at a station"),
 ("faster","adjective","/ˈfɑːstə/","سریع‌تر","The bus is faster.","اتوبوس سریع‌تر است.","a bus moving in a clear lane beside slow traffic"),
 ("otherwise","adverb","/ˈʌðəwaɪz/","وگرنه","Hurry, otherwise we'll be late.","عجله کن، وگرنه دیر می‌رسیم.","a woman in her early thirties glancing anxiously at a clock while dressing"),
 ("unless","conjunction","/ənˈles/","مگر اینکه","We'll go unless it rains.","می‌رویم مگر اینکه باران ببارد.","two adults in their thirties looking at a clear sky with coats ready"),
 ("plan B","phrase","/ˌplæn ˈbiː/","برنامه جایگزین","We need a plan B.","به برنامه جایگزین نیاز داریم.","two adults in their thirties considering two options on a notepad"),
 ("decision","noun","/dɪˈsɪʒn/","تصمیم","It's your decision.","تصمیم با توست.","a man in his early thirties pointing towards another person with an open palm"),
]

V[10] = [
 ("agreement","noun","/əˈɡriːmənt/","توافق","We reached an agreement.","به توافق رسیدیم.","two adults in their thirties shaking hands over an open notebook"),
 ("agree","verb","/əˈɡriː/","موافق بودن","We all agree.","همه موافقیم.","three adults in their thirties nodding in agreement"),
 ("disagree","verb","/ˌdɪsəˈɡriː/","مخالف بودن","I disagree with that.","با آن مخالفم.","a woman in her early thirties raising a hand with a polite objecting gesture"),
 ("suggest","verb","/səˈdʒest/","پیشنهاد کردن","I suggest Friday.","جمعه را پیشنهاد می‌کنم.","a man in his early thirties pointing at a day on a plain calendar"),
 ("prefer","verb","/prɪˈfɜː/","ترجیح دادن","I prefer the morning.","صبح را ترجیح می‌دهم.","a woman in her early thirties enjoying early morning light with tea"),
 ("share","verb","/ʃeə/","تقسیم کردن","We'll share the cost.","هزینه را تقسیم می‌کنیم.","two adults in their thirties splitting banknotes evenly"),
 ("organise","verb","/ˈɔːɡənaɪz/","سازماندهی کردن","She organises everything.","همه‌چیز را سازماندهی می‌کند.","a woman in her early thirties arranging items into neat groups"),
 ("remind","verb","/rɪˈmaɪnd/","یادآوری کردن","Remind me tomorrow.","فردا یادم بینداز.","a man in his early thirties sticking a blank note on a fridge"),
 ("group","noun","/ɡruːp/","گروه","We're a small group.","گروه کوچکی هستیم.","four adults in their thirties standing together"),
 ("idea","noun","/aɪˈdɪə/","ایده","That's a great idea.","ایده عالی‌ای است.","a woman in her early thirties raising a finger with a bright expression"),
 ("option","noun","/ˈɒpʃn/","گزینه","We have three options.","سه گزینه داریم.","three separate items laid out for comparison on a table"),
 ("budget","noun","/ˈbʌdʒɪt/","بودجه","What's our budget?","بودجه‌مان چقدر است؟","a hand writing figures in a plain notebook beside a calculator"),
 ("trip","noun","/trɪp/","سفر","Let's plan a trip.","بیا سفری برنامه‌ریزی کنیم.","a small travel bag beside a folded map"),
 ("schedule","noun","/ˈʃedjuːl/","برنامه زمانی","Here's the schedule.","این هم برنامه زمانی.","a plain printed timetable pinned to a board"),
 ("detail","noun","/ˈdiːteɪl/","جزئیات","Let's check the details.","بیا جزئیات را بررسی کنیم.","two adults in their thirties studying a document closely"),
 ("responsible","adjective","/rɪˈspɒnsəbl/","مسئول","Who's responsible for food?","چه کسی مسئول غذاست؟","a man in his early thirties raising his hand to volunteer"),
 ("flexible","adjective","/ˈfleksəbl/","انعطاف‌پذیر","My schedule is flexible.","برنامه‌ام انعطاف‌پذیر است.","a woman in her early thirties adjusting entries in an open planner"),
 ("difficult","adjective","/ˈdɪfɪkəlt/","سخت","That will be difficult.","سخت خواهد بود.","a woman in her early thirties frowning slightly at a complex plan"),
 ("easy","adjective","/ˈiːzi/","آسان","This part is easy.","این قسمت آسان است.","a man in his early thirties completing a simple task with a relaxed smile"),
 ("done","adjective","/dʌn/","انجام‌شده","Everything is done.","همه‌چیز انجام شد.","two adults in their thirties closing a notebook with satisfied expressions"),
]
