# -*- coding: utf-8 -*-
"""واژگان دروس ۲۱ تا ۳۰ سطح B2 — مکاتبه رسمی، اصطلاح، هم‌آیی، اقناع."""

V = {}

V[21] = [
 ("I am writing to","phrase","/aɪ əm ˈraɪtɪŋ tuː/","بدین‌وسیله می‌نویسم که","I am writing to confirm the order.","بدین‌وسیله برای تأیید سفارش می‌نویسم.","a typed letter on a plain desk"),
 ("with reference to","phrase","/wɪð ˈrefrəns tuː/","با اشاره به","With reference to your email…","با اشاره به ایمیل شما…","a printed email beside a reply draft"),
 ("further to","phrase","/ˈfɜːðə tuː/","پیرو","Further to our call, here are the details.","پیرو تماسمان، جزئیات این است.","a phone beside an open notebook"),
 ("please find attached","phrase","/pliːz faɪnd əˈtætʃt/","به پیوست تقدیم می‌شود","Please find attached the report.","گزارش به پیوست تقدیم می‌شود.","a paper clip fastening two documents"),
 ("I would be grateful if","phrase","/aɪ wʊd bi ˈɡreɪtfl ɪf/","سپاسگزار می‌شوم اگر","I would be grateful if you could confirm.","سپاسگزار می‌شوم اگر تأیید کنید.","a polite typed request on a page"),
 ("at your earliest convenience","phrase","/ət jɔːr ˈɜːliɪst kənˈviːniəns/","در اولین فرصت","Please reply at your earliest convenience.","لطفاً در اولین فرصت پاسخ دهید.","a letter placed on top of a waiting tray"),
 ("apologise for any inconvenience","phrase","/əˈpɒlədʒaɪz fɔː ˈeni ˌɪnkənˈviːniəns/","بابت زحمت عذرخواهی می‌کنم","We apologise for any inconvenience.","بابت هر زحمتی عذرخواهی می‌کنیم.","a courteous printed notice on a counter"),
 ("yours sincerely","phrase","/jɔːz sɪnˈsɪəli/","با احترام","Yours sincerely, Ali.","با احترام، علی.","a signature line at the foot of a letter"),
 ("recipient","noun","/rɪˈsɪpiənt/","گیرنده","Check the recipient before sending.","پیش از ارسال گیرنده را بررسی کن.","an addressed envelope on a desk"),
 ("attachment","noun","/əˈtætʃmənt/","پیوست","The attachment is missing.","پیوست جا مانده.","an empty paper clip beside a single page"),
 ("enquiry","noun","/ɪnˈkwaɪəri/","استعلام","We received your enquiry.","استعلام شما را دریافت کردیم.","a letter opened on a reception desk"),
 ("acknowledge receipt","phrase","/əkˈnɒlɪdʒ rɪˈsiːt/","تأیید دریافت","Please acknowledge receipt.","لطفاً دریافت را تأیید کنید.","a stamped page in an incoming tray"),
 ("follow-up","noun","/ˈfɒləʊ ʌp/","پیگیری","This is a follow-up email.","این ایمیل پیگیری است.","a second letter placed on top of a first"),
 ("prompt","adjective","/prɒmpt/","سریع و به‌موقع","Thank you for your prompt reply.","از پاسخ سریعتان ممنونم.","a reply letter dated the same day"),
 ("courteous","adjective","/ˈkɜːtiəs/","مؤدبانه","The tone was courteous.","لحن مؤدبانه بود.","a neatly typed polite letter"),
 ("concise wording","phrase","/kənˈsaɪs ˈwɜːdɪŋ/","نگارش موجز","Use concise wording.","از نگارش موجز استفاده کن.","a short paragraph on an otherwise empty page"),
 ("subject line","phrase","/ˈsʌbdʒɪkt laɪn/","موضوع نامه","Write a clear subject line.","موضوع نامه را روشن بنویس.","a single short heading at the top of a page"),
 ("cc","verb","/ˌsiːˈsiː/","رونوشت زدن","Please cc the manager.","لطفاً به مدیر رونوشت بزن.","two identical letters addressed to different people"),
 ("forward","verb","/ˈfɔːwəd/","ارسال مجدد کردن","I forwarded it to the team.","برای تیم فرستادمش.","a letter being passed from one tray to another"),
 ("bear with me","phrase","/beə wɪð miː/","کمی صبر کنید","Please bear with me.","لطفاً کمی صبر کنید.","a person in their thirties raising a hand politely"),
]

V[22] = [
 ("the data suggests","phrase","/ðə ˈdeɪtə səˈdʒests/","داده‌ها حاکی از آن است","The data suggests a rise.","داده‌ها حاکی از افزایش است.","a chart with an upward trend line"),
 ("findings","noun","/ˈfaɪndɪŋz/","یافته‌ها","The findings were clear.","یافته‌ها روشن بود.","a bound report open at a results page"),
 ("methodology","noun","/ˌmeθəˈdɒlədʒi/","روش‌شناسی","The methodology was sound.","روش‌شناسی درست بود.","a labelled experimental setup on a bench"),
 ("sample","noun","/ˈsɑːmpl/","نمونه","The sample was too small.","نمونه خیلی کوچک بود.","a small set of items selected from a larger group"),
 ("respondent","noun","/rɪˈspɒndənt/","پاسخ‌دهنده","Most respondents agreed.","بیشتر پاسخ‌دهندگان موافق بودند.","a stack of completed questionnaires"),
 ("correlation","noun","/ˌkɒrəˈleɪʃn/","همبستگی","There's a strong correlation.","همبستگی قوی‌ای هست.","two chart lines rising together"),
 ("variable","noun","/ˈveəriəbl/","متغیر","One variable was ignored.","یک متغیر نادیده گرفته شد.","one dial among several on a control panel"),
 ("bias","noun","/ˈbaɪəs/","سوگیری","There may be some bias.","شاید کمی سوگیری باشد.","a scale tipped by an unseen weight"),
 ("limitation","noun","/ˌlɪmɪˈteɪʃn/","محدودیت","The study has limitations.","مطالعه محدودیت‌هایی دارد.","a marked boundary around a chart area"),
 ("implication for policy","phrase","/ˌɪmplɪˈkeɪʃn fɔː ˈpɒləsi/","پیامد برای سیاست‌گذاری","The implication for policy is clear.","پیامد آن برای سیاست‌گذاری روشن است.","a highlighted line at the end of a report"),
 ("summarise findings","phrase","/ˈsʌməraɪz ˈfaɪndɪŋz/","خلاصه کردن یافته‌ها","Let me summarise the findings.","بگذارید یافته‌ها را خلاصه کنم.","a one-page summary beside a thick report"),
 ("as shown in","phrase","/əz ʃəʊn ɪn/","همان‌طور که در … آمده","As shown in the table…","همان‌طور که در جدول آمده…","a hand pointing at a printed table"),
 ("based on","phrase","/beɪst ɒn/","بر پایه","Based on the data, we recommend waiting.","بر پایه داده‌ها توصیه به صبر می‌کنیم.","a report resting on a stack of charts"),
 ("in comparison with","phrase","/ɪn kəmˈpærɪsn wɪð/","در مقایسه با","In comparison with last year, it improved.","در مقایسه با پارسال بهتر شد.","two charts from different years side by side"),
 ("substantial","adjective","/səbˈstænʃl/","قابل توجه","There was a substantial rise.","افزایش قابل توجهی بود.","a bar chart with one very tall column"),
 ("marginal","adjective","/ˈmɑːdʒɪnl/","جزئی","The change was marginal.","تغییر جزئی بود.","two bars with a barely visible difference"),
 ("preliminary","adjective","/prɪˈlɪmɪnəri/","مقدماتی","These are preliminary results.","این‌ها نتایج مقدماتی‌اند.","a draft page marked with early figures"),
 ("conclusive","adjective","/kənˈkluːsɪv/","قطعی","The evidence isn't conclusive.","شواهد قطعی نیست.","an unfinished chain of connected boxes"),
 ("in summary","phrase","/ɪn ˈsʌməri/","خلاصه اینکه","In summary, the trend is upward.","خلاصه اینکه روند صعودی است.","a final short paragraph on a report page"),
 ("subject to change","phrase","/ˈsʌbdʒɪkt tə tʃeɪndʒ/","قابل تغییر","Figures are subject to change.","ارقام قابل تغییرند.","a page with a pencilled amendment"),
]

V[23] = [
 ("register","noun","/ˈredʒɪstə/","ثبت زبانی، لحن","Match the register to the reader.","لحن را با خواننده هماهنگ کن.","the same message written in two different styles"),
 ("formality","noun","/fɔːˈmæləti/","رسمیت","The level of formality matters.","میزان رسمیت مهم است.","a formal letter beside a casual note"),
 ("colloquial","adjective","/kəˈləʊkwiəl/","محاوره‌ای","That word is too colloquial.","آن واژه زیادی محاوره‌ای است.","a casual handwritten note"),
 ("neutral","adjective","/ˈnjuːtrəl/","خنثی","Keep the tone neutral.","لحن را خنثی نگه دار.","a plainly worded typed line"),
 ("stiff","adjective","/stɪf/","خشک","The email sounds stiff.","ایمیل خشک به‌نظر می‌رسد.","a rigidly formatted letter"),
 ("friendly","adjective","/ˈfrendli/","دوستانه","A friendly tone works better here.","اینجا لحن دوستانه بهتر جواب می‌دهد.","a short warm note on a desk"),
 ("appropriate","adjective","/əˈprəʊpriət/","مناسب","That's not appropriate here.","اینجا مناسب نیست.","a note set aside from a formal folder"),
 ("soften","verb","/ˈsɒfn/","نرم کردن","Let's soften the wording.","بیا نگارش را نرم کنیم.","a crossed-out blunt line replaced by a gentler one"),
 ("rephrase","verb","/ˌriːˈfreɪz/","بازنویسی کردن","Could you rephrase that?","می‌شود بازنویسی‌اش کنی؟","a line rewritten beneath its original"),
 ("adapt tone","phrase","/əˈdæpt təʊn/","تنظیم لحن","Adapt your tone to the audience.","لحنت را با مخاطب تنظیم کن.","two versions of one message side by side"),
 ("contraction","noun","/kənˈtrækʃn/","کوتاه‌نویسی","Avoid contractions in formal writing.","در نوشتار رسمی از کوتاه‌نویسی پرهیز کن.","a page with shortened forms marked"),
 ("slang","noun","/slæŋ/","زبان عامیانه","Don't use slang at work.","سر کار از زبان عامیانه استفاده نکن.","a casual note beside a formal one"),
 ("jargon","noun","/ˈdʒɑːɡən/","اصطلاحات صنفی","Too much jargon confuses readers.","اصطلاحات صنفی زیاد خواننده را گیج می‌کند.","a page dense with technical terms"),
 ("plain English","phrase","/pleɪn ˈɪŋɡlɪʃ/","انگلیسی ساده","Write in plain English.","به انگلیسی ساده بنویس.","a clear short paragraph on a page"),
 ("audience awareness","phrase","/ˈɔːdiəns əˈweənəs/","شناخت مخاطب","Audience awareness is key.","شناخت مخاطب کلیدی است.","a writer in their thirties glancing at a reader's profile note"),
 ("come across as rude","phrase","/kʌm əˈkrɒs əz ruːd/","بی‌ادب به‌نظر رسیدن","It might come across as rude.","ممکن است بی‌ادب به‌نظر برسد.","a blunt short message on a screen"),
 ("hedge","verb","/hedʒ/","محتاطانه گفتن","He hedged his answer.","پاسخش را محتاطانه داد.","a carefully qualified line on a page"),
 ("direct","adjective","/dəˈrekt/","مستقیم","English can be less direct than Persian.","انگلیسی می‌تواند از فارسی غیرمستقیم‌تر باشد.","two messages, one blunt and one softened"),
 ("polite formula","phrase","/pəˈlaɪt ˈfɔːmjələ/","عبارت تعارفی","Use a polite formula to open.","برای شروع از عبارت تعارفی استفاده کن.","the opening line of a courteous letter"),
 ("strike the right note","phrase","/straɪk ðə raɪt nəʊt/","لحن درست را گرفتن","The email strikes the right note.","ایمیل لحن درستی دارد.","a well-balanced short letter on a desk"),
]

V[24] = [
 ("a piece of cake","phrase","/ə piːs əv keɪk/","خیلی آسان","The test was a piece of cake.","آزمون خیلی آسان بود.","a person in their thirties finishing a task effortlessly"),
 ("once in a blue moon","phrase","/wʌns ɪn ə bluː muːn/","خیلی به‌ندرت","We meet once in a blue moon.","خیلی به‌ندرت همدیگر را می‌بینیم.","two adults in their thirties greeting warmly after a long gap"),
 ("under the weather","phrase","/ˈʌndə ðə ˈweðə/","کسالت داشتن","I'm a bit under the weather.","کمی کسالت دارم.","a person in their thirties resting with a blanket and tea"),
 ("hit the roof","phrase","/hɪt ðə ruːf/","از کوره در رفتن","He hit the roof.","از کوره در رفت.","a man in his early thirties reacting sharply at a desk"),
 ("in the same boat","phrase","/ɪn ðə seɪm bəʊt/","هم‌سرنوشت","We're all in the same boat.","همه هم‌سرنوشتیم.","several adults in their thirties waiting together"),
 ("cost an arm and a leg","phrase","/kɒst ən ɑːm ənd ə leɡ/","خیلی گران بودن","It cost an arm and a leg.","خیلی گران تمام شد.","a large price tag beside a modest item"),
 ("break the ice","phrase","/breɪk ði aɪs/","یخ را شکستن","A joke broke the ice.","شوخی یخ را شکست.","a group of adults in their thirties beginning to laugh together"),
 ("call it a day","phrase","/kɔːl ɪt ə deɪ/","کار را تمام کردن","Let's call it a day.","بیا کار را تمام کنیم.","a workshop with tools being put away at dusk"),
 ("get the hang of","phrase","/ɡet ðə hæŋ əv/","راه افتادن در","I got the hang of it quickly.","سریع راه افتادم.","a person in their thirties using a new tool confidently"),
 ("keep an eye on","phrase","/kiːp ən aɪ ɒn/","حواس داشتن به","Keep an eye on the time.","حواست به وقت باشد.","a clock kept in view beside a task"),
 ("out of the blue","phrase","/aʊt əv ðə bluː/","یکهو","She called out of the blue.","یکهو زنگ زد.","a phone ringing on an otherwise quiet desk"),
 ("on the same page","phrase","/ɒn ðə seɪm peɪdʒ/","هم‌نظر","Are we on the same page?","هم‌نظریم؟","two adults in their thirties reading the same document"),
 ("go the extra mile","phrase","/ɡəʊ ði ˈekstrə maɪl/","سنگ تمام گذاشتن","She always goes the extra mile.","همیشه سنگ تمام می‌گذارد.","a woman in her early thirties finishing work after others have left"),
 ("cut corners","phrase","/kʌt ˈkɔːnəz/","سرهم‌بندی کردن","Don't cut corners.","سرهم‌بندی نکن.","an unfinished join on a piece of work"),
 ("play it by ear","phrase","/pleɪ ɪt baɪ ɪə/","بسته به شرایط تصمیم گرفتن","Let's play it by ear.","بسته به شرایط تصمیم می‌گیریم.","an open plan with no fixed times marked"),
 ("touch base","phrase","/tʌtʃ beɪs/","تماس گرفتن برای هماهنگی","Let's touch base on Monday.","دوشنبه هماهنگ می‌کنیم.","two adults in their thirties on a brief call"),
 ("in a nutshell","phrase","/ɪn ə ˈnʌtʃel/","خلاصه بگویم","In a nutshell, it worked.","خلاصه بگویم، جواب داد.","a single short line summarising a full page"),
 ("bite off more than you can chew","phrase","/baɪt ɒf mɔː ðən juː kən tʃuː/","لقمه بزرگ‌تر از دهان برداشتن","I bit off more than I could chew.","لقمه بزرگ‌تر از دهانم برداشتم.","a desk overloaded with too many folders"),
 ("back to square one","phrase","/bæk tə skweə wʌn/","برگشتن به نقطه اول","We're back to square one.","به نقطه اول برگشتیم.","a whiteboard wiped clean"),
 ("the last straw","phrase","/ðə lɑːst strɔː/","کاسه صبر لبریز","That was the last straw.","کاسه صبرم لبریز شد.","one extra folder toppling a full stack"),
]

V[25] = [
 ("make a decision","phrase","/meɪk ə dɪˈsɪʒn/","تصمیم گرفتن","We made a decision quickly.","سریع تصمیم گرفتیم.","a person in their thirties signing a page decisively"),
 ("do research","phrase","/duː rɪˈsɜːtʃ/","تحقیق کردن","We did research first.","اول تحقیق کردیم.","a desk covered with reference material"),
 ("make progress","phrase","/meɪk ˈprəʊɡres/","پیشرفت کردن","We're making progress.","داریم پیشرفت می‌کنیم.","a chart line moving steadily upward"),
 ("do business","phrase","/duː ˈbɪznəs/","کسب‌وکار کردن","We do business with them.","با آن‌ها کار می‌کنیم.","two adults in their thirties shaking hands over documents"),
 ("make an effort","phrase","/meɪk ən ˈefət/","تلاش کردن","She made a real effort.","واقعاً تلاش کرد.","a woman in her early thirties persisting at a hard task"),
 ("do a favour","phrase","/duː ə ˈfeɪvə/","لطف کردن","Could you do me a favour?","می‌شود لطفی بکنی؟","one adult in their thirties helping another with a box"),
 ("take responsibility","phrase","/teɪk rɪˌspɒnsəˈbɪləti/","مسئولیت پذیرفتن","He took responsibility.","مسئولیت را پذیرفت.","a man in his early thirties signing calmly"),
 ("take a risk","phrase","/teɪk ə rɪsk/","ریسک کردن","We took a calculated risk.","ریسک حساب‌شده‌ای کردیم.","a person in their thirties stepping onto a narrow bridge"),
 ("pay attention","phrase","/peɪ əˈtenʃn/","توجه کردن","Pay attention to the details.","به جزئیات توجه کن.","a magnified view of a small component"),
 ("meet a deadline","phrase","/miːt ə ˈdedlaɪn/","به مهلت رسیدن","We met the deadline.","به مهلت رسیدیم.","a finished task beside a circled calendar day"),
 ("reach an agreement","phrase","/riːtʃ ən əˈɡriːmənt/","به توافق رسیدن","They reached an agreement.","به توافق رسیدند.","two adults in their thirties signing the same page"),
 ("raise a concern","phrase","/reɪz ə kənˈsɜːn/","نگرانی را مطرح کردن","She raised a concern.","نگرانی‌ای مطرح کرد.","a woman in her early thirties speaking at a meeting"),
 ("draw a conclusion","phrase","/drɔː ə kənˈkluːʒn/","نتیجه گرفتن","Let's not draw a conclusion yet.","هنوز نتیجه نگیریم.","an unfinished diagram on a whiteboard"),
 ("strong argument","phrase","/strɒŋ ˈɑːɡjumənt/","استدلال محکم","That's a strong argument.","استدلال محکمی است.","a well-structured page of points"),
 ("heavy traffic","phrase","/ˈhevi ˈtræfɪk/","ترافیک سنگین","We hit heavy traffic.","به ترافیک سنگین خوردیم.","a long line of stationary cars"),
 ("deeply concerned","phrase","/ˈdiːpli kənˈsɜːnd/","عمیقاً نگران","We're deeply concerned.","عمیقاً نگرانیم.","two adults in their thirties with serious expressions"),
 ("highly likely","phrase","/ˈhaɪli ˈlaɪkli/","بسیار محتمل","It's highly likely.","بسیار محتمل است.","a marker near the top of a probability scale"),
 ("widely accepted","phrase","/ˈwaɪdli əkˈseptɪd/","به‌طور گسترده پذیرفته","It's widely accepted now.","حالا به‌طور گسترده پذیرفته است.","many identical approved documents"),
 ("collocation","noun","/ˌkɒləˈkeɪʃn/","هم‌آیی واژگانی","Collocations sound natural.","هم‌آیی‌ها طبیعی به‌نظر می‌رسند.","two word cards fitting together like puzzle pieces"),
 ("sound wrong","phrase","/saʊnd rɒŋ/","نادرست به گوش رسیدن","It sounds wrong to a native speaker.","برای یک بومی نادرست به گوش می‌رسد.","a person in their thirties frowning at a written line"),
]

V[26] = [
 ("get by","phrase","/ɡet baɪ/","از پس گذران برآمدن","We get by on a small budget.","با بودجه کم می‌گذرانیم.","a modest but tidy kitchen table"),
 ("get through","phrase","/ɡet θruː/","به پایان رساندن","I got through the whole report.","تمام گزارش را به پایان رساندم.","a finished thick document on a desk"),
 ("get over","phrase","/ɡet ˈəʊvə/","کنار آمدن با","She got over the setback.","با آن عقبگرد کنار آمد.","a woman in her early thirties smiling again after difficulty"),
 ("take on","phrase","/teɪk ɒn/","بر عهده گرفتن","He took on the project.","پروژه را بر عهده گرفت.","a man in his early thirties accepting a thick folder"),
 ("take over","phrase","/teɪk ˈəʊvə/","تحویل گرفتن مسئولیت","She took over the team.","تیم را تحویل گرفت.","a woman in her early thirties stepping to the front of a group"),
 ("take up","phrase","/teɪk ʌp/","شروع کردن (سرگرمی)","I took up running last year.","پارسال دویدن را شروع کردم.","running shoes beside an open door"),
 ("put off","phrase","/pʊt ɒf/","به تعویق انداختن","We put off the meeting.","جلسه را به تعویق انداختیم.","a note moved to a later calendar square"),
 ("put up with","phrase","/pʊt ʌp wɪð/","تحمل کردن","I can't put up with it.","تحملش نمی‌کنم.","a person in their thirties covering their ears near noise"),
 ("put forward","phrase","/pʊt ˈfɔːwəd/","مطرح کردن","She put forward a proposal.","پیشنهادی مطرح کرد.","a document slid across a meeting table"),
 ("bring about","phrase","/brɪŋ əˈbaʊt/","به وجود آوردن","The change brought about problems.","تغییر مشکلاتی به وجود آورد.","a switch flipped with visible consequences"),
 ("bring up","phrase","/brɪŋ ʌp/","پیش کشیدن","He brought up the cost.","هزینه را پیش کشید.","a man in his early thirties speaking at a meeting"),
 ("carry on","phrase","/ˈkæri ɒn/","ادامه دادن","Carry on without me.","بدون من ادامه بدهید.","a team in their thirties continuing work"),
 ("run into","phrase","/rʌn ˈɪntuː/","برخوردن به","We ran into a problem.","به مشکلی برخوردیم.","a blocked path on a worksite"),
 ("come up with","phrase","/kʌm ʌp wɪð/","ارائه دادن (ایده)","She came up with a solution.","راه‌حلی ارائه داد.","a woman in her early thirties sketching an idea"),
 ("look into","phrase","/lʊk ˈɪntuː/","بررسی کردن","We'll look into it.","بررسی‌اش می‌کنیم.","a person in their thirties examining a report closely"),
 ("work out","phrase","/wɜːk aʊt/","حل شدن، محاسبه کردن","It worked out well.","خوب از آب درآمد.","a completed calculation on a notepad"),
 ("set out","phrase","/set aʊt/","شرح دادن","The report sets out three options.","گزارش سه گزینه را شرح می‌دهد.","a page with three numbered sections"),
 ("stand out","phrase","/stænd aʊt/","برجسته بودن","Her work stands out.","کارش برجسته است.","one item clearly distinct among similar ones"),
 ("fall behind","phrase","/fɔːl bɪˈhaɪnd/","عقب افتادن","We fell behind schedule.","از برنامه عقب افتادیم.","a partly finished project beside a marked calendar"),
 ("catch up on","phrase","/kætʃ ʌp ɒn/","جبران عقب‌ماندگی","I need to catch up on work.","باید عقب‌ماندگی کارم را جبران کنم.","a person in their thirties working through a backlog"),
]

V[27] = [
 ("sound natural","phrase","/saʊnd ˈnætʃrəl/","طبیعی به گوش رسیدن","It sounds natural now.","حالا طبیعی به گوش می‌رسد.","two adults in their thirties in relaxed conversation"),
 ("word choice","phrase","/wɜːd tʃɔɪs/","انتخاب واژه","Word choice makes a difference.","انتخاب واژه فرق می‌کند.","two similar word cards, one chosen"),
 ("fixed expression","phrase","/fɪkst ɪkˈspreʃn/","عبارت ثابت","It's a fixed expression.","عبارت ثابتی است.","two word cards joined and sealed together"),
 ("literal translation","phrase","/ˈlɪtərəl trænzˈleɪʃn/","ترجمه لفظ‌به‌لفظ","Avoid literal translation.","از ترجمه لفظ‌به‌لفظ پرهیز کن.","a Persian line and an awkward English line side by side"),
 ("idiomatic","adjective","/ˌɪdiəˈmætɪk/","اصطلاحی","That's the idiomatic way.","شیوه اصطلاحی همین است.","a natural-sounding line marked with a tick"),
 ("awkward","adjective","/ˈɔːkwəd/","ناجور","The sentence sounds awkward.","جمله ناجور به‌نظر می‌رسد.","a line marked with a question mark"),
 ("fluent speech","phrase","/ˈfluːənt spiːtʃ/","گفتار روان","Fluent speech takes practice.","گفتار روان تمرین می‌خواهد.","a woman in her early thirties speaking easily to a group"),
 ("filler word","phrase","/ˈfɪlə wɜːd/","کلمه پرکننده","Too many filler words distract.","کلمات پرکننده زیاد حواس را پرت می‌کند.","a transcript with repeated short words marked"),
 ("intonation","noun","/ˌɪntəˈneɪʃn/","آهنگ کلام","Intonation carries meaning.","آهنگ کلام معنا را می‌رساند.","a rising and falling line drawn over a sentence"),
 ("stress pattern","phrase","/stres ˈpætn/","الگوی تکیه","Learn the stress pattern.","الگوی تکیه را یاد بگیر.","a word with one syllable marked bold"),
 ("chunk","noun","/tʃʌŋk/","قطعه زبانی","Learn language in chunks.","زبان را قطعه‌قطعه یاد بگیر.","several word cards grouped into blocks"),
 ("memorise","verb","/ˈmeməraɪz/","حفظ کردن","Memorise whole phrases.","عبارت‌های کامل را حفظ کن.","a notebook with repeated written lines"),
 ("imitate","verb","/ˈɪmɪteɪt/","تقلید کردن","Imitate the rhythm.","ریتم را تقلید کن.","a person in their thirties repeating along with headphones"),
 ("shadow","verb","/ˈʃædəʊ/","تکرار همزمان","Shadowing improves rhythm.","تکرار همزمان ریتم را بهتر می‌کند.","a person in their thirties speaking along with an audio track"),
 ("register shift","phrase","/ˈredʒɪstə ʃɪft/","تغییر لحن","Notice the register shift.","به تغییر لحن دقت کن.","two versions of a sentence side by side"),
 ("native-like","adjective","/ˈneɪtɪv laɪk/","نزدیک به بومی","His accent is native-like.","لهجه‌اش نزدیک به بومی است.","two adults in their thirties conversing without hesitation"),
 ("overuse","verb","/ˌəʊvəˈjuːz/","زیاده‌روی در کاربرد","Don't overuse idioms.","در کاربرد اصطلاح زیاده‌روی نکن.","a page crowded with highlighted phrases"),
 ("in context","phrase","/ɪn ˈkɒntekst/","در بافت","Learn words in context.","واژه‌ها را در بافت یاد بگیر.","a word card placed inside a full sentence"),
 ("get it right","phrase","/ɡet ɪt raɪt/","درست از آب درآوردن","It takes time to get it right.","درست از آب درآوردنش زمان می‌برد.","a corrected line finally marked with a tick"),
 ("pick up","phrase","/pɪk ʌp/","ناخودآگاه یاد گرفتن","I picked it up from films.","از فیلم‌ها یادش گرفتم.","a person in their thirties watching a screen with subtitles"),
]

V[28] = [
 ("build a case","phrase","/bɪld ə keɪs/","استدلال ساختن","Let's build a case for it.","بیا برایش استدلال بسازیم.","several documents assembled into one folder"),
 ("make a case for","phrase","/meɪk ə keɪs fɔː/","استدلال آوردن برای","She made a case for delay.","برای تأخیر استدلال آورد.","a woman in her early thirties presenting points on a chart"),
 ("persuade","verb","/pəˈsweɪd/","متقاعد کردن","He persuaded the board.","هیئت‌مدیره را متقاعد کرد.","a group of adults in their thirties nodding together"),
 ("convincing evidence","phrase","/kənˈvɪnsɪŋ ˈevɪdəns/","شواهد قانع‌کننده","We need convincing evidence.","به شواهد قانع‌کننده نیاز داریم.","a clear chart placed on a meeting table"),
 ("compelling","adjective","/kəmˈpelɪŋ/","متقاعدکننده","It's a compelling argument.","استدلال متقاعدکننده‌ای است.","a well-structured presentation slide"),
 ("weak point","phrase","/wiːk pɔɪnt/","نقطه ضعف","Every case has a weak point.","هر استدلالی نقطه ضعفی دارد.","a single crack in a solid structure"),
 ("strengthen","verb","/ˈstreŋθn/","تقویت کردن","We should strengthen the argument.","باید استدلال را تقویت کنیم.","an extra support added to a structure"),
 ("undermine","verb","/ˌʌndəˈmaɪn/","تضعیف کردن","That undermines your point.","این نکته‌ات را تضعیف می‌کند.","a support removed from beneath a structure"),
 ("appeal to","phrase","/əˈpiːl tuː/","متوسل شدن به","He appealed to common sense.","به عقل سلیم متوسل شد.","a man in his early thirties gesturing openly to listeners"),
 ("back up","phrase","/bæk ʌp/","پشتیبانی کردن از","Back it up with data.","با داده پشتیبانی‌اش کن.","a claim placed beside a supporting chart"),
 ("supporting evidence","phrase","/səˈpɔːtɪŋ ˈevɪdəns/","شواهد پشتیبان","Where's the supporting evidence?","شواهد پشتیبان کجاست؟","a folder of documents beside a single claim"),
 ("counter","verb","/ˈkaʊntə/","پاسخ دادن به (استدلال)","She countered the objection.","به اعتراض پاسخ داد.","a woman in her early thirties responding across a table"),
 ("stakeholder","noun","/ˈsteɪkhəʊldə/","ذی‌نفع","We consulted all stakeholders.","با همه ذی‌نفعان مشورت کردیم.","several adults in their thirties around a shared plan"),
 ("proposal","noun","/prəˈpəʊzl/","پیشنهاد رسمی","The proposal was accepted.","پیشنهاد پذیرفته شد.","a bound document on a meeting table"),
 ("benefit from","phrase","/ˈbenɪfɪt frɒm/","سود بردن از","Everyone benefits from it.","همه از آن سود می‌برند.","several people receiving the same improvement"),
 ("in favour of","phrase","/ɪn ˈfeɪvər əv/","به نفعِ","The vote was in favour of change.","رأی به نفع تغییر بود.","most hands raised in a room"),
 ("bear the cost","phrase","/beə ðə kɒst/","هزینه را متحمل شدن","Who bears the cost?","چه کسی هزینه را متحمل می‌شود؟","a receipt placed in front of one person"),
 ("long-term","adjective","/ˌlɒŋˈtɜːm/","بلندمدت","Think about the long-term benefit.","به فایده بلندمدت فکر کن.","a chart extending far to the right"),
 ("short-term","adjective","/ˌʃɔːtˈtɜːm/","کوتاه‌مدت","It's a short-term fix.","راه‌حل کوتاه‌مدتی است.","a temporary patch on a broken part"),
 ("win over","phrase","/wɪn ˈəʊvə/","جلب کردن","She won over the sceptics.","تردیدکنندگان را جلب کرد.","a group of adults in their thirties shifting from doubt to agreement"),
]

V[29] = [
 ("objection","noun","/əbˈdʒekʃn/","اعتراض","There was one objection.","یک اعتراض بود.","one raised hand in a seated group"),
 ("anticipate an objection","phrase","/ænˈtɪsɪpeɪt ən əbˈdʒekʃn/","پیش‌بینی اعتراض","Anticipate the obvious objection.","اعتراض بدیهی را پیش‌بینی کن.","a prepared answer written beside a question"),
 ("admittedly","adverb","/ədˈmɪtɪdli/","باید اعتراف کرد","Admittedly, it's expensive.","باید اعتراف کرد که گران است.","a man in his early thirties conceding a point openly"),
 ("granted","adverb","/ˈɡrɑːntɪd/","قبول","Granted, it takes time.","قبول، وقت می‌برد.","a clock beside an accepted plan"),
 ("nonetheless","adverb","/ˌnʌnðəˈles/","با این همه","Nonetheless, it's worth doing.","با این همه ارزش انجام دادن دارد.","a project continuing past an obstacle"),
 ("that said","phrase","/ðæt sed/","با این حال","That said, there's a risk.","با این حال ریسکی هست.","a warning note added to an approved plan"),
 ("critics argue","phrase","/ˈkrɪtɪks ˈɑːɡjuː/","منتقدان می‌گویند","Critics argue it's too slow.","منتقدان می‌گویند کند است.","two adults in their thirties raising concerns at a table"),
 ("some may say","phrase","/sʌm meɪ seɪ/","برخی شاید بگویند","Some may say it's risky.","برخی شاید بگویند پرخطر است.","a small group with doubtful expressions"),
 ("address a concern","phrase","/əˈdres ə kənˈsɜːn/","به نگرانی پرداختن","Let me address that concern.","بگذارید به آن نگرانی بپردازم.","a presenter in their thirties responding to a raised hand"),
 ("valid concern","phrase","/ˈvælɪd kənˈsɜːn/","نگرانی بجا","That's a valid concern.","نگرانی بجایی است.","a marked note taken seriously on a page"),
 ("overcome","verb","/ˌəʊvəˈkʌm/","بر … غلبه کردن","We overcame the objection.","بر اعتراض غلبه کردیم.","a barrier removed from a path"),
 ("concession","noun","/kənˈseʃn/","امتیاز دادن","We made one concession.","یک امتیاز دادیم.","one clause amended in a contract"),
 ("rebuttal","noun","/rɪˈbʌtl/","پاسخ رد","His rebuttal was strong.","پاسخ ردش محکم بود.","a second document placed firmly beside a first"),
 ("defend a position","phrase","/dɪˈfend ə pəˈzɪʃn/","دفاع از موضع","She defended her position well.","خوب از موضعش دفاع کرد.","a woman in her early thirties standing firm at a meeting"),
 ("give ground","phrase","/ɡɪv ɡraʊnd/","عقب نشستن","We gave some ground.","کمی عقب نشستیم.","a marker moved slightly toward the other side"),
 ("common objection","phrase","/ˈkɒmən əbˈdʒekʃn/","اعتراض رایج","That's a common objection.","اعتراض رایجی است.","the same note repeated on several pages"),
 ("worth considering","phrase","/wɜːθ kənˈsɪdərɪŋ/","ارزش بررسی دارد","It's worth considering.","ارزش بررسی دارد.","a document moved into a review pile"),
 ("reassure","verb","/ˌriːəˈʃʊə/","اطمینان دادن","Let me reassure you.","بگذارید به شما اطمینان بدهم.","a man in his early thirties speaking calmly to a worried colleague"),
 ("clarify a misunderstanding","phrase","/ˈklærɪfaɪ ə ˌmɪsʌndəˈstændɪŋ/","رفع سوءتفاهم","Let's clarify the misunderstanding.","بیا سوءتفاهم را رفع کنیم.","two adults in their thirties reaching agreement over a page"),
 ("bring people on board","phrase","/brɪŋ ˈpiːpl ɒn bɔːd/","همراه کردن","We brought everyone on board.","همه را همراه کردیم.","a full team of adults in their thirties gathered around one plan"),
]

V[30] = [
 ("upper intermediate","phrase","/ˈʌpər ˌɪntəˈmiːdiət/","متوسط بالا","You've finished upper intermediate.","سطح متوسط بالا را تمام کرده‌ای.","a high step on a long rising staircase"),
 ("proficiency","noun","/prəˈfɪʃnsi/","تسلط","My proficiency has grown.","تسلطم بیشتر شده.","a woman in her early thirties speaking confidently to a group"),
 ("command of English","phrase","/kəˈmɑːnd əv ˈɪŋɡlɪʃ/","تسلط بر انگلیسی","She has a good command of English.","تسلط خوبی بر انگلیسی دارد.","a person in their thirties chairing a meeting comfortably"),
 ("nuanced meaning","phrase","/ˈnjuːɑːnst ˈmiːnɪŋ/","معنای ظریف","I catch nuanced meaning now.","حالا معنای ظریف را می‌گیرم.","two nearly identical sentences with one word changed"),
 ("abstract topic","phrase","/ˈæbstrækt ˈtɒpɪk/","موضوع انتزاعی","I can discuss abstract topics.","می‌توانم درباره موضوعات انتزاعی بحث کنم.","two adults in their thirties in a long thoughtful discussion"),
 ("hold your own","phrase","/həʊld jɔːr əʊn/","از پس خود برآمدن","I can hold my own in a debate.","در بحث از پس خودم برمی‌آیم.","a person in their thirties speaking confidently among others"),
 ("think in English","phrase","/θɪŋk ɪn ˈɪŋɡlɪʃ/","به انگلیسی فکر کردن","I've started to think in English.","شروع کرده‌ام به انگلیسی فکر کنم.","a person in their thirties writing without pausing to translate"),
 ("translate in your head","phrase","/trænzˈleɪt ɪn jɔː hed/","در ذهن ترجمه کردن","I no longer translate in my head.","دیگر در ذهنم ترجمه نمی‌کنم.","a person in their thirties speaking without hesitation"),
 ("plateau","noun","/ˈplætəʊ/","فلات پیشرفت","Everyone hits a plateau.","هرکسی به فلات می‌رسد.","a chart line running flat for a stretch"),
 ("push through","phrase","/pʊʃ θruː/","از سد گذشتن","Push through the plateau.","از فلات بگذر.","a walker in their thirties continuing past a flat stretch"),
 ("consolidation","noun","/kənˌsɒlɪˈdeɪʃn/","تثبیت","Review is consolidation.","مرور همان تثبیت است.","loose pages gathered into one bound folder"),
 ("active vocabulary","phrase","/ˈæktɪv vəˈkæbjələri/","واژگان فعال","Grow your active vocabulary.","واژگان فعالت را زیاد کن.","a well-used notebook with many marked entries"),
 ("passive vocabulary","phrase","/ˈpæsɪv vəˈkæbjələri/","واژگان منفعل","Passive vocabulary is larger.","واژگان منفعل بزرگ‌تر است.","a thick dictionary beside a slim notebook"),
 ("advanced level","phrase","/ədˈvɑːnst ˈlevl/","سطح پیشرفته","C1 is the advanced level.","C1 سطح پیشرفته است.","a higher landing on a staircase"),
 ("realistic expectation","phrase","/ˌrɪəˈlɪstɪk ˌekspekˈteɪʃn/","انتظار واقع‌بینانه","Keep expectations realistic.","انتظارت را واقع‌بینانه نگه دار.","a modest flag placed partway along a path"),
 ("daily exposure","phrase","/ˈdeɪli ɪkˈspəʊʒə/","مواجهه روزانه","Daily exposure matters most.","مواجهه روزانه از همه مهم‌تر است.","a calendar with every day ticked"),
 ("stretch yourself","phrase","/stretʃ jɔːˈself/","خود را به چالش کشیدن","Stretch yourself a little.","کمی خودت را به چالش بکش.","a person in their thirties reaching for a higher shelf"),
 ("measurable","adjective","/ˈmeʒərəbl/","قابل اندازه‌گیری","Set measurable goals.","هدف‌های قابل اندازه‌گیری بگذار.","a marked scale beside a simple chart"),
 ("sustainable","adjective","/səˈsteɪnəbl/","پایدار","Make it a sustainable habit.","عادتی پایدار بسازش.","a plant growing steadily in good light"),
 ("congratulations","noun","/kənˌɡrætʃuˈleɪʃnz/","تبریک","Congratulations on finishing.","تمام کردنش را تبریک می‌گویم.","colleagues in their thirties applauding one person"),
]
