# -*- coding: utf-8 -*-
"""
واژگان دروس ۱۱ تا ۲۰ سطح A2 — مقایسه، توصیف دقیق‌تر، و حال کامل.

بلوک ۱۶ تا ۱۸ سخت‌ترین بخش A2 است (حال کامل و مجهول). واژه‌های این
دروس عمداً ساده‌تر انتخاب شده‌اند تا بار گرامری و بار واژگانی همزمان
روی کاربر نیفتد.
"""

V = {}

V[11] = [
 ("expensive","adjective","/ɪkˈspensɪv/","گران","This one is more expensive.","این یکی گران‌تر است.","two similar bags side by side, one visibly finer than the other"),
 ("comfortable","adjective","/ˈkʌmftəbl/","راحت","These shoes are more comfortable.","این کفش‌ها راحت‌ترند.","a woman in her early thirties walking easily in soft flat shoes"),
 ("popular","adjective","/ˈpɒpjələ/","محبوب","This model is more popular.","این مدل محبوب‌تر است.","a busy shop counter with one product being picked up repeatedly"),
 ("useful","adjective","/ˈjuːsfl/","مفید","A map is more useful here.","اینجا نقشه مفیدتر است.","a folded paper map open on a table beside a phone"),
 ("modern","adjective","/ˈmɒdn/","امروزی","The new one is more modern.","نو‌تره امروزی‌تر است.","a sleek modern kitchen appliance beside an older one"),
 ("crowded","adjective","/ˈkraʊdɪd/","شلوغ","The market is more crowded.","بازار شلوغ‌تر است.","a busy indoor market with many adult shoppers"),
 ("receipt","noun","/rɪˈsiːt/","رسید","Keep the receipt, please.","لطفاً رسید را نگه دار.","a small printed slip lying on a shop counter"),
 ("better","adjective","/ˈbetə/","بهتر","This quality is better.","این کیفیت بهتر است.","two fabric samples side by side, one clearly finer"),
 ("worse","adjective","/wɜːs/","بدتر","The weather is worse today.","امروز هوا بدتر است.","a dark rainy street under heavy clouds"),
 ("cheap","adjective","/tʃiːp/","ارزان","The cheaper one is fine.","ارزان‌تره هم خوب است.","a modest simple product on a shop shelf"),
 ("quality","noun","/ˈkwɒləti/","کیفیت","The quality is very good.","کیفیتش خیلی خوب است.","a hand feeling the texture of a well-made fabric"),
 ("price","noun","/praɪs/","قیمت","Compare the prices first.","اول قیمت‌ها را مقایسه کن.","two blank price tags hanging side by side"),
 ("brand","noun","/brænd/","برند","Which brand do you prefer?","کدام برند را ترجیح می‌دهی؟","two unlabelled product boxes side by side on a counter"),
 ("discount","noun","/ˈdɪskaʊnt/","تخفیف","There's a discount today.","امروز تخفیف هست.","a shop window with a large blank sale card"),
 ("size","noun","/saɪz/","اندازه","Do you have a bigger size?","اندازه بزرگ‌تر دارید؟","a shop assistant in their thirties holding up two garments of different sizes"),
 ("choose","verb","/tʃuːz/","انتخاب کردن","It's hard to choose.","انتخاب سخت است.","a woman in her early thirties looking between two similar items"),
 ("compare","verb","/kəmˈpeə/","مقایسه کردن","Let's compare them.","بیا مقایسه‌شان کنیم.","two adults in their thirties holding one item each side by side"),
 ("cost","verb","/kɒst/","هزینه داشتن","How much does it cost?","چقدر هزینه دارد؟","a customer in their thirties pointing questioningly at an item"),
 ("worth","adjective","/wɜːθ/","ارزشش را داشتن","It's worth the money.","ارزش پولش را دارد.","a man in his early thirties nodding approvingly at a purchase"),
 ("value","noun","/ˈvæljuː/","ارزش","Good value for money.","ارزش خرید خوبی دارد.","a modest product beside a small stack of banknotes"),
]

V[12] = [
 ("carefully","adverb","/ˈkeəfəli/","با دقت","She drives carefully.","با دقت رانندگی می‌کند.","a woman in her early thirties driving with both hands on the wheel"),
 ("quickly","adverb","/ˈkwɪkli/","سریع","He answered quickly.","سریع جواب داد.","a man in his early thirties raising his hand fast in a meeting"),
 ("slowly","adverb","/ˈsləʊli/","آهسته","Please speak slowly.","لطفاً آهسته صحبت کن.","a woman in her early thirties speaking with a calm measured gesture"),
 ("quietly","adverb","/ˈkwaɪətli/","بی‌سروصدا","He closed the door quietly.","بی‌سروصدا در را بست.","a hand gently pushing a door shut"),
 ("loudly","adverb","/ˈlaʊdli/","بلند","She spoke loudly.","بلند صحبت کرد.","a woman in her early thirties speaking to a large group with a raised hand"),
 ("badly","adverb","/ˈbædli/","بد","He played badly today.","امروز بد بازی کرد.","a man in his early thirties looking disappointed on a sports field"),
 ("well","adverb","/wel/","خوب","She sings very well.","خیلی خوب آواز می‌خواند.","a woman in her early thirties singing confidently with a microphone"),
 ("politely","adverb","/pəˈlaɪtli/","مؤدبانه","He asked politely.","مؤدبانه پرسید.","a man in his early thirties speaking with a courteous open gesture"),
 ("easily","adverb","/ˈiːzɪli/","به‌راحتی","She found it easily.","به‌راحتی پیدایش کرد.","a woman in her early thirties picking an item from a shelf without effort"),
 ("hard","adverb","/hɑːd/","سخت","He works hard.","سخت کار می‌کند.","a man in his early thirties concentrating over a long task"),
 ("safely","adverb","/ˈseɪfli/","با ایمنی","We arrived safely.","با ایمنی رسیدیم.","a car parked correctly beside a kerb with the driver stepping out"),
 ("clearly","adverb","/ˈklɪəli/","واضح","Please write clearly.","لطفاً واضح بنویس.","a hand writing neatly on a blank page"),
 ("driver","noun","/ˈdraɪvə/","راننده","The driver was careful.","راننده مراقب بود.","a driver in their thirties looking attentively at the road"),
 ("speed","noun","/spiːd/","سرعت","Reduce your speed.","سرعتت را کم کن.","a plain speed dial on a car dashboard"),
 ("behaviour","noun","/bɪˈheɪvjə/","رفتار","His behaviour was polite.","رفتارش مؤدبانه بود.","a man in his early thirties holding a door open for another person"),
 ("manner","noun","/ˈmænə/","شیوه","She explained it in a simple manner.","به شیوه ساده‌ای توضیحش داد.","a woman in her early thirties drawing a simple diagram for a listener"),
 ("skill","noun","/skɪl/","مهارت","Cooking is a useful skill.","آشپزی مهارت مفیدی است.","a man in his early thirties preparing food with practised movements"),
 ("mistake","noun","/mɪˈsteɪk/","اشتباه","I made a small mistake.","اشتباه کوچکی کردم.","a woman in her early thirties calmly correcting a line in a notebook"),
 ("attention","noun","/əˈtenʃn/","توجه","Pay attention, please.","لطفاً توجه کن.","a group of adults in their thirties looking attentively forward"),
 ("effort","noun","/ˈefət/","تلاش","It takes effort.","تلاش می‌خواهد.","a man in his early thirties persisting at a demanding task"),
]

V[13] = [
 ("as … as","phrase","/əz … əz/","به‌اندازه","It's as big as mine.","به‌اندازه مالِ من بزرگ است.","two identical bags placed side by side"),
 ("same","adjective","/seɪm/","یکسان","They're exactly the same.","دقیقاً یکسان‌اند.","two identical objects on a plain surface"),
 ("similar","adjective","/ˈsɪmələ/","شبیه","These two are similar.","این دو شبیه هم‌اند.","two nearly identical items with a small visible difference"),
 ("different","adjective","/ˈdɪfrənt/","متفاوت","They're completely different.","کاملاً متفاوت‌اند.","two clearly dissimilar objects side by side"),
 ("almost","adverb","/ˈɔːlməʊst/","تقریباً","It's almost the same price.","تقریباً همان قیمت است.","two price tags with nearly identical marks"),
 ("exactly","adverb","/ɪɡˈzæktli/","دقیقاً","That's exactly right.","دقیقاً درست است.","a hand aligning two objects perfectly"),
 ("difference","noun","/ˈdɪfrəns/","تفاوت","What's the difference?","تفاوتش چیست؟","a woman in her early thirties holding two similar items and comparing"),
 ("both","determiner","/bəʊθ/","هر دو","Both options are good.","هر دو گزینه خوب‌اند.","two items presented equally on a table"),
 ("neither","determiner","/ˈnaɪðə/","هیچ‌کدام","Neither one is cheap.","هیچ‌کدام ارزان نیست.","a man in his early thirties shaking his head at two options"),
 ("twice","adverb","/twaɪs/","دو برابر","It's twice as long.","دو برابر طولانی‌تر است.","one long object beside a shorter one of half its length"),
 ("half","noun","/hɑːf/","نصف","It costs half as much.","نصف قیمت است.","a single item beside a stack of banknotes half the size of another"),
 ("enough","determiner","/ɪˈnʌf/","کافی","That's enough for us.","برای ما کافی است.","a modest portion of food on a plate looking satisfying"),
 ("weight","noun","/weɪt/","وزن","They have the same weight.","وزنشان یکی است.","a balanced two-pan scale with equal loads"),
 ("height","noun","/haɪt/","قد، ارتفاع","We're the same height.","هم‌قدیم.","two adults in their thirties standing back to back at equal height"),
 ("distance","noun","/ˈdɪstəns/","فاصله","The distance is the same.","فاصله یکی است.","two equal gaps marked between three posts"),
 ("heavy","adjective","/ˈhevi/","سنگین","This isn't as heavy as that.","این به‌سنگینی آن نیست.","a man in his early thirties lifting one box easily and another with effort"),
 ("light","adjective","/laɪt/","سبک","This bag is lighter.","این کیف سبک‌تر است.","a woman in her early thirties carrying a small bag effortlessly"),
 ("wide","adjective","/waɪd/","پهن","The road is wider here.","جاده اینجا پهن‌تر است.","a road that visibly widens ahead"),
 ("narrow","adjective","/ˈnærəʊ/","باریک","That street is narrower.","آن خیابان باریک‌تر است.","a narrow alley between two buildings"),
 ("equal","adjective","/ˈiːkwəl/","برابر","The two parts are equal.","دو بخش برابرند.","two identical halves of a divided shape"),
]

V[14] = [
 ("for","preposition","/fɔː/","به مدت","I've lived here for years.","سال‌هاست اینجا زندگی می‌کنم.","a woman in her early thirties standing comfortably in a familiar home"),
 ("since","preposition","/sɪns/","از (زمان)","I've known her since 2015.","از ۲۰۱۵ می‌شناسمش.","two friends in their thirties looking at an old photograph together"),
 ("ever","adverb","/ˈevə/","هرگز، تا حالا","Have you ever been there?","تا حالا آنجا رفته‌ای؟","a man in his early thirties looking at a distant landscape thoughtfully"),
 ("never","adverb","/ˈnevə/","هرگز","I've never tried it.","هرگز امتحانش نکرده‌ام.","a woman in her early thirties looking curiously at an unfamiliar dish"),
 ("recently","adverb","/ˈriːsntli/","اخیراً","I've seen her recently.","اخیراً دیدمش.","two adults in their thirties greeting each other on a street"),
 ("period","noun","/ˈpɪəriəd/","دوره","It was a difficult period.","دوره سختی بود.","a man in his early thirties looking back thoughtfully at a window"),
 ("month","noun","/mʌnθ/","ماه","I've been here for a month.","یک ماه است اینجایم.","a plain wall calendar page"),
 ("year","noun","/jɪə/","سال","She's worked here for two years.","دو سال است اینجا کار می‌کند.","a woman in her early thirties at a familiar desk with personal items"),
 ("hour","noun","/ˈaʊə/","ساعت","We've waited for an hour.","یک ساعت است منتظریم.","two adults in their thirties waiting on a bench looking tired"),
 ("for a while","phrase","/fər ə ˈwaɪl/","مدتی","We waited for a while.","مدتی منتظر ماندیم.","two adults in their thirties sitting patiently on a bench"),
 ("age","noun","/eɪdʒ/","سن","We've been friends since a young age.","از سنین کم دوستیم.","two adults in their thirties laughing over an old photo album"),
 ("recently built","phrase","/ˈriːsntli bɪlt/","تازه‌ساخت","It's a recently built house.","خانه تازه‌ساختی است.","a newly finished house with clean surfaces"),
 ("these days","phrase","/ðiːz deɪz/","این روزها","These days I work from home.","این روزها از خانه کار می‌کنم.","a woman in her early thirties working at a laptop in a home corner"),
 ("no longer","phrase","/nəʊ ˈlɒŋɡə/","دیگر نه","He no longer works here.","دیگر اینجا کار نمی‌کند.","an empty tidy desk in an office"),
 ("experience","noun","/ɪkˈspɪəriəns/","تجربه","She has a lot of experience.","تجربه زیادی دارد.","a woman in her early thirties confidently guiding a colleague"),
 ("change","verb","/tʃeɪndʒ/","تغییر کردن","Things have changed.","چیزها عوض شده‌اند.","a street shown with old and new buildings side by side"),
 ("grow","verb","/ɡrəʊ/","رشد کردن","The city has grown.","شهر رشد کرده است.","a wide city view with construction cranes among buildings"),
 ("improve","verb","/ɪmˈpruːv/","بهتر شدن","My English has improved.","انگلیسی‌ام بهتر شده.","a woman in her early thirties speaking confidently to a group"),
 ("keep","verb","/kiːp/","نگه داشتن","I've kept this book for years.","سال‌هاست این کتاب را نگه داشته‌ام.","a well-worn book held carefully in two hands"),
 ("live","verb","/lɪv/","زندگی کردن","We've lived here since 2019.","از ۲۰۱۹ اینجا زندگی می‌کنیم.","two adults in their thirties in the doorway of their settled home"),
]

V[15] = [
 ("been","verb","/biːn/","بوده","Have you been to Iran?","به ایران رفته‌ای؟","a traveller in their thirties with a bag looking at a distant landscape"),
 ("visit","verb","/ˈvɪzɪt/","بازدید کردن","I've visited many cities.","شهرهای زیادی را دیده‌ام.","a woman in her early thirties walking through a historic square"),
 ("travel","verb","/ˈtrævl/","سفر کردن","She's travelled a lot.","خیلی سفر کرده است.","a man in his early thirties walking through an airport with a bag"),
 ("abroad","adverb","/əˈbrɔːd/","خارج از کشور","Have you worked abroad?","خارج از کشور کار کرده‌ای؟","a departures area with travellers in their thirties"),
 ("amazing","adjective","/əˈmeɪzɪŋ/","شگفت‌انگیز","The view was amazing.","منظره شگفت‌انگیز بود.","a woman in her early thirties looking with wonder at a vast landscape"),
 ("guide","noun","/ɡaɪd/","راهنما","We had a local guide.","راهنمای محلی داشتیم.","a guide in their thirties pointing something out to two visitors"),
 ("meet","verb","/miːt/","ملاقات کردن","I've met her before.","قبلاً دیدمش.","two adults in their thirties greeting each other with recognition"),
 ("climb","verb","/klaɪm/","بالا رفتن","We've climbed that mountain.","از آن کوه بالا رفته‌ایم.","two adults in their thirties on a mountain path with a summit ahead"),
 ("fly","verb","/flaɪ/","پرواز کردن","I've never flown before.","تا حالا پرواز نکرده‌ام.","an aircraft wing seen through a cabin window"),
 ("win","verb","/wɪn/","بردن","She's won three times.","سه بار برده است.","a woman in her early thirties holding a small trophy"),
 ("lose","verb","/luːz/","باختن، گم کردن","I've lost my ticket.","بلیتم را گم کرده‌ام.","a man in his early thirties searching his pockets at a station"),
 ("forget","verb","/fəˈɡet/","فراموش کردن","I've forgotten his name.","اسمش را فراموش کرده‌ام.","a woman in her early thirties with a hand on her forehead, thinking"),
 ("adventure","noun","/ədˈventʃə/","ماجراجویی","It was a real adventure.","ماجراجویی واقعی بود.","a backpack and boots at the start of a mountain trail"),
 ("desert","noun","/ˈdezət/","کویر","Have you seen the desert?","کویر را دیده‌ای؟","wide sand dunes under a clear sky"),
 ("forest","noun","/ˈfɒrɪst/","جنگل","We've walked in the forest.","در جنگل قدم زده‌ایم.","a green forest path between tall trees"),
 ("island","noun","/ˈaɪlənd/","جزیره","I've never visited an island.","هرگز به جزیره‌ای نرفته‌ام.","a small green island surrounded by calm sea"),
 ("culture","noun","/ˈkʌltʃə/","فرهنگ","I love learning about cultures.","عاشق یادگیری درباره فرهنگ‌هایم.","traditional patterned textiles displayed on a wall"),
 ("language","noun","/ˈlæŋɡwɪdʒ/","زبان","She's learned three languages.","سه زبان یاد گرفته است.","a woman in her early thirties with several notebooks open"),
 ("once","adverb","/wʌns/","یک بار","I've been there once.","یک بار آنجا رفته‌ام.","a single ticket stub kept in a notebook"),
 ("souvenir","noun","/ˌsuːvəˈnɪə/","سوغاتی","I bought a small souvenir.","سوغاتی کوچکی خریدم.","a small handcrafted keepsake held in an open palm"),
]

V[16] = [
 ("yet","adverb","/jet/","هنوز","I haven't started yet.","هنوز شروع نکرده‌ام.","an unopened book beside an empty notepad"),
 ("just","adverb","/dʒʌst/","همین الان","She's just arrived.","همین الان رسید.","a woman in her early thirties stepping through a doorway with a bag"),
 ("start","verb","/stɑːt/","شروع کردن","We've just started.","تازه شروع کرده‌ایم.","a woman in her early thirties opening a fresh notebook"),
 ("pay","verb","/peɪ/","پرداختن","Have you paid yet?","پرداخت کرده‌ای؟","a hand placing a bank card on a payment terminal"),
 ("solve","verb","/sɒlv/","حل کردن","We've solved the problem.","مشکل را حل کرده‌ایم.","two adults in their thirties looking relieved at a finished diagram"),
 ("submit","verb","/səbˈmɪt/","ثبت کردن","I've submitted the form.","فرم را ثبت کرده‌ام.","a hand placing a completed form into a tray"),
 ("review","verb","/rɪˈvjuː/","بازبینی کردن","I've reviewed the report.","گزارش را بازبینی کرده‌ام.","a man in his early thirties reading a page closely with a pen"),
 ("collect","verb","/kəˈlekt/","جمع کردن","I've collected the papers.","کاغذها را جمع کرده‌ام.","hands gathering loose sheets into a neat stack"),
 ("deliver","verb","/dɪˈlɪvə/","تحویل دادن","They've delivered the package.","بسته را تحویل داده‌اند.","a courier in their thirties handing a parcel to someone at a door"),
 ("sign","verb","/saɪn/","امضا کردن","Have you signed it yet?","امضایش کرده‌ای؟","a hand signing at the bottom of a plain document"),
 ("print","verb","/prɪnt/","چاپ کردن","I've printed the tickets.","بلیت‌ها را چاپ کرده‌ام.","fresh sheets emerging from an office printer"),
 ("reply","verb","/rɪˈplaɪ/","پاسخ دادن","She hasn't replied yet.","هنوز پاسخ نداده.","a woman in her early thirties looking at a phone with a waiting expression"),
 ("attach","verb","/əˈtætʃ/","پیوست کردن","I've attached the file.","فایل را پیوست کرده‌ام.","a paper clip fastening two sheets together"),
 ("update","verb","/ˌʌpˈdeɪt/","به‌روزرسانی کردن","I've updated the list.","فهرست را به‌روز کرده‌ام.","a hand adding a new line to an existing written list"),
 ("deadline","noun","/ˈdedlaɪn/","مهلت","The deadline is Friday.","مهلت جمعه است.","a wall calendar with one day circled"),
 ("task","noun","/tɑːsk/","کار، وظیفه","I have three tasks left.","سه کار مانده.","a plain checklist with some boxes ticked"),
 ("list","noun","/lɪst/","فهرست","I've made a list.","فهرستی درست کرده‌ام.","a hand-written list on a notepad without readable text"),
 ("progress","noun","/ˈprəʊɡres/","پیشرفت","We've made good progress.","پیشرفت خوبی داشته‌ایم.","two adults in their thirties looking satisfied at completed work"),
 ("complete","adjective","/kəmˈpliːt/","کامل","The work is complete.","کار کامل است.","a finished project laid out neatly on a desk"),
 ("upload","verb","/ˈʌpləʊd/","بارگذاری کردن","I've uploaded the photos.","عکس‌ها را بارگذاری کرده‌ام.","a laptop showing a progress bar without text"),
]

V[17] = [
 ("interview","noun","/ˈɪntəvjuː/","مصاحبه","I had an interview yesterday.","دیروز مصاحبه داشتم.","two adults in their thirties seated across a desk in a formal conversation"),
 ("last night","phrase","/ˌlɑːst ˈnaɪt/","دیشب","I saw him last night.","دیشب دیدمش.","two adults in their thirties talking outside in evening light"),
 ("this week","phrase","/ˌðɪs ˈwiːk/","این هفته","I've seen him this week.","این هفته دیدمش.","a plain weekly planner on a desk"),
 ("before","adverb","/bɪˈfɔː/","قبلاً","Have you done this before?","قبلاً این کار را کرده‌ای؟","a man in his early thirties looking at a task with familiarity"),
 ("finished","adjective","/ˈfɪnɪʃt/","تمام‌شده","The project is finished.","پروژه تمام شده است.","a completed piece of work set aside on a desk"),
 ("return","verb","/rɪˈtɜːn/","برگشتن","She's returned from her trip.","از سفرش برگشته.","a woman in her early thirties entering a home with a suitcase"),
 ("move","verb","/muːv/","نقل مکان کردن","They moved last month.","ماه پیش نقل مکان کردند.","two adults in their thirties carrying boxes into a new home"),
 ("apply","verb","/əˈplaɪ/","درخواست دادن","I applied for the job.","برای آن شغل درخواست دادم.","a woman in her early thirties filling in a form at a desk"),
 ("work","verb","/wɜːk/","کار کردن","He's worked here since May.","از اردیبهشت اینجا کار می‌کند.","a man in his early thirties at a settled workstation"),
 ("study","verb","/ˈstʌdi/","تحصیل کردن","She studied in Tehran.","در تهران تحصیل کرد.","a university building with adult students outside"),
 ("finish line","phrase","/ˈfɪnɪʃ laɪn/","خط پایان","We're near the finish line.","نزدیک خط پایانیم.","a running track with a marked line ahead"),
 ("career","noun","/kəˈrɪə/","حرفه، شغل","She's had a long career.","حرفه طولانی‌ای داشته.","a woman in her early thirties in a professional setting with awards on a shelf"),
 ("company","noun","/ˈkʌmpəni/","شرکت","I've worked for this company for years.","سال‌هاست برای این شرکت کار می‌کنم.","a modern office lobby with a reception desk"),
 ("project","noun","/ˈprɒdʒekt/","پروژه","The project started in May.","پروژه اردیبهشت شروع شد.","a large plan drawing spread on a table"),
 ("salary","noun","/ˈsæləri/","حقوق","The salary is good.","حقوقش خوب است.","a payslip and a few banknotes on a desk"),
 ("lately","adverb","/ˈleɪtli/","این اواخر","I haven't seen him lately.","این اواخر ندیدمش.","an empty chair at a familiar table"),
 ("history","noun","/ˈhɪstri/","تاریخ","This city has a long history.","این شهر تاریخ طولانی‌ای دارد.","an old stone building beside modern ones"),
 ("recently opened","phrase","/ˈriːsntli ˈəʊpənd/","تازه‌افتتاح","A new cafe has recently opened.","کافه‌ای تازه افتتاح شده.","a bright new cafe interior with fresh furnishings"),
 ("promotion","noun","/prəˈməʊʃn/","ترفیع","She got a promotion.","ترفیع گرفت.","a woman in her early thirties being congratulated by colleagues"),
 ("training","noun","/ˈtreɪnɪŋ/","آموزش","The training lasted a week.","آموزش یک هفته طول کشید.","a small group of adults in their thirties in a workshop room"),
]

V[18] = [
 ("made","verb","/meɪd/","ساخته شد","It was made in Iran.","در ایران ساخته شد.","a craftsman in their thirties finishing a handmade object"),
 ("wood","noun","/wʊd/","چوب","The table is made of wood.","میز از چوب ساخته شده.","a wooden plank with visible grain on a workbench"),
 ("written","verb","/ˈrɪtn/","نوشته شد","This book was written long ago.","این کتاب خیلی وقت پیش نوشته شد.","an old book with worn pages on a desk"),
 ("sold","verb","/səʊld/","فروخته شد","The tickets were sold quickly.","بلیت‌ها سریع فروخته شدند.","an empty ticket counter with a closed shutter"),
 ("used","verb","/juːzd/","استفاده شد","This room is used for meetings.","این اتاق برای جلسات استفاده می‌شود.","a meeting room with chairs around a table"),
 ("grown","verb","/ɡrəʊn/","پرورش داده شد","Rice is grown here.","اینجا برنج کشت می‌شود.","green rice fields under open sky"),
 ("produced","verb","/prəˈdjuːst/","تولید شد","This is produced locally.","این محلی تولید می‌شود.","a small workshop with finished goods on a bench"),
 ("designed","verb","/dɪˈzaɪnd/","طراحی شد","It was designed by a young architect.","توسط معمار جوانی طراحی شد.","architectural drawings spread on a wide table"),
 ("repaired","verb","/rɪˈpeəd/","تعمیر شد","The car was repaired yesterday.","خودرو دیروز تعمیر شد.","a mechanic in their thirties closing a car bonnet"),
 ("invented","verb","/ɪnˈventɪd/","اختراع شد","The wheel was invented long ago.","چرخ خیلی وقت پیش اختراع شد.","a simple wooden wheel on a workshop floor"),
 ("factory","noun","/ˈfæktri/","کارخانه","It comes from a local factory.","از کارخانه‌ای محلی می‌آید.","a clean industrial workshop interior"),
 ("material","noun","/məˈtɪəriəl/","ماده، جنس","What material is it?","از چه جنسی است؟","folded fabric and wood samples on a table"),
 ("product","noun","/ˈprɒdʌkt/","محصول","This product is popular.","این محصول محبوب است.","a single finished item displayed on a plain stand"),
 ("machine","noun","/məˈʃiːn/","دستگاه","The machine is very old.","دستگاه خیلی قدیمی است.","an old workshop machine with worn metal parts"),
 ("process","noun","/ˈprəʊses/","فرایند","It's a slow process.","فرایند کندی است.","several stages of a craft laid out in order on a bench"),
 ("hand-made","adjective","/ˌhændˈmeɪd/","دست‌ساز","It's completely hand-made.","کاملاً دست‌ساز است.","hands shaping clay on a potter's wheel"),
 ("local","adjective","/ˈləʊkl/","محلی","We buy local products.","محصولات محلی می‌خریم.","a small neighbourhood shop with fresh goods"),
 ("famous","adjective","/ˈfeɪməs/","مشهور","This city is famous for carpets.","این شهر به فرش مشهور است.","a patterned carpet displayed on a wall"),
 ("traditional","adjective","/trəˈdɪʃənl/","سنتی","It's a traditional method.","روش سنتی‌ای است.","traditional craft tools on a wooden workbench"),
 ("metal","noun","/ˈmetl/","فلز","The frame is made of metal.","قاب از فلز ساخته شده.","a polished metal frame resting on a workbench"),
]

V[19] = [
 ("who","pronoun","/huː/","که (برای افراد)","The man who helped me.","مردی که کمکم کرد.","a man in his early thirties helping another carry a box"),
 ("which","pronoun","/wɪtʃ/","که (برای اشیا)","The book which I bought.","کتابی که خریدم.","a single book held in two hands"),
 ("that","pronoun","/ðæt/","که","The house that we saw.","خانه‌ای که دیدیم.","a modest house viewed from a street"),
 ("where","adverb","/weə/","جایی که","The cafe where we met.","کافه‌ای که همدیگر را دیدیم.","two chairs at a small cafe table"),
 ("patient","adjective","/ˈpeɪʃnt/","صبور","He's a patient teacher.","معلم صبوری است.","a man in his early thirties calmly explaining something twice"),
 ("colleague","noun","/ˈkɒliːɡ/","همکار","A colleague who speaks English.","همکاری که انگلیسی صحبت می‌کند.","two colleagues in their thirties talking at a desk"),
 ("owner","noun","/ˈəʊnə/","صاحب","The owner who sold it.","صاحبی که فروختش.","a shopkeeper in their thirties behind a counter"),
 ("customer","noun","/ˈkʌstəmə/","مشتری","A customer who complained.","مشتری‌ای که شکایت کرد.","a customer in their thirties speaking seriously at a counter"),
 ("stranger","noun","/ˈstreɪndʒə/","غریبه","A stranger who helped us.","غریبه‌ای که کمکمان کرد.","an unfamiliar person in their thirties giving directions on a street"),
 ("expert","noun","/ˈekspɜːt/","متخصص","An expert who knows this well.","متخصصی که این را خوب می‌داند.","a professional in their thirties explaining with confidence"),
 ("tool","noun","/tuːl/","ابزار","A tool which is very useful.","ابزاری که خیلی مفید است.","a well-used hand tool on a workbench"),
 ("device","noun","/dɪˈvaɪs/","دستگاه","A device that saves time.","دستگاهی که وقت صرفه‌جویی می‌کند.","a small modern appliance on a kitchen counter"),
 ("building","noun","/ˈbɪldɪŋ/","ساختمان","The building which we visited.","ساختمانی که بازدید کردیم.","a distinctive building facade"),
 ("street","noun","/striːt/","خیابان","The street where I grew up.","خیابانی که در آن بزرگ شدم.","a quiet residential street with old trees"),
 ("generous","adjective","/ˈdʒenərəs/","سخاوتمند","She's a generous person.","آدم سخاوتمندی است.","a woman in her early thirties offering a filled plate to guests"),
 ("kind","adjective","/kaɪnd/","مهربان","A person who is very kind.","کسی که خیلی مهربان است.","a woman in her early thirties offering help warmly"),
 ("honest","adjective","/ˈɒnɪst/","صادق","She's someone who is honest.","کسی است که صادق است.","two adults in their thirties speaking with direct open expressions"),
 ("serious","adjective","/ˈsɪəriəs/","جدی","It's a serious problem.","مشکل جدی‌ای است.","two adults in their thirties talking with concerned expressions"),
 ("interesting","adjective","/ˈɪntrəstɪŋ/","جالب","A story that is interesting.","داستانی که جالب است.","two adults in their thirties leaning in with curious expressions"),
 ("boring","adjective","/ˈbɔːrɪŋ/","کسل‌کننده","A film which was boring.","فیلمی که کسل‌کننده بود.","a man in his early thirties looking bored in a cinema seat"),
]

V[20] = [
 ("narrative","noun","/ˈnærətɪv/","روایت","It's a long narrative.","روایت بلندی است.","two adults in their thirties talking at length over tea"),
 ("describe","verb","/dɪˈskraɪb/","توصیف کردن","Can you describe it?","می‌توانی توصیفش کنی؟","a woman in her early thirties gesturing while explaining a scene"),
 ("continue","verb","/kənˈtɪnjuː/","ادامه دادن","Please continue.","لطفاً ادامه بده.","a listener in their thirties nodding encouragingly"),
 ("interrupt","verb","/ˌɪntəˈrʌpt/","قطع کردن حرف","Sorry to interrupt.","ببخشید که حرفت را قطع می‌کنم.","a man in his early thirties raising a hand politely mid-conversation"),
 ("mention","verb","/ˈmenʃn/","اشاره کردن","You mentioned that before.","قبلاً به آن اشاره کردی.","a woman in her early thirties pointing back with a recalling gesture"),
 ("repeat","verb","/rɪˈpiːt/","تکرار کردن","Could you repeat that?","می‌شود دوباره بگویید؟","a man in his early thirties leaning in to hear better"),
 ("remember","verb","/rɪˈmembə/","به یاد آوردن","I remember that day.","آن روز را به یاد دارم.","a woman in her early thirties smiling at an old photograph"),
 ("silence","noun","/ˈsaɪləns/","سکوت","There was a long silence.","سکوت طولانی‌ای بود.","two adults in their thirties sitting quietly without speaking"),
 ("conclusion","noun","/kənˈkluːʒn/","نتیجه‌گیری","What's your conclusion?","نتیجه‌گیری‌ات چیست؟","a man in his early thirties closing a folder with a decided expression"),
 ("part","noun","/pɑːt/","بخش","The best part was the end.","بهترین بخش پایانش بود.","a book open near its final pages"),
 ("character","noun","/ˈkærəktə/","شخصیت","The main character was funny.","شخصیت اصلی بامزه بود.","an illustrated figure on a book cover without text"),
 ("scene","noun","/siːn/","صحنه","That scene was beautiful.","آن صحنه زیبا بود.","a wide scenic landscape at golden hour"),
 ("ending","noun","/ˈendɪŋ/","پایان","The ending surprised me.","پایانش غافلگیرم کرد.","a woman in her early thirties looking startled while closing a book"),
 ("argument","noun","/ˈɑːɡjumənt/","بحث","They had a short argument.","بحث کوتاهی داشتند.","two adults in their thirties in a tense but restrained discussion"),
 ("however","adverb","/haʊˈevə/","اما","However, we arrived late.","اما دیر رسیدیم.","two adults in their thirties arriving at a closed door"),
 ("although","conjunction","/ɔːlˈðəʊ/","اگرچه","Although it rained, we walked.","اگرچه باران بارید، پیاده رفتیم.","two adults in their thirties walking under one umbrella"),
 ("because of","phrase","/bɪˈkɒz əv/","به‌خاطر","We stayed because of the rain.","به‌خاطر باران ماندیم.","a person watching heavy rain from indoors"),
 ("in fact","phrase","/ɪn ˈfækt/","در واقع","In fact, it was easy.","در واقع آسان بود.","a man in his early thirties shrugging with a relaxed smile"),
 ("at last","phrase","/ət ˈlɑːst/","بالاخره","At last, we understood.","بالاخره فهمیدیم.","two adults in their thirties nodding with sudden understanding"),
 ("unforgettable","adjective","/ˌʌnfəˈɡetəbl/","فراموش‌نشدنی","It was an unforgettable trip.","سفر فراموش‌نشدنی‌ای بود.","two adults in their thirties looking at a striking landscape"),
]
