# -*- coding: utf-8 -*-
"""
محتوای دروس ۱۱ تا ۲۰ سطح A1.

جدا از `build_a1.py` نگه داشته شده چون آن فایل با ۳۰ درس غیرقابل خواندن
می‌شد. ساختار داده دقیقاً همان است و `build_a1.py` این‌ها را ادغام می‌کند.

قواعد صحنه تصویر (همان قواعد دروس ۱ تا ۱۰):
  - بزرگسال ۲۵ تا ۳۵ ساله، نه کودک
  - پوشش کامل و محتشم
  - هیچ متنی در تصویر نباشد (خودِ `imagegen.py` این را اضافه می‌کند)
  - صحنه باید معنی واژه را نشان دهد، نه فقط فضا را
"""

# (واژه, بخش کلام, IPA, فارسی, جمله انگلیسی, ترجمه, صحنه تصویر)
V = {}

V[11] = [
 ("music","noun","/ˈmjuːzɪk/","موسیقی","I like music.","موسیقی دوست دارم.","a woman in her early thirties listening to music with headphones, eyes closed, in a sunlit living room"),
 ("film","noun","/fɪlm/","فیلم","We watch a film on Friday.","جمعه‌ها فیلم می‌بینیم.","two adults in their thirties watching a film on a television in a cosy living room at night"),
 ("really","adverb","/ˈrɪəli/","واقعاً","I really like this.","واقعاً این را دوست دارم.","a woman in her early thirties smiling with genuine delight at something in her hands"),
 ("game","noun","/ɡeɪm/","بازی","They play a game together.","با هم بازی می‌کنند.","three adults in their thirties playing a board game around a low table, laughing"),
 ("sport","noun","/spɔːt/","ورزش","Sport is good for you.","ورزش برایت خوب است.","a man in his early thirties stretching before exercise in a park in the morning"),
 ("swimming","noun","/ˈswɪmɪŋ/","شنا","I like swimming.","شنا دوست دارم.","an indoor swimming pool with clear blue water and lane ropes, seen from the poolside, no people"),
 ("running","noun","/ˈrʌnɪŋ/","دویدن","Running is my hobby.","دویدن سرگرمی من است.","a woman in her early thirties in a loose long-sleeved tracksuit running along a tree-lined path"),
 ("cooking","noun","/ˈkʊkɪŋ/","آشپزی","He hates cooking.","از آشپزی متنفر است.","a man in his early thirties chopping vegetables at a kitchen counter with a frustrated expression"),
 ("dancing","noun","/ˈdɑːnsɪŋ/","رقص","She loves dancing.","رقص را خیلی دوست دارد.","a woman in her early thirties in a long modest dress moving joyfully to music in a bright room"),
 ("painting","noun","/ˈpeɪntɪŋ/","نقاشی","Painting is relaxing.","نقاشی آرامش‌بخش است.","a woman in her thirties painting on a canvas at an easel near a large window"),
 ("hobby","noun","/ˈhɒbi/","سرگرمی","What is your hobby?","سرگرمی‌ات چیست؟","a man in his early thirties arranging a small collection of hobby tools on a desk"),
 ("free time","noun","/ˌfriː ˈtaɪm/","اوقات فراغت","I read in my free time.","در اوقات فراغتم مطالعه می‌کنم.","a woman in her early thirties relaxing with a book and tea on a balcony in the afternoon"),
 ("favourite","adjective","/ˈfeɪvərɪt/","محبوب، مورد علاقه","This is my favourite song.","این آهنگ محبوب من است.","a man in his early thirties smiling while holding a single record album close to him"),
 ("interesting","adjective","/ˈɪntrəstɪŋ/","جالب","The film is interesting.","فیلم جالب است.","two adults in their thirties leaning forward with curious expressions during a presentation"),
 ("boring","adjective","/ˈbɔːrɪŋ/","کسل‌کننده","This game is boring.","این بازی کسل‌کننده است.","a man in his early thirties resting his chin on his hand looking bored at a table"),
 ("like","verb","/laɪk/","دوست داشتن","I like tea.","چای دوست دارم.","a woman in her early thirties smiling warmly while holding a cup of tea with both hands"),
 ("love","verb","/lʌv/","عاشق بودن","We love this city.","عاشق این شهر هستیم.","two adults in their thirties looking out over a city skyline with delighted expressions"),
 ("hate","verb","/heɪt/","متنفر بودن","He hates the rain.","از باران متنفر است.","a man in his early thirties frowning at heavy rain through a window"),
 ("thing","noun","/θɪŋ/","چیز","This is my favourite thing.","این چیز مورد علاقه من است.","a single small object held carefully in two hands"),
 ("great","adjective","/ɡreɪt/","عالی","That is a great idea.","فکر عالی‌ای است.","two adults in their thirties reacting with delight to something one has said"),
]

V[12] = [
 ("rice","noun","/raɪs/","برنج","Some rice, please.","کمی برنج، لطفاً.","a bowl of cooked white rice on a wooden table in warm daylight"),
 ("bread","noun","/bred/","نان","We buy fresh bread.","نان تازه می‌خریم.","a woman in her early thirties holding a warm loaf of bread in a bakery"),
 ("meat","noun","/miːt/","گوشت","I don't eat much meat.","زیاد گوشت نمی‌خورم.","slices of cooked meat arranged on a plate with herbs on a kitchen counter"),
 ("chicken","noun","/ˈtʃɪkɪn/","مرغ","There is chicken for dinner.","برای شام مرغ داریم.","a roasted chicken dish on a serving plate on a dining table"),
 ("fish","noun","/fɪʃ/","ماهی","Do you like fish?","ماهی دوست داری؟","a grilled fish with lemon slices on a white plate"),
 ("egg","noun","/eɡ/","تخم‌مرغ","I want two eggs.","دو تا تخم‌مرغ می‌خواهم.","two eggs in a small bowl beside a frying pan on a stove"),
 ("milk","noun","/mɪlk/","شیر","There isn't any milk.","هیچ شیری نیست.","a glass of milk beside an open empty refrigerator shelf"),
 ("water","noun","/ˈwɔːtə/","آب","Can I have some water?","می‌شود کمی آب بدهید؟","a glass of clear water being filled from a jug on a table"),
 ("tea","noun","/tiː/","چای","She drinks tea in the morning.","صبح‌ها چای می‌نوشد.","a woman in her early thirties pouring tea into a small glass at a kitchen table"),
 ("coffee","noun","/ˈkɒfi/","قهوه","I need a coffee.","به یک قهوه نیاز دارم.","a man in his early thirties holding a warm cup of coffee with both hands"),
 ("sugar","noun","/ˈʃʊɡə/","شکر","No sugar, thank you.","بدون شکر، ممنون.","a small bowl of white sugar with a spoon beside a tea glass"),
 ("salt","noun","/sɔːlt/","نمک","Add some salt.","کمی نمک اضافه کن.","a hand sprinkling salt into a cooking pot on a stove"),
 ("fruit","noun","/fruːt/","میوه","We eat a lot of fruit.","زیاد میوه می‌خوریم.","a bowl of mixed fresh fruit on a bright kitchen table"),
 ("food","noun","/fuːd/","غذا","I like Iranian food.","غذای ایرانی دوست دارم.","a table set with several simple dishes of home-cooked food"),
 ("vegetable","noun","/ˈvedʒtəbl/","سبزیجات","Vegetables are healthy.","سبزیجات سالم هستند.","fresh vegetables laid out on a kitchen counter ready for cooking"),
 ("cheese","noun","/tʃiːz/","پنیر","Is there any cheese?","پنیر هست؟","slices of cheese on a small wooden board with bread"),
 ("hungry","adjective","/ˈhʌŋɡri/","گرسنه","I'm very hungry.","خیلی گرسنه‌ام.","a man in his early thirties looking eagerly at a plate of food being placed in front of him"),
 ("thirsty","adjective","/ˈθɜːsti/","تشنه","Are you thirsty?","تشنه‌ای؟","a woman in her early thirties reaching for a glass of water after exercise"),
 ("some","determiner","/sʌm/","مقداری","I want some bread.","کمی نان می‌خواهم.","a hand taking a few slices of bread from a basket"),
 ("any","determiner","/ˈeni/","هیچ، مقداری","Is there any milk?","شیر هست؟","a man in his early thirties looking into an almost empty fridge with a questioning expression"),
]

V[13] = [
 ("restaurant","noun","/ˈrestrɒnt/","رستوران","We are at a restaurant.","در یک رستوران هستیم.","two adults in their thirties seated at a table inside a warm modern restaurant"),
 ("menu","noun","/ˈmenjuː/","منو","Can I see the menu?","می‌توانم منو را ببینم؟","a woman in her early thirties holding an open menu folder at a restaurant table"),
 ("waiter","noun","/ˈweɪtə/","پیشخدمت","The waiter is coming.","پیشخدمت دارد می‌آید.","a waiter in their thirties carrying a tray between restaurant tables"),
 ("knife","noun","/naɪf/","چاقو","I need a knife.","چاقو لازم دارم.","a table knife beside a plate"),
 ("thank","verb","/θæŋk/","تشکر کردن","I thank the waiter.","از پیشخدمت تشکر می‌کنم.","a seated customer in their thirties nodding gratefully to a waiter"),
 ("bill","noun","/bɪl/","صورتحساب","The bill, please.","صورتحساب، لطفاً.","a folded paper receipt on a small tray on a restaurant table"),
 ("plate","noun","/pleɪt/","بشقاب","Put it on the plate.","روی بشقاب بگذار.","a clean white plate on a wooden restaurant table"),
 ("glass","noun","/ɡlɑːs/","لیوان","Two glasses of water.","دو لیوان آب.","two glasses of water side by side on a table"),
 ("soup","noun","/suːp/","سوپ","I'd like the soup.","سوپ می‌خواهم.","a warm bowl of soup with a spoon on a table"),
 ("salad","noun","/ˈsæləd/","سالاد","A green salad, please.","یک سالاد سبز، لطفاً.","a fresh green salad in a bowl on a restaurant table"),
 ("give","verb","/ɡɪv/","دادن","Give me the menu, please.","لطفاً منو را به من بده.","a waiter in their thirties handing a menu to a seated guest"),
 ("bowl","noun","/bəʊl/","کاسه","The soup is in a bowl.","سوپ در کاسه است.","a bowl of soup on a wooden table"),
 ("dessert","noun","/dɪˈzɜːt/","دسر","We want a dessert.","دسر می‌خواهیم.","a small sweet dish served on a plate"),
 ("spoon","noun","/spuːn/","قاشق","I need a spoon.","قاشق لازم دارم.","a spoon resting beside a bowl on a table"),
 ("delicious","adjective","/dɪˈlɪʃəs/","خوشمزه","This soup is delicious.","این سوپ خوشمزه است.","a woman in her early thirties smiling and giving a thumbs up beside a steaming bowl of soup on a table"),
 ("hot","adjective","/hɒt/","داغ","Careful, it's hot.","مراقب باش، داغ است.","steam rising from a hot dish just placed on a table"),
 ("cold","adjective","/kəʊld/","سرد","My food is cold.","غذایم سرد است.","a man in his early thirties looking disappointed at an untouched plate of food"),
 ("fork","noun","/fɔːk/","چنگال","The fork is on the left.","چنگال سمت چپ است.","a fork placed neatly beside a plate"),
 ("order","verb","/ˈɔːdə/","سفارش دادن","We order two teas.","دو تا چای سفارش می‌دهیم.","two adults in their thirties pointing at a menu while a waiter writes"),
 ("pay","verb","/peɪ/","پرداختن","I will pay the bill.","من صورتحساب را می‌پردازم.","a man in his early thirties handing a bank card to a waiter at a table"),
]

V[14] = [
 ("garden","noun","/ˈɡɑːdn/","باغچه","There is a small garden.","باغچه کوچکی هست.","a small green garden behind a modest house"),
 ("flat","noun","/flæt/","آپارتمان","We live in a flat.","در آپارتمان زندگی می‌کنیم.","the front door of an apartment in a clean modern hallway"),
 ("room","noun","/ruːm/","اتاق","There are four rooms.","چهار اتاق هست.","an empty bright room with a window and wooden floor"),
 ("kitchen","noun","/ˈkɪtʃɪn/","آشپزخانه","There is a kitchen here.","اینجا آشپزخانه هست.","a tidy modern kitchen with counters and a window"),
 ("bedroom","noun","/ˈbedruːm/","اتاق خواب","My bedroom is small.","اتاق خوابم کوچک است.","a small tidy bedroom with a made bed and a bedside lamp"),
 ("bathroom","noun","/ˈbɑːθruːm/","حمام","Where is the bathroom?","حمام کجاست؟","a clean simple bathroom with a mirror and a sink"),
 ("living room","noun","/ˈlɪvɪŋ ruːm/","اتاق نشیمن","We sit in the living room.","در اتاق نشیمن می‌نشینیم.","a comfortable living room with a sofa and soft daylight"),
 ("gate","noun","/ɡeɪt/","دروازه","The gate is open.","دروازه باز است.","an open metal gate at the front of a house"),
 ("need","verb","/niːd/","نیاز داشتن","We need a bigger room.","به اتاق بزرگ‌تری نیاز داریم.","two adults in their thirties looking around a small crowded room"),
 ("floor","noun","/flɔː/","طبقه، کف","We live on the third floor.","طبقه سوم زندگی می‌کنیم.","a stairwell landing with a numbered apartment door"),
 ("wall","noun","/wɔːl/","دیوار","The wall is white.","دیوار سفید است.","a plain white interior wall with soft shadows"),
 ("stairs","noun","/steəz/","پله","The stairs are behind the door.","پله‌ها پشت در هستند.","a plain indoor staircase with a wooden rail"),
 ("lift","noun","/lɪft/","آسانسور","The lift is on the left.","آسانسور سمت چپ است.","a lift door in an apartment corridor"),
 ("rent","noun","/rent/","اجاره","The rent is high.","اجاره زیاد است.","a set of house keys resting on a written page"),
 ("find","verb","/faɪnd/","پیدا کردن","I need to find my keys.","باید کلیدهایم را پیدا کنم.","a man in his early thirties searching through a drawer with a puzzled expression"),
 ("roof","noun","/ruːf/","سقف، بام","The roof is old.","سقف قدیمی است.","the tiled roof of a small house seen from outside"),
 ("garage","noun","/ˈɡærɑːʒ/","پارکینگ","The car is in the garage.","خودرو در پارکینگ است.","a car parked inside a simple garage"),
 ("place","noun","/pleɪs/","جا، مکان","This is a quiet place.","اینجا جای آرامی است.","a calm corner of a room with a chair and a lamp"),
 ("yard","noun","/jɑːd/","حیاط","The children play in the yard.","بچه‌ها در حیاط بازی می‌کنند.","a small paved yard with a tree in one corner"),
 ("balcony","noun","/ˈbælkəni/","بالکن","There is a balcony upstairs.","طبقه بالا بالکن هست.","a small balcony with two chairs overlooking a street"),
]

V[15] = [
 ("shelf","noun","/ʃelf/","قفسه","The books are on the shelf.","کتاب‌ها روی قفسه‌اند.","a wooden shelf holding several books"),
 ("sofa","noun","/ˈsəʊfə/","مبل","The cat is on the sofa.","گربه روی مبل است.","a cat resting on a soft grey sofa in a living room"),
 ("bed","noun","/bed/","تخت","My bag is under the bed.","کیفم زیر تخت است.","a neatly made bed with a bag visible underneath"),
 ("lamp","noun","/læmp/","چراغ","The lamp is on the desk.","چراغ روی میز است.","a small desk lamp switched on beside a notebook"),
 ("carpet","noun","/ˈkɑːpɪt/","فرش","There is a carpet on the floor.","روی زمین فرش هست.","a patterned carpet covering a living room floor"),
 ("take","verb","/teɪk/","برداشتن","Take your bag, please.","لطفاً کیفت را بردار.","a man in his early thirties picking up a shoulder bag from a chair"),
 ("mirror","noun","/ˈmɪrə/","آینه","The mirror is on the wall.","آینه روی دیوار است.","a round mirror hanging on a plain wall"),
 ("put","verb","/pʊt/","گذاشتن","Put the book on the table.","کتاب را روی میز بگذار.","a woman in her early thirties placing a book onto a wooden table"),
 ("curtain","noun","/ˈkɜːtn/","پرده","The curtain is blue.","پرده آبی است.","a light curtain hanging beside a window"),
 ("desk","noun","/desk/","میز کار","She works at the desk.","پشت میز کار می‌کند.","a woman in her early thirties working at a tidy home desk"),
 ("fridge","noun","/frɪdʒ/","یخچال","The milk is in the fridge.","شیر در یخچال است.","an open refrigerator with a bottle of milk on a shelf"),
 ("television","noun","/ˈtelɪvɪʒn/","تلویزیون","The television is off.","تلویزیون خاموش است.","a switched-off flat television on a low stand"),
 ("cupboard","noun","/ˈkʌbəd/","کمد","The cups are in the cupboard.","فنجان‌ها در کمدند.","an open kitchen cupboard with plates and cups"),
 ("picture","noun","/ˈpɪktʃə/","تابلو، عکس","There is a picture on the wall.","روی دیوار تابلو هست.","a framed landscape picture hanging on a wall"),
 ("in","preposition","/ɪn/","داخل","The key is in the bag.","کلید داخل کیف است.","a key placed inside an open handbag"),
 ("on","preposition","/ɒn/","روی","The book is on the table.","کتاب روی میز است.","a closed book resting on a wooden table"),
 ("under","preposition","/ˈʌndə/","زیر","The cat is under the table.","گربه زیر میز است.","a cat sitting underneath a dining table"),
 ("next to","preposition","/ˈnekst tuː/","کنار","The lamp is next to the bed.","چراغ کنار تخت است.","a bedside lamp standing immediately beside a bed"),
 ("behind","preposition","/bɪˈhaɪnd/","پشت","The chair is behind the door.","صندلی پشت در است.","a chair placed behind a partly open door"),
 ("between","preposition","/bɪˈtwiːn/","بین","The table is between two chairs.","میز بین دو صندلی است.","a small table positioned between two chairs"),
]

V[16] = [
 ("coat","noun","/kəʊt/","پالتو","I have got a red coat.","یک پالتوی قرمز دارم.","a woman in her early thirties wearing a long red coat on a city street"),
 ("shirt","noun","/ʃɜːt/","پیراهن","He has got a white shirt.","یک پیراهن سفید دارد.","a man in his early thirties wearing a plain white long-sleeved shirt"),
 ("trousers","noun","/ˈtraʊzəz/","شلوار","These trousers are new.","این شلوار نو است.","a pair of neatly folded dark trousers on a bed"),
 ("dress","noun","/dres/","پیراهن زنانه","She has got a blue dress.","یک پیراهن آبی دارد.","a woman in her early thirties wearing a long modest blue dress"),
 ("skirt","noun","/skɜːt/","دامن","The skirt is long.","دامن بلند است.","a long flowing skirt hanging on a wardrobe rail"),
 ("shoes","noun","/ʃuːz/","کفش","My shoes are black.","کفش‌هایم مشکی است.","a pair of black shoes placed neatly by a doorway"),
 ("hat","noun","/hæt/","کلاه","He wears a hat in winter.","زمستان کلاه می‌پوشد.","a man in his early thirties wearing a warm knitted hat outdoors"),
 ("scarf","noun","/skɑːf/","شال گردن","She has got a green scarf.","یک شال گردن سبز دارد.","a woman in her early thirties wrapping a green scarf around her neck"),
 ("long","adjective","/lɒŋ/","بلند","She has a long coat.","پالتوی بلندی دارد.","a long coat hanging on a hook"),
 ("jacket","noun","/ˈdʒækɪt/","کت","I need a warm jacket.","به یک کت گرم نیاز دارم.","a man in his early thirties zipping up a warm jacket"),
 ("red","adjective","/red/","قرمز","The coat is red.","پالتو قرمز است.","a bright red fabric folded neatly on a table"),
 ("blue","adjective","/bluː/","آبی","I like blue.","آبی دوست دارم.","a deep blue fabric folded neatly on a table"),
 ("green","adjective","/ɡriːn/","سبز","Her scarf is green.","شال گردنش سبز است.","a green fabric folded neatly on a table"),
 ("black","adjective","/blæk/","مشکی","Black shoes, please.","کفش مشکی، لطفاً.","a black fabric folded neatly on a table"),
 ("white","adjective","/waɪt/","سفید","He has got a white shirt.","پیراهن سفید دارد.","a white fabric folded neatly on a table"),
 ("yellow","adjective","/ˈjeləʊ/","زرد","The bag is yellow.","کیف زرد است.","a yellow fabric folded neatly on a table"),
 ("brown","adjective","/braʊn/","قهوه‌ای","Brown is a warm colour.","قهوه‌ای رنگ گرمی است.","a brown fabric folded neatly on a table"),
 ("colour","noun","/ˈkʌlə/","رنگ","What colour is it?","چه رنگی است؟","several folded fabrics in different colours arranged side by side"),
 ("wear","verb","/weə/","پوشیدن","She wears a long coat.","پالتوی بلندی می‌پوشد.","a woman in her early thirties putting on a long coat by a mirror"),
 ("size","noun","/saɪz/","اندازه","What size is this?","این چه اندازه‌ای است؟","a hand holding up a folded garment to check its size"),
]

V[17] = [
 ("sell","verb","/sel/","فروختن","They sell fruit here.","اینجا میوه می‌فروشند.","a shopkeeper in their thirties handing fruit to a customer"),
 ("market","noun","/ˈmɑːkɪt/","بازار","We go to the market.","به بازار می‌رویم.","a busy indoor market with stalls and adult shoppers in their thirties"),
 ("seller","noun","/ˈselə/","فروشنده","The seller is friendly.","فروشنده خوش‌برخورد است.","a shopkeeper in their thirties smiling behind a counter"),
 ("price","noun","/praɪs/","قیمت","The price is good.","قیمت خوب است.","a small blank price tag attached to a garment"),
 ("customer","noun","/ˈkʌstəmə/","مشتری","The customer is waiting.","مشتری منتظر است.","a woman in her early thirties waiting patiently at a shop counter"),
 ("cash","noun","/kæʃ/","نقد","I pay in cash.","نقدی پرداخت می‌کنم.","a hand placing banknotes on a shop counter"),
 ("card","noun","/kɑːd/","کارت","Can I pay by card?","می‌توانم با کارت بپردازم؟","a hand holding a bank card near a payment terminal"),
 ("change","noun","/tʃeɪndʒ/","پول خرد","Here is your change.","این هم پول خردتان.","coins being handed back across a shop counter"),
 ("large","adjective","/lɑːdʒ/","بزرگ","I want a large one.","یکی بزرگ می‌خواهم.","two boxes side by side, one clearly larger"),
 ("cheap","adjective","/tʃiːp/","ارزان","These shoes are cheap.","این کفش‌ها ارزان است.","a man in his early thirties smiling while holding a modest pair of shoes"),
 ("expensive","adjective","/ɪkˈspensɪv/","گران","That coat is expensive.","آن پالتو گران است.","a woman in her early thirties raising her eyebrows at a price tag on a coat"),
 ("little","adjective","/ˈlɪtl/","کم، کوچک","I have little money.","پول کمی دارم.","a few coins in an open palm"),
 ("these","determiner","/ðiːz/","این‌ها","How much are these?","این‌ها چند هستند؟","a hand gesturing towards several items together on a shop shelf"),
 ("coin","noun","/kɔɪn/","سکه","I have two coins.","دو سکه دارم.","two coins resting in an open palm"),
 ("those","determiner","/ðəʊz/","آن‌ها","Those bags are nice.","آن کیف‌ها قشنگ هستند.","a row of bags displayed on a distant shop shelf"),
 ("buy","verb","/baɪ/","خریدن","I want to buy a shirt.","می‌خواهم یک پیراهن بخرم.","a man in his early thirties handing money to a shop assistant"),
 ("basket","noun","/ˈbɑːskɪt/","سبد","Put it in the basket.","بگذارش در سبد.","a shopping basket holding a few items"),
 ("cost","verb","/kɒst/","قیمت داشتن","How much does it cost?","چقدر قیمتش است؟","a customer in their thirties pointing questioningly at an item"),
 ("try on","verb","/ˈtraɪ ɒn/","پرو کردن","Can I try it on?","می‌توانم پرو کنم؟","a woman in her early thirties holding a coat up in front of a fitting-room mirror"),
 ("queue","noun","/kjuː/","صف","The queue is long.","صف طولانی است.","a line of adults waiting at a counter"),
]

V[18] = [
 ("weather","noun","/ˈweðə/","آب‌وهوا","How is the weather?","هوا چطور است؟","a wide view of a sky with mixed clouds and sunshine over a city"),
 ("rain","noun","/reɪn/","باران","There is a lot of rain.","باران زیادی می‌بارد.","heavy rain falling on a quiet street with puddles"),
 ("snow","noun","/snəʊ/","برف","We have snow in winter.","زمستان برف داریم.","snow covering a quiet street and rooftops"),
 ("wind","noun","/wɪnd/","باد","The wind is strong.","باد شدید است.","tree branches bending in strong wind on a grey day"),
 ("sun","noun","/sʌn/","خورشید","The sun is bright today.","امروز خورشید درخشان است.","a bright sun in a clear blue sky above rooftops"),
 ("cloud","noun","/klaʊd/","ابر","There are grey clouds.","ابرهای خاکستری هست.","thick grey clouds gathering over a landscape"),
 ("sky","noun","/skaɪ/","آسمان","The sky is blue.","آسمان آبی است.","a clear blue sky above an open field"),
 ("season","noun","/ˈsiːzn/","فصل","Which season do you like?","کدام فصل را دوست داری؟","four small landscape scenes showing different seasons side by side"),
 ("spring","noun","/sprɪŋ/","بهار","Spring is beautiful.","بهار زیباست.","a park with blossoming trees and fresh green grass"),
 ("summer","noun","/ˈsʌmə/","تابستان","It is hot in summer.","تابستان گرم است.","a sunny summer park with strong light and deep shadows"),
 ("autumn","noun","/ˈɔːtəm/","پاییز","Autumn is my favourite.","پاییز فصل محبوب من است.","a path covered with orange and brown autumn leaves"),
 ("winter","noun","/ˈwɪntə/","زمستان","Winter is very cold.","زمستان خیلی سرد است.","a bare winter tree in a snowy landscape under a pale sky"),
 ("warm","adjective","/wɔːm/","گرم و مطبوع","It is warm today.","امروز هوا مطبوع است.","a woman in her early thirties walking comfortably in mild sunny weather"),
 ("cool","adjective","/kuːl/","خنک","The evening is cool.","عصر خنک است.","a man in his early thirties wearing a light jacket in cool evening air"),
 ("wet","adjective","/wet/","خیس","The street is wet.","خیابان خیس است.","a wet street reflecting light after rain"),
 ("dry","adjective","/draɪ/","خشک","The ground is dry.","زمین خشک است.","cracked dry ground under strong sunlight"),
 ("cloudy","adjective","/ˈklaʊdi/","ابری","It is cloudy today.","امروز ابری است.","an overcast grey sky over a quiet street"),
 ("sunny","adjective","/ˈsʌni/","آفتابی","It is a sunny day.","روز آفتابی است.","a bright sunny street with clear shadows"),
 ("know","verb","/nəʊ/","دانستن","I know the answer.","جواب را می‌دانم.","a woman in her early thirties raising her hand confidently in a class"),
 ("storm","noun","/stɔːm/","طوفان","There was a storm.","طوفان بود.","dark clouds and bending trees in a strong wind"),
]

V[19] = [
 ("can","modal verb","/kæn/","توانستن","I can swim.","می‌توانم شنا کنم.","a swimmer seen from behind moving forward through calm blue pool water, only head and shoulders visible"),
 ("swim","verb","/swɪm/","شنا کردن","She can swim well.","خوب شنا می‌کند.","a swimmer seen from above gliding through blue pool water, only head and shoulders above the surface, arms mid-stroke"),
 ("drive","verb","/draɪv/","رانندگی کردن","He can drive a car.","می‌تواند رانندگی کند.","a man in his early thirties driving a car with both hands on the wheel"),
 ("climb","verb","/klaɪm/","بالا رفتن","I can climb a tree.","می‌توانم از درخت بالا بروم.","a man in his early thirties climbing a low tree branch"),
 ("sing","verb","/sɪŋ/","آواز خواندن","She can sing beautifully.","زیبا آواز می‌خواند.","a woman in her early thirties singing with a microphone in a small room"),
 ("dance","verb","/dɑːns/","رقصیدن","They can dance.","می‌توانند برقصند.","two adults in their thirties in modest clothing moving to music"),
 ("draw","verb","/drɔː/","نقاشی کشیدن","He can draw very well.","خیلی خوب نقاشی می‌کشد.","a man in his early thirties sketching in a notebook with a pencil"),
 ("ride","verb","/raɪd/","سوار شدن","I can ride a bike.","می‌توانم دوچرخه سواری کنم.","a woman in her early thirties riding a bicycle on a quiet path"),
 ("speak","verb","/spiːk/","صحبت کردن","She can speak English.","انگلیسی صحبت می‌کند.","a woman in her early thirties speaking confidently to a small group"),
 ("throw","verb","/θrəʊ/","پرتاب کردن","He can throw a ball.","می‌تواند توپ پرتاب کند.","a man in his early thirties throwing a ball in a park"),
 ("catch","verb","/kætʃ/","گرفتن","She can catch it.","می‌تواند بگیردش.","a woman in her early thirties catching a ball with both hands"),
 ("fix","verb","/fɪks/","تعمیر کردن","I can fix this.","می‌توانم این را تعمیر کنم.","a man in his early thirties repairing a small appliance"),
 ("jump","verb","/dʒʌmp/","پریدن","She can jump high.","می‌تواند بلند بپرد.","a woman in a loose long-sleeved tracksuit jumping upward on a sports field"),
 ("hear","verb","/hɪə/","شنیدن","I can't hear you.","صدایت را نمی‌شنوم.","a man in his early thirties cupping a hand behind his ear"),
 ("well","adverb","/wel/","خوب","He plays well.","خوب بازی می‌کند.","a man in his early thirties playing a guitar with a satisfied expression"),
 ("fast","adverb","/fɑːst/","تند","She runs fast.","تند می‌دود.","a runner in a loose long-sleeved tracksuit moving quickly along a path"),
 ("slowly","adverb","/ˈsləʊli/","آهسته","Please speak slowly.","لطفاً آهسته صحبت کن.","a woman in her early thirties speaking carefully with a calm gesture"),
 ("ability","noun","/əˈbɪləti/","توانایی","Everyone has an ability.","هر کسی توانایی دارد.","three adults in their thirties each doing a different skilled activity"),
 ("difficult","adjective","/ˈdɪfɪkəlt/","دشوار","This is difficult for me.","این برایم دشوار است.","a man in his early thirties frowning in concentration over a task"),
 ("try","verb","/traɪ/","تلاش کردن","I try every day.","هر روز تلاش می‌کنم.","a woman in her early thirties concentrating on a difficult task"),
]

V[20] = [
 ("body","noun","/ˈbɒdi/","بدن","Take care of your body.","مراقب بدنت باش.","a man in his early thirties stretching calmly in a loose long-sleeved tracksuit"),
 ("head","noun","/hed/","سر","My head hurts.","سرم درد می‌کند.","a woman in her early thirties touching her forehead with a pained expression"),
 ("hand","noun","/hænd/","دست","Wash your hands.","دست‌هایت را بشور.","two hands being washed under running water at a sink"),
 ("arm","noun","/ɑːm/","بازو","My arm is painful.","بازویم درد می‌کند.","a man in his early thirties holding his upper arm carefully"),
 ("leg","noun","/leɡ/","پا","He has a bad leg.","پایش مشکل دارد.","a man in his early thirties sitting with one leg extended and supported"),
 ("foot","noun","/fʊt/","کف پا","My foot is cold.","کف پایم سرد است.","a person's feet in warm socks on a rug"),
 ("eye","noun","/aɪ/","چشم","My eyes are tired.","چشم‌هایم خسته است.","a woman in her early thirties rubbing her tired eyes at a desk"),
 ("ear","noun","/ɪə/","گوش","I have an ear problem.","گوشم مشکل دارد.","a man in his early thirties touching his ear with a concerned expression"),
 ("tooth","noun","/tuːθ/","دندان","I have a bad tooth.","دندانم خراب است.","a woman in her early thirties holding her cheek with a pained expression"),
 ("back","noun","/bæk/","کمر","My back hurts.","کمرم درد می‌کند.","a man in his early thirties pressing a hand to his lower back"),
 ("headache","noun","/ˈhedeɪk/","سردرد","I have a headache.","سردرد دارم.","a woman in her early thirties resting her head in her hands at a table"),
 ("finger","noun","/ˈfɪŋɡə/","انگشت","My finger hurts.","انگشتم درد می‌کند.","a bandaged finger held up"),
 ("fever","noun","/ˈfiːvə/","تب","He has a fever.","تب دارد.","a man in his early thirties lying covered by a blanket with a thermometer nearby"),
 ("stomach","noun","/ˈstʌmək/","معده، شکم","I have a stomach ache.","دل‌درد دارم.","a man in his early thirties pressing a hand to his stomach"),
 ("medicine","noun","/ˈmedsn/","دارو","Take this medicine.","این دارو را بخور.","a small box of medicine and a glass of water on a table"),
 ("rest","noun","/rest/","استراحت","You need rest.","به استراحت نیاز داری.","a person resting on a sofa under a light blanket"),
 ("ill","adjective","/ɪl/","بیمار","I feel ill today.","امروز حالم بد است.","a man in his early thirties resting under a blanket looking unwell"),
 ("healthy","adjective","/ˈhelθi/","سالم","Fruit is healthy.","میوه سالم است.","a woman in her early thirties eating fresh fruit with a bright expression"),
 ("tired","adjective","/ˈtaɪəd/","خسته","She is very tired.","خیلی خسته است.","a woman in her early thirties yawning at a desk in the evening"),
 ("should","modal verb","/ʃʊd/","باید","You should rest.","باید استراحت کنی.","a doctor in their thirties gesturing calmly while advising a patient"),
]
