# -*- coding: utf-8 -*-
"""واژگان دروس ۱ تا ۱۰ سطح B1."""

V = {}

V[1] = [
 ("responsibility","noun","/rɪˌspɒnsəˈbɪləti/","مسئولیت","It's my responsibility.","مسئولیت من است.","a woman in her early thirties reviewing documents at a desk with focus"),
 ("colleague","noun","/ˈkɒliːɡ/","همکار","I work with three colleagues.","با سه همکار کار می‌کنم.","four adults in their thirties around a meeting table"),
 ("deadline","noun","/ˈdedlaɪn/","مهلت","We've been working to a tight deadline.","با مهلت فشرده‌ای کار کرده‌ایم.","a wall calendar with one day circled in red"),
 ("department","noun","/dɪˈpɑːtmənt/","بخش، دپارتمان","She works in the sales department.","در بخش فروش کار می‌کند.","an open-plan office area with several desks"),
 ("manager","noun","/ˈmænɪdʒə/","مدیر","The manager has been away.","مدیر نبوده است.","a manager in their thirties speaking with two colleagues"),
 ("employee","noun","/ɪmˈplɔɪiː/","کارمند","The company has fifty employees.","شرکت پنجاه کارمند دارد.","a group of adults in their thirties entering an office building"),
 ("salary","noun","/ˈsæləri/","حقوق","The salary is reasonable.","حقوقش منطقی است.","a payslip and banknotes on a desk"),
 ("promotion","noun","/prəˈməʊʃn/","ترفیع","He's been hoping for a promotion.","امید به ترفیع داشته است.","a man in his early thirties being congratulated at work"),
 ("overtime","noun","/ˈəʊvətaɪm/","اضافه‌کاری","I've been doing overtime.","اضافه‌کاری کرده‌ام.","a lit desk lamp in an otherwise dark office"),
 ("achievement","noun","/əˈtʃiːvmənt/","دستاورد","It was a real achievement.","دستاورد واقعی‌ای بود.","a woman in her early thirties looking proudly at finished work"),
 ("workload","noun","/ˈwɜːkləʊd/","حجم کار","The workload has increased.","حجم کار زیاد شده.","a desk stacked with folders and papers"),
 ("handle","verb","/ˈhændl/","از عهده برآمدن","She handles pressure well.","خوب از پس فشار برمی‌آید.","a woman in her early thirties working calmly amid a busy office"),
 ("manage","verb","/ˈmænɪdʒ/","اداره کردن","He manages a small team.","تیم کوچکی را اداره می‌کند.","a man in his early thirties guiding three colleagues at a whiteboard"),
 ("deal with","phrase","/diːl wɪð/","رسیدگی کردن به","I've been dealing with this all week.","تمام هفته به این رسیدگی کرده‌ام.","a person in their thirties sorting through a pile of documents"),
 ("focus on","phrase","/ˈfəʊkəs ɒn/","تمرکز کردن بر","We should focus on quality.","باید بر کیفیت تمرکز کنیم.","a hand pointing at one item on a simple chart"),
 ("in charge of","phrase","/ɪn tʃɑːdʒ əv/","مسئولِ","She's in charge of training.","مسئول آموزش است.","a woman in her early thirties leading a small workshop"),
 ("demanding","adjective","/dɪˈmɑːndɪŋ/","پرتوقع، سخت","It's a demanding job.","شغل سختی است.","a man in his early thirties working late with a tired expression"),
 (
  "rewarding","adjective","/rɪˈwɔːdɪŋ/","رضایت‌بخش","The work is rewarding.","کار رضایت‌بخش است.",
  "a woman in her early thirties smiling at a completed project"),
 ("efficient","adjective","/ɪˈfɪʃnt/","کارآمد","She's very efficient.","خیلی کارآمد است.","a tidy desk with everything neatly arranged"),
 ("so far","phrase","/səʊ fɑː/","تا اینجا","So far, everything is fine.","تا اینجا همه‌چیز خوب است.","a progress chart partly filled in"),
]

V[2] = [
 ("procedure","noun","/prəˈsiːdʒə/","روال، رویه","The procedure has been changed.","روال عوض شده است.","numbered steps laid out on a workbench"),
 ("system","noun","/ˈsɪstəm/","سامانه","The system was updated last night.","سامانه دیشب به‌روز شد.","server racks in a clean equipment room"),
 ("document","noun","/ˈdɒkjumənt/","سند","The documents have been checked.","اسناد بررسی شده‌اند.","a stack of plain papers on a desk"),
 ("approval","noun","/əˈpruːvl/","تأیید","We're waiting for approval.","منتظر تأیید هستیم.","a hand holding a pen above a form"),
 ("request","noun","/rɪˈkwest/","درخواست","Your request has been received.","درخواستتان دریافت شده.","an envelope being placed in a tray"),
 ("stage","noun","/steɪdʒ/","مرحله","We're at the final stage.","در مرحله پایانی هستیم.","several marked steps on a rising path"),
 ("standard","noun","/ˈstændəd/","استاندارد","The work meets the standard.","کار استاندارد را رعایت می‌کند.","a measuring tool beside a finished item"),
 ("quality control","phrase","/ˈkwɒləti kənˈtrəʊl/","کنترل کیفیت","Quality control is important.","کنترل کیفیت مهم است.","an inspector in their thirties examining a product closely"),
 ("supplier","noun","/səˈplaɪə/","تأمین‌کننده","The supplier was changed.","تأمین‌کننده عوض شد.","boxes being unloaded from a small van"),
 ("delivery","noun","/dɪˈlɪvəri/","تحویل","The delivery has been delayed.","تحویل به تأخیر افتاده.","a parcel left beside a doorway"),
 ("complete","verb","/kəmˈpliːt/","تکمیل کردن","The form must be completed.","فرم باید تکمیل شود.","a hand filling the last field of a form"),
 ("approve","verb","/əˈpruːv/","تأیید کردن","The plan was approved.","برنامه تأیید شد.","a manager in their thirties nodding over a document"),
 ("reject","verb","/rɪˈdʒekt/","رد کردن","The request was rejected.","درخواست رد شد.","a document set aside on a separate pile"),
 ("replace","verb","/rɪˈpleɪs/","جایگزین کردن","The part has been replaced.","قطعه تعویض شده.","a new component beside an old worn one"),
 ("inspect","verb","/ɪnˈspekt/","بازرسی کردن","Everything is inspected first.","اول همه‌چیز بازرسی می‌شود.","a person in their thirties examining items on a production line"),
 ("carry out","phrase","/ˈkæri aʊt/","انجام دادن","The test was carried out yesterday.","آزمایش دیروز انجام شد.","two adults in their thirties running a test at a bench"),
 ("set up","phrase","/set ʌp/","راه‌اندازی کردن","The system was set up in May.","سامانه در اردیبهشت راه‌اندازی شد.","technicians in their thirties installing equipment"),
 ("automatic","adjective","/ˌɔːtəˈmætɪk/","خودکار","The process is automatic.","فرایند خودکار است.","a clean automated production line"),
 ("reliable","adjective","/rɪˈlaɪəbl/","قابل اتکا","It's a reliable method.","روش قابل اتکایی است.","identical items produced consistently on a bench"),
 ("in progress","phrase","/ɪn ˈprəʊɡres/","در جریان","The work is still in progress.","کار هنوز در جریان است.","a half-finished project on a workbench"),
]

V[3] = [
 ("be used to","phrase","/bi ˈjuːst tuː/","عادت داشتن به","I'm used to the noise now.","حالا به سروصدا عادت کرده‌ام.","a woman in her early thirties working calmly beside a busy street window"),
 ("get used to","phrase","/ɡet ˈjuːst tuː/","عادت کردن به","It takes time to get used to it.","عادت کردن به آن زمان می‌برد.","a man in his early thirties gradually settling into a new desk"),
 ("routine","noun","/ruːˈtiːn/","روال روزانه","My routine has changed.","روال روزانه‌ام عوض شده.","a person in their thirties following the same morning steps"),
 ("adjust","verb","/əˈdʒʌst/","خود را وفق دادن","She adjusted quickly.","سریع خود را وفق داد.","a woman in her early thirties confidently at home in a new office"),
 ("adapt","verb","/əˈdæpt/","سازگار شدن","We had to adapt.","مجبور بودیم سازگار شویم.","two adults in their thirties rearranging a workspace"),
 ("environment","noun","/ɪnˈvaɪrənmənt/","محیط","It's a friendly environment.","محیط دوستانه‌ای است.","a bright office where colleagues chat easily"),
 ("culture shock","phrase","/ˈkʌltʃə ʃɒk/","شوک فرهنگی","I had a small culture shock.","شوک فرهنگی کوچکی داشتم.","a traveller in their thirties looking around an unfamiliar street"),
 ("challenge","noun","/ˈtʃælɪndʒ/","چالش","It was a real challenge.","چالش واقعی بود.","a man in his early thirties studying a complicated diagram"),
 ("difficulty","noun","/ˈdɪfɪkəlti/","دشواری","I had difficulty at first.","اول دشواری داشتم.","a woman in her early thirties frowning at a task"),
 ("progress","noun","/ˈprəʊɡres/","پیشرفت","I've made progress.","پیشرفت کرده‌ام.","a rising line on a simple chart"),
 ("gradually","adverb","/ˈɡrædʒuəli/","به‌تدریج","Things gradually improved.","اوضاع به‌تدریج بهتر شد.","a plant shown at three stages of growth"),
 ("at first","phrase","/ət fɜːst/","در ابتدا","At first it was hard.","در ابتدا سخت بود.","a person in their thirties hesitating at a new doorway"),
 ("eventually","adverb","/ɪˈventʃuəli/","سرانجام","Eventually I settled in.","سرانجام جا افتادم.","a woman in her early thirties comfortably settled at a personalised desk"),
 ("familiar","adjective","/fəˈmɪliə/","آشنا","The place feels familiar now.","حالا اینجا آشنا به‌نظر می‌رسد.","a man in his early thirties walking confidently through a known street"),
 ("strange","adjective","/streɪndʒ/","غریب","Everything felt strange.","همه‌چیز غریب به‌نظر می‌رسید.","a person in their thirties looking uncertainly around an unfamiliar room"),
 ("comfortable with","phrase","/ˈkʌmftəbl wɪð/","راحت با","I'm comfortable with the change.","با این تغییر راحتم.","a woman in her early thirties relaxed in a new workspace"),
 ("no longer","phrase","/nəʊ ˈlɒŋɡə/","دیگر نه","It's no longer difficult.","دیگر سخت نیست.","a task being completed easily and set aside"),
 ("attitude","noun","/ˈætɪtjuːd/","نگرش","He has a positive attitude.","نگرش مثبتی دارد.","a man in his early thirties smiling at a challenging task"),
 ("patience","noun","/ˈpeɪʃns/","صبر","It takes patience.","صبر می‌خواهد.","a woman in her early thirties calmly repeating a careful task"),
 ("confidence","noun","/ˈkɒnfɪdəns/","اعتماد به نفس","My confidence has grown.","اعتماد به نفسم بیشتر شده.","a woman in her early thirties presenting to a small group without notes"),
]

V[4] = [
 ("already gone","phrase","/ɔːlˈredi ɡɒn/","قبلاً رفته بود","She had already gone.","قبلاً رفته بود.","an empty chair beside a closed laptop"),
 ("arrive","verb","/əˈraɪv/","رسیدن","We arrived after the meeting.","بعد از جلسه رسیدیم.","two adults in their thirties entering a room where others are leaving"),
 ("realise","verb","/ˈrɪəlaɪz/","پی بردن","I realised I had forgotten it.","پی بردم فراموشش کرده بودم.","a man in his early thirties stopping suddenly with a startled look"),
 ("notice","verb","/ˈnəʊtɪs/","متوجه شدن","Nobody noticed the mistake.","کسی متوجه اشتباه نشد.","a small marked error on an otherwise clean page"),
 ("discover","verb","/dɪˈskʌvə/","کشف کردن","We discovered the problem late.","دیر مشکل را کشف کردیم.","two adults in their thirties examining an opened device"),
 ("explain","verb","/ɪkˈspleɪn/","توضیح دادن","He explained what had happened.","توضیح داد چه اتفاقی افتاده بود.","a man in his early thirties gesturing while explaining to two listeners"),
 ("forget","verb","/fəˈɡet/","فراموش کردن","I had forgotten his name.","اسمش را فراموش کرده بودم.","a woman in her early thirties pressing a hand to her forehead"),
 ("remember","verb","/rɪˈmembə/","به یاد آوردن","Then I remembered.","بعد به یادم آمد.","a man in his early thirties raising a finger as an idea strikes"),
 ("previously","adverb","/ˈpriːviəsli/","پیش‌تر","We had previously agreed.","پیش‌تر توافق کرده بودیم.","two adults in their thirties reviewing an earlier written note"),
 ("earlier","adverb","/ˈɜːliə/","زودتر","She had left earlier.","زودتر رفته بود.","a clock showing an earlier hour beside an empty desk"),
 ("by then","phrase","/baɪ ðen/","تا آن موقع","By then it was too late.","تا آن موقع دیر شده بود.","a closed shop shutter at dusk"),
 ("after that","phrase","/ˈɑːftə ðæt/","بعد از آن","After that, everything changed.","بعد از آن همه‌چیز عوض شد.","a fork in a path with one side clearly taken"),
 ("delay","noun","/dɪˈleɪ/","تأخیر","There had been a delay.","تأخیری پیش آمده بود.","travellers in their thirties waiting in a quiet station"),
 ("misunderstanding","noun","/ˌmɪsʌndəˈstændɪŋ/","سوءتفاهم","It was a misunderstanding.","سوءتفاهم بود.","two adults in their thirties talking with puzzled expressions"),
 ("apology","noun","/əˈpɒlədʒi/","عذرخواهی","He offered an apology.","عذرخواهی کرد.","a man in his early thirties speaking with a regretful open gesture"),
 ("relief","noun","/rɪˈliːf/","آسودگی","It was a relief.","مایه آسودگی بود.","a woman in her early thirties exhaling with a relaxed expression"),
 ("panic","verb","/ˈpænɪk/","وحشت کردن","Don't panic.","وحشت نکن.","a man in his early thirties taking a steadying breath"),
 ("calm down","phrase","/kɑːm daʊn/","آرام شدن","She calmed down quickly.","سریع آرام شد.","a woman in her early thirties sitting down with a cup of tea"),
 ("in the end","phrase","/ɪn ði end/","در پایان","In the end, we found it.","در پایان پیدایش کردیم.","two adults in their thirties nodding with resolved expressions"),
 ("fortunately","adverb","/ˈfɔːtʃənətli/","خوشبختانه","Fortunately, nothing was lost.","خوشبختانه چیزی از دست نرفت.","an intact bag returned to its owner"),
]

V[5] = [
 ("incident","noun","/ˈɪnsɪdənt/","رویداد، اتفاق","It was a strange incident.","اتفاق عجیبی بود.","two adults in their thirties looking at something unexpected on a street"),
 ("witness","noun","/ˈwɪtnəs/","شاهد","There was one witness.","یک شاهد بود.","a person in their thirties observing a scene from a distance"),
 ("describe","verb","/dɪˈskraɪb/","توصیف کردن","Can you describe what happened?","می‌توانی توصیف کنی چه شد؟","a woman in her early thirties gesturing while recounting an event"),
 ("recall","verb","/rɪˈkɔːl/","به یاد آوردن","I can't recall the details.","جزئیات را به یاد نمی‌آورم.","a man in his early thirties thinking with a hand on his chin"),
 ("occur","verb","/əˈkɜː/","رخ دادن","It occurred last winter.","زمستان گذشته رخ داد.","a snowy street with a single set of footprints"),
 ("background","noun","/ˈbækɡraʊnd/","پس‌زمینه","Let me give you the background.","بگذار پس‌زمینه‌اش را بگویم.","a wide street scene with people going about their day"),
 ("detail","noun","/ˈdiːteɪl/","جزئیات","The details matter.","جزئیات مهم است.","two adults in their thirties studying a document closely"),
 ("version","noun","/ˈvɜːʃn/","روایت، نسخه","He told a different version.","روایت متفاوتی گفت.","two adults in their thirties describing something with different gestures"),
 ("meanwhile","adverb","/ˈmiːnwaɪl/","در همان حال","Meanwhile, we waited outside.","در همان حال بیرون منتظر بودیم.","two adults in their thirties waiting under a doorway"),
 ("suddenly","adverb","/ˈsʌdnli/","ناگهان","Suddenly the lights went out.","ناگهان چراغ‌ها خاموش شد.","a dark room lit only by a window"),
 ("afterwards","adverb","/ˈɑːftəwədz/","پس از آن","Afterwards we went home.","پس از آن به خانه رفتیم.","two adults in their thirties walking away down a quiet street"),
 ("apparently","adverb","/əˈpærəntli/","ظاهراً","Apparently nobody knew.","ظاهراً کسی نمی‌دانست.","two adults in their thirties shrugging at a notice"),
 ("coincidence","noun","/kəʊˈɪnsɪdəns/","اتفاق هم‌زمان","It was a strange coincidence.","اتفاق هم‌زمان عجیبی بود.","two identical objects appearing unexpectedly side by side"),
 ("unusual","adjective","/ʌnˈjuːʒuəl/","غیرعادی","It was an unusual day.","روز غیرعادی‌ای بود.","an empty street at what should be a busy hour"),
 ("dramatic","adjective","/drəˈmætɪk/","پرهیجان","It wasn't very dramatic.","خیلی پرهیجان نبود.","a calm scene after a small commotion"),
 ("unexpected","adjective","/ˌʌnɪkˈspektɪd/","غیرمنتظره","The ending was unexpected.","پایانش غیرمنتظره بود.","a woman in her early thirties reacting with visible surprise"),
 ("to be honest","phrase","/tə bi ˈɒnɪst/","راستش را بخواهی","To be honest, I was scared.","راستش را بخواهی ترسیده بودم.","a man in his early thirties speaking frankly with an open gesture"),
 ("as far as I know","phrase","/əz fɑːr əz aɪ nəʊ/","تا جایی که می‌دانم","As far as I know, it's fine.","تا جایی که می‌دانم مشکلی نیست.","a person in their thirties speaking with a measured, careful gesture"),
 ("point of view","phrase","/pɔɪnt əv vjuː/","دیدگاه","From my point of view, it was fair.","از دید من منصفانه بود.","two adults in their thirties seated opposite each other in discussion"),
 ("looking back","phrase","/ˈlʊkɪŋ bæk/","به گذشته که نگاه می‌کنم","Looking back, it was funny.","به گذشته که نگاه می‌کنم بامزه بود.","a woman in her early thirties smiling at an old photograph"),
]

V[6] = [
 ("by the time","phrase","/baɪ ðə taɪm/","تا وقتی که","By the time we arrived, it had closed.","تا وقتی رسیدیم بسته بود.","a closed shop door with a person arriving outside"),
 ("as soon as","phrase","/əz suːn əz/","به‌محض اینکه","As soon as I heard, I called.","به‌محض اینکه شنیدم زنگ زدم.","a man in his early thirties reaching for a phone quickly"),
 ("until","conjunction","/ənˈtɪl/","تا اینکه","We waited until it stopped.","صبر کردیم تا بند آمد.","two adults in their thirties sheltering as rain eases"),
 ("schedule","noun","/ˈʃedjuːl/","برنامه زمانی","The schedule was changed.","برنامه زمانی عوض شد.","a printed timetable on a wall"),
 ("appointment","noun","/əˈpɔɪntmənt/","قرار ملاقات","I missed my appointment.","قرار ملاقاتم را از دست دادم.","an empty waiting-room chair beside a reception desk"),
 ("traffic jam","phrase","/ˈtræfɪk dʒæm/","راه‌بندان","We were stuck in a traffic jam.","در راه‌بندان گیر کرده بودیم.","a long line of stationary cars on a road"),
 ("rush","verb","/rʌʃ/","عجله کردن","We rushed to the station.","با عجله به ایستگاه رفتیم.","two adults in their thirties hurrying with bags"),
 ("miss","verb","/mɪs/","از دست دادن","We missed the train.","قطار را از دست دادیم.","a train pulling away from an empty platform"),
 ("catch","verb","/kætʃ/","رسیدن به","We just caught the bus.","به‌زحمت به اتوبوس رسیدیم.","a person in their thirties stepping onto a bus as doors close"),
 ("postpone","verb","/pəˈspəʊn/","به تعویق انداختن","The meeting was postponed.","جلسه به تعویق افتاد.","a hand moving a marked note to a later calendar square"),
 ("cancel","verb","/ˈkænsl/","لغو کردن","They cancelled the flight.","پرواز را لغو کردند.","an airport board with an empty gate area"),
 ("arrange","verb","/əˈreɪndʒ/","ترتیب دادن","I arranged another time.","وقت دیگری ترتیب دادم.","a woman in her early thirties writing in a planner"),
 ("in advance","phrase","/ɪn ədˈvɑːns/","از پیش","Book it in advance.","از پیش رزروش کن.","a calendar with a future date marked"),
 ("on time","phrase","/ɒn taɪm/","سر وقت","She's always on time.","همیشه سر وقت است.","a woman in her early thirties arriving as a clock strikes the hour"),
 ("last minute","phrase","/lɑːst ˈmɪnɪt/","دقیقه آخر","It was a last-minute change.","تغییر دقیقه آخری بود.","a man in his early thirties quickly rewriting a note"),
 ("ahead of","phrase","/əˈhed əv/","جلوتر از","We finished ahead of time.","زودتر از موعد تمام کردیم.","a completed task set aside with a clock showing time to spare"),
 ("behind schedule","phrase","/bɪˈhaɪnd ˈʃedjuːl/","عقب از برنامه","We're behind schedule.","از برنامه عقبیم.","a partly finished project with a marked calendar nearby"),
 ("urgent","adjective","/ˈɜːdʒənt/","فوری","It's an urgent matter.","موضوع فوری‌ای است.","a folder placed prominently on top of a pile"),
 ("punctual","adjective","/ˈpʌŋktʃuəl/","وقت‌شناس","He's a punctual person.","آدم وقت‌شناسی است.","a man in his early thirties glancing at a watch while waiting"),
 ("eventually arrive","phrase","/ɪˈventʃuəli əˈraɪv/","سرانجام رسیدن","We eventually arrived.","سرانجام رسیدیم.","two adults in their thirties reaching a doorway with relief"),
]

V[7] = [
 ("claim","verb","/kleɪm/","ادعا کردن","He claimed he had finished.","ادعا کرد تمامش کرده بود.","a man in his early thirties speaking with a firm gesture"),
 ("admit","verb","/ədˈmɪt/","اعتراف کردن","She admitted she had forgotten.","اعتراف کرد فراموش کرده بود.","a woman in her early thirties speaking with a candid expression"),
 ("deny","verb","/dɪˈnaɪ/","انکار کردن","He denied everything.","همه‌چیز را انکار کرد.","a man in his early thirties shaking his head firmly"),
 ("insist","verb","/ɪnˈsɪst/","اصرار کردن","She insisted she was right.","اصرار داشت حق با اوست.","a woman in her early thirties repeating a point with a firm hand"),
 ("mention","verb","/ˈmenʃn/","اشاره کردن","He mentioned it yesterday.","دیروز به آن اشاره کرد.","a man in his early thirties gesturing back to an earlier remark"),
 ("confirm","verb","/kənˈfɜːm/","تأیید کردن","She confirmed she had sent it.","تأیید کرد فرستاده بود.","a woman in her early thirties nodding at a screen"),
 ("assume","verb","/əˈsjuːm/","فرض کردن","I assumed you knew.","فرض کردم می‌دانی.","a man in his early thirties looking surprised at new information"),
 ("statement","noun","/ˈsteɪtmənt/","اظهار","He made a short statement.","اظهار کوتاهی کرد.","a person in their thirties speaking to a small attentive group"),
 ("evidence","noun","/ˈevɪdəns/","شواهد","There was no evidence.","شاهدی نبود.","an empty evidence tray on a plain table"),
 ("rumour","noun","/ˈruːmə/","شایعه","It was just a rumour.","فقط شایعه بود.","two adults in their thirties whispering in a corridor"),
 ("fact","noun","/fækt/","واقعیت","Let's stick to the facts.","بیا به واقعیت‌ها بچسبیم.","a marked line on a clear printed page"),
 ("source","noun","/sɔːs/","منبع","Who was the source?","منبعش چه کسی بود؟","a person in their thirties handing over a folded note"),
 ("according to","phrase","/əˈkɔːdɪŋ tuː/","به گفته","According to him, it's finished.","به گفته او تمام شده.","a man in his early thirties relaying information to another"),
 ("in fact","phrase","/ɪn fækt/","در واقع","In fact, it wasn't true.","در واقع درست نبود.","a woman in her early thirties correcting a note on a page"),
 ("as a result","phrase","/əz ə rɪˈzʌlt/","در نتیجه","As a result, we lost time.","در نتیجه وقت از دست دادیم.","a clock beside an unfinished task"),
 ("misleading","adjective","/mɪsˈliːdɪŋ/","گمراه‌کننده","The report was misleading.","گزارش گمراه‌کننده بود.","a signpost pointing in an unhelpful direction"),
 ("accurate","adjective","/ˈækjərət/","دقیق","The figures are accurate.","ارقام دقیق‌اند.","a precise measuring instrument on a bench"),
 ("reliable source","phrase","/rɪˈlaɪəbl sɔːs/","منبع موثق","It came from a reliable source.","از منبع موثقی آمد.","a stamped official-looking document on a desk"),
 ("word for word","phrase","/wɜːd fə wɜːd/","کلمه به کلمه","He repeated it word for word.","کلمه به کلمه تکرارش کرد.","a person in their thirties reading aloud from a written page"),
 ("clear up","phrase","/klɪər ʌp/","روشن کردن","We cleared up the confusion.","سوءتفاهم را روشن کردیم.","two adults in their thirties reaching an understanding across a table"),
]

V[8] = [
 ("afford","verb","/əˈfɔːd/","توان مالی داشتن","If I could afford it, I'd buy it.","اگر توانش را داشتم می‌خریدم.","a person in their thirties looking thoughtfully at an expensive item"),
 ("imagine","verb","/ɪˈmædʒɪn/","تصور کردن","Imagine you had a year off.","تصور کن یک سال مرخصی داشتی.","a woman in her early thirties gazing thoughtfully out of a window"),
 ("consider","verb","/kənˈsɪdə/","در نظر گرفتن","I'd consider moving.","نقل مکان را در نظر می‌گرفتم.","a man in his early thirties weighing two options on a page"),
 ("prefer","verb","/prɪˈfɜː/","ترجیح دادن","I'd prefer to stay.","ترجیح می‌دادم بمانم.","a woman in her early thirties choosing between two paths"),
 ("choice","noun","/tʃɔɪs/","انتخاب","It's a difficult choice.","انتخاب سختی است.","two doors side by side, both closed"),
 ("opportunity","noun","/ˌɒpəˈtjuːnəti/","فرصت","It's a rare opportunity.","فرصت کمیابی است.","an open door with light beyond it"),
 ("risk","noun","/rɪsk/","ریسک","There's always a risk.","همیشه ریسکی هست.","a narrow bridge over a gap"),
 ("benefit","noun","/ˈbenɪfɪt/","سود، فایده","The benefits are clear.","فایده‌هایش روشن است.","a simple chart with a clearly rising line"),
 ("freedom","noun","/ˈfriːdəm/","آزادی","I'd have more freedom.","آزادی بیشتری داشتم.","a person in their thirties walking an open road at sunrise"),
 ("abroad","adverb","/əˈbrɔːd/","خارج از کشور","If I lived abroad, I'd travel more.","اگر خارج زندگی می‌کردم بیشتر سفر می‌کردم.","a traveller in their thirties looking at a departures area"),
 ("wealthy","adjective","/ˈwelθi/","ثروتمند","If I were wealthy, I'd help others.","اگر ثروتمند بودم به بقیه کمک می‌کردم.","a person in their thirties handing a package to someone in need"),
 ("realistic","adjective","/ˌrɪəˈlɪstɪk/","واقع‌بینانه","Let's be realistic.","بیا واقع‌بین باشیم.","two adults in their thirties reviewing figures on a page"),
 ("possible","adjective","/ˈpɒsəbl/","ممکن","It's possible but hard.","ممکن است اما سخت.","a steep but visible path up a hill"),
 ("impossible","adjective","/ɪmˈpɒsəbl/","ناممکن","That's almost impossible.","تقریباً ناممکن است.","a path blocked by a high wall"),
 ("in your place","phrase","/ɪn jɔː pleɪs/","جای تو","If I were in your place, I'd wait.","جای تو بودم صبر می‌کردم.","two adults in their thirties talking seriously across a table"),
 ("what if","phrase","/wɒt ɪf/","اگر … چه","What if it doesn't work?","اگر جواب ندهد چه؟","a woman in her early thirties looking uncertainly at a plan"),
 ("otherwise","adverb","/ˈʌðəwaɪz/","وگرنه","Hurry, otherwise we'd be late.","عجله کن، وگرنه دیر می‌شد.","two adults in their thirties hurrying toward a closing door"),
 ("chance","noun","/tʃɑːns/","شانس، احتمال","There's a good chance.","احتمالش خوب است.","a coin resting on a table"),
 ("decision","noun","/dɪˈsɪʒn/","تصمیم","It was a big decision.","تصمیم بزرگی بود.","a person in their thirties signing a document with care"),
 ("regret","noun","/rɪˈɡret/","پشیمانی","I have no regrets.","پشیمان نیستم.","a man in his early thirties looking back calmly at a path taken"),
]

V[9] = [
 ("wish","verb","/wɪʃ/","آرزو کردن","I wish I knew the answer.","کاش جواب را می‌دانستم.","a woman in her early thirties looking thoughtfully at an unfinished page"),
 ("miss someone","phrase","/mɪs ˈsʌmwʌn/","دلتنگ کسی بودن","I miss my old team.","دلتنگ تیم قدیمم هستم.","a man in his early thirties looking at a group photograph"),
 ("lonely","adjective","/ˈləʊnli/","تنها","The first month was lonely.","ماه اول تنها بودم.","a single person seated in a large empty room"),
 ("homesick","adjective","/ˈhəʊmsɪk/","دلتنگ خانه","I felt homesick.","دلتنگ خانه بودم.","a person in their thirties looking at a framed family photo"),
 ("grateful","adjective","/ˈɡreɪtfl/","سپاسگزار","I'm grateful for the help.","بابت کمک سپاسگزارم.","a woman in her early thirties receiving help with a warm expression"),
 ("disappointed","adjective","/ˌdɪsəˈpɔɪntɪd/","ناامید","I was disappointed.","ناامید شدم.","a man in his early thirties looking down at a closed folder"),
 ("frustrated","adjective","/frʌˈstreɪtɪd/","کلافه","She felt frustrated.","کلافه شده بود.","a woman in her early thirties rubbing her temples at a desk"),
 ("relieved","adjective","/rɪˈliːvd/","آسوده","I was relieved to hear it.","از شنیدنش آسوده شدم.","a man in his early thirties exhaling with a relaxed smile"),
 ("guilty","adjective","/ˈɡɪlti/","احساس گناه","I felt guilty about it.","درباره‌اش احساس گناه کردم.","a person in their thirties looking away uncomfortably"),
 ("proud of","phrase","/praʊd əv/","به … افتخار کردن","I'm proud of the team.","به تیم افتخار می‌کنم.","adults in their thirties applauding a colleague"),
 ("if only","phrase","/ɪf ˈəʊnli/","کاش","If only I had more time.","کاش وقت بیشتری داشتم.","a clock beside an unfinished piece of work"),
 ("mistake","noun","/mɪˈsteɪk/","اشتباه","It was my mistake.","اشتباه من بود.","a corrected line on a written page"),
 ("advice","noun","/ədˈvaɪs/","نصیحت","I wish I'd taken his advice.","کاش نصیحتش را گوش کرده بودم.","two adults in their thirties, one listening carefully"),
 ("support","noun","/səˈpɔːt/","حمایت","I had a lot of support.","حمایت زیادی داشتم.","colleagues in their thirties standing together"),
 ("second chance","phrase","/ˈsekənd tʃɑːns/","فرصت دوم","Everyone deserves a second chance.","هرکسی فرصت دوم را سزاوار است.","a door reopening onto a lit room"),
 ("move on","phrase","/muːv ɒn/","گذشتن از","It's time to move on.","وقتش است از آن بگذریم.","a person in their thirties walking forward along a clear path"),
 ("get over","phrase","/ɡet ˈəʊvə/","کنار آمدن با","She got over it quickly.","سریع با آن کنار آمد.","a woman in her early thirties smiling again after a difficult moment"),
 ("look forward to","phrase","/lʊk ˈfɔːwəd tuː/","مشتاق … بودن","I look forward to next year.","مشتاق سال آینده‌ام.","a person in their thirties looking toward a bright horizon"),
 ("cheer up","phrase","/tʃɪər ʌp/","روحیه دادن","He cheered me up.","به من روحیه داد.","one adult in their thirties making another laugh"),
 ("emotion","noun","/ɪˈməʊʃn/","احساس","It's normal to show emotion.","نشان دادن احساس طبیعی است.","two adults in their thirties in an open honest conversation"),
]

V[10] = [
 ("situation","noun","/ˌsɪtʃuˈeɪʃn/","موقعیت","It's a difficult situation.","موقعیت دشواری است.","two adults in their thirties in a serious discussion"),
 ("option","noun","/ˈɒpʃn/","گزینه","We have three options.","سه گزینه داریم.","three doors side by side"),
 ("solution","noun","/səˈluːʃn/","راه‌حل","We found a solution.","راه‌حلی پیدا کردیم.","two adults in their thirties looking satisfied at a finished diagram"),
 ("advantage","noun","/ədˈvɑːntɪdʒ/","مزیت","The main advantage is speed.","مزیت اصلی سرعت است.","a simple chart with one bar clearly higher"),
 ("disadvantage","noun","/ˌdɪsədˈvɑːntɪdʒ/","عیب","The disadvantage is cost.","عیبش هزینه است.","a price tag beside a favoured item"),
 ("priority","noun","/praɪˈɒrəti/","اولویت","Safety is the priority.","ایمنی اولویت است.","a marked first item at the top of a plain list"),
 ("compromise","noun","/ˈkɒmprəmaɪz/","سازش","We reached a compromise.","به سازش رسیدیم.","two adults in their thirties shaking hands over a shared page"),
 ("alternative","noun","/ɔːlˈtɜːnətɪv/","جایگزین","Is there an alternative?","جایگزینی هست؟","a second path branching from a main road"),
 ("consequence","noun","/ˈkɒnsɪkwəns/","پیامد","Think about the consequences.","به پیامدها فکر کن.","dominoes standing in a line, one tipping"),
 ("depend on","phrase","/dɪˈpend ɒn/","بستگی داشتن به","It depends on the budget.","به بودجه بستگی دارد.","a balance scale with unequal weights"),
 ("weigh up","phrase","/weɪ ʌp/","سبک و سنگین کردن","Let's weigh up the options.","بیا گزینه‌ها را سبک و سنگین کنیم.","a two-pan balance holding two different items"),
 ("go ahead","phrase","/ɡəʊ əˈhed/","پیش رفتن","We decided to go ahead.","تصمیم گرفتیم پیش برویم.","a person in their thirties stepping forward through a doorway"),
 ("back out","phrase","/bæk aʊt/","عقب کشیدن","They backed out at the end.","آخر کار عقب کشیدند.","a person in their thirties stepping back from a table"),
 ("worth it","phrase","/wɜːθ ɪt/","ارزشش را داشتن","It wasn't worth it.","ارزشش را نداشت.","a man in his early thirties looking doubtfully at a purchase"),
 ("in theory","phrase","/ɪn ˈθɪəri/","در تئوری","In theory, it works.","در تئوری جواب می‌دهد.","a clean diagram drawn on a whiteboard"),
 ("in practice","phrase","/ɪn ˈpræktɪs/","در عمل","In practice, it's harder.","در عمل سخت‌تر است.","a workbench with a partly assembled device"),
 ("reasonable","adjective","/ˈriːznəbl/","معقول","That sounds reasonable.","معقول به‌نظر می‌رسد.","two adults in their thirties nodding across a table"),
 ("risky","adjective","/ˈrɪski/","پرخطر","It's a risky plan.","برنامه پرخطری است.","a narrow plank across a gap"),
 ("sensible","adjective","/ˈsensəbl/","عاقلانه","It's the sensible choice.","انتخاب عاقلانه‌ای است.","a person in their thirties choosing the clearer of two paths"),
 ("either way","phrase","/ˈaɪðə weɪ/","در هر صورت","Either way, we'll manage.","در هر صورت از پسش برمی‌آییم.","a fork in a path with both branches clear"),
]
