# -*- coding: utf-8 -*-
"""
واژگان دروس ۲۱ تا ۳۰ سطح A2 — مدال‌ها، درخواست، و بسته‌بندی سطح.

نیمه دوم A2 از گرامرِ توصیفی به گرامرِ کارکردی می‌رود: توصیه، الزام،
ممنوعیت، درخواست مؤدبانه. این‌ها واژه‌های موقعیتی می‌خواهند (پزشکی،
هتل، علائم)، نه واژه‌های انتزاعی — چون کاربر باید بتواند همان روز
در یک موقعیت واقعی از آن‌ها استفاده کند.
"""

V = {}

V[21] = [
 ("should","modal","/ʃʊd/","باید (توصیه)","You should rest.","باید استراحت کنی.","a man in his early thirties resting on a sofa with a blanket"),
 ("must","modal","/mʌst/","باید (الزام)","I must finish this today.","امروز باید این را تمام کنم.","a woman in her early thirties working with focused urgency at a desk"),
 ("have to","phrase","/ˈhæv tuː/","مجبور بودن","I have to work tomorrow.","فردا مجبورم کار کنم.","a man in his early thirties putting on a coat early in the morning"),
 ("advice","noun","/ədˈvaɪs/","نصیحت","Thanks for the advice.","بابت نصیحتت ممنون.","two adults in their thirties talking, one listening attentively"),
 ("headache","noun","/ˈhedeɪk/","سردرد","I have a headache.","سردرد دارم.","a woman in her early thirties pressing her fingers to her temple"),
 ("fever","noun","/ˈfiːvə/","تب","She has a fever.","تب دارد.","a hand holding a thermometer near a resting person"),
 ("rest","verb","/rest/","استراحت کردن","You need to rest.","باید استراحت کنی.","a man in his early thirties lying back with his eyes closed"),
 ("medicine","noun","/ˈmedsn/","دارو","Take this medicine twice a day.","این دارو را روزی دو بار بخور.","a small unlabelled medicine box beside a glass of water"),
 ("pain","noun","/peɪn/","درد","I feel a pain here.","اینجا درد می‌کند.","a man in his early thirties holding his shoulder with a pained look"),
 ("healthy","adjective","/ˈhelθi/","سالم","Try to eat healthy food.","سعی کن غذای سالم بخوری.","a plate of fresh vegetables and fruit"),
 ("tired","adjective","/ˈtaɪəd/","خسته","You look tired.","خسته به نظر می‌رسی.","a woman in her early thirties rubbing her eyes at a desk"),
 ("exercise","noun","/ˈeksəsaɪz/","ورزش","Exercise is important.","ورزش مهم است.","a man in his early thirties stretching in a park"),
 ("sleep","noun","/sliːp/","خواب","You need more sleep.","به خواب بیشتری نیاز داری.","a tidy bed in a softly lit bedroom"),
 ("diet","noun","/ˈdaɪət/","رژیم غذایی","You should change your diet.","باید رژیم غذایی‌ات را عوض کنی.","a plate of simple balanced food beside a glass of water"),
 ("stress","noun","/stres/","استرس","Too much stress is bad.","استرس زیاد بد است.","a woman in her early thirties with a tense expression at a full desk"),
 ("relax","verb","/rɪˈlæks/","آرام گرفتن","Try to relax.","سعی کن آرام باشی.","a man in his early thirties sitting calmly with a cup of tea"),
 ("careful with","phrase","/ˈkeəfl wɪð/","مراقب … بودن","Be careful with the stairs.","مراقب پله‌ها باش.","a hand on a stair rail seen from above"),
 ("better soon","phrase","/ˈbetə suːn/","زودتر خوب شدن","Get better soon.","زود خوب شو.","a small get-well card beside a bunch of flowers"),
 ("serious problem","phrase","/ˈsɪəriəs ˈprɒbləm/","مشکل جدی","It isn't a serious problem.","مشکل جدی‌ای نیست.","a doctor in their thirties reassuring a seated patient"),
 ("appointment card","phrase","/əˈpɔɪntmənt kɑːd/","کارت نوبت","Keep the appointment card.","کارت نوبت را نگه دار.","a small blank card held between two fingers"),
]

V[22] = [
 ("mustn't","modal","/ˈmʌsnt/","نباید (ممنوع)","You mustn't park here.","اینجا نباید پارک کنی.","a no-parking symbol painted on a kerb"),
 ("can't","modal","/kɑːnt/","نمی‌شود","You can't enter here.","اینجا نمی‌شود وارد شد.","a closed gate with a barrier across it"),
 ("allowed","adjective","/əˈlaʊd/","مجاز","Photos aren't allowed.","عکس گرفتن مجاز نیست.","a crossed-out camera symbol on a wall"),
 ("forbidden","adjective","/fəˈbɪdn/","ممنوع","Smoking is forbidden here.","سیگار کشیدن اینجا ممنوع است.","a crossed-out cigarette symbol at an entrance"),
 ("rule","noun","/ruːl/","قانون، قاعده","These are the rules.","این‌ها قوانین‌اند.","a plain notice board with several blank lines"),
 ("instruction","noun","/ɪnˈstrʌkʃn/","دستورالعمل","Follow the instructions.","دستورالعمل‌ها را دنبال کن.","a plain printed sheet with numbered lines on a wall"),
 ("warning","noun","/ˈwɔːnɪŋ/","هشدار","That's a warning sign.","آن تابلوی هشدار است.","a triangular warning symbol on a pole"),
 ("entrance","noun","/ˈentrəns/","ورودی","The entrance is over there.","ورودی آن طرف است.","an open doorway at the front of a building"),
 ("exit","noun","/ˈeksɪt/","خروجی","Where's the exit?","خروجی کجاست؟","a lit exit doorway at the end of a corridor"),
 ("permission","noun","/pəˈmɪʃn/","اجازه","You need permission first.","اول باید اجازه بگیری.","a man in his early thirties raising a hand to ask"),
 ("fine","noun","/faɪn/","جریمه","There's a fine for that.","برایش جریمه هست.","a printed slip tucked under a car's windscreen wiper"),
 ("park","verb","/pɑːk/","پارک کردن","Don't park on the corner.","سر نبش پارک نکن.","a car parked neatly between two lines"),
 ("touch","verb","/tʌtʃ/","دست زدن","Please don't touch this.","لطفاً به این دست نزن.","a hand held back from a display case"),
 ("enter","verb","/ˈentə/","وارد شدن","Don't enter without knocking.","بدون در زدن وارد نشو.","a closed office door with a hand about to knock"),
 ("wait here","phrase","/weɪt hɪə/","اینجا منتظر بمان","Please wait here.","لطفاً اینجا منتظر بمان.","a marked waiting area with two chairs"),
 ("quiet zone","phrase","/ˈkwaɪət zəʊn/","محدوده سکوت","This is a quiet zone.","اینجا محدوده سکوت است.","a library reading room with people seated silently"),
 ("public","adjective","/ˈpʌblɪk/","عمومی","It's a public building.","ساختمان عمومی است.","a wide entrance hall with people walking through"),
 ("private","adjective","/ˈpraɪvət/","خصوصی","This area is private.","این محوطه خصوصی است.","a gated path leading to a house"),
 ("safety","noun","/ˈseɪfti/","ایمنی","It's for your safety.","برای ایمنی خودت است.","a safety helmet resting on a bench"),
 ("emergency","noun","/ɪˈmɜːdʒənsi/","اضطراری","Use it only in an emergency.","فقط در مواقع اضطراری استفاده کن.","a red emergency box mounted on a wall"),
]

V[23] = [
 ("could","modal","/kʊd/","می‌شود (درخواست)","Could you help me?","می‌شود کمکم کنی؟","a woman in her early thirties asking for help with a polite gesture"),
 ("would","modal","/wʊd/","می‌شود، مایل بودن","Would you wait a moment?","می‌شود لحظه‌ای صبر کنی؟","a man in his early thirties gesturing politely for someone to pause"),
 ("mind","verb","/maɪnd/","ناراحت شدن","Would you mind waiting?","اشکالی ندارد صبر کنید؟","two adults in their thirties speaking politely at a counter"),
 ("request","noun","/rɪˈkwest/","درخواست","I have a small request.","درخواست کوچکی دارم.","a woman in her early thirties speaking to a receptionist"),
 ("grateful","adjective","/ˈɡreɪtfl/","سپاسگزار","I'm very grateful.","خیلی سپاسگزارم.","a woman in her early thirties receiving help with a warm expression"),
 ("borrow","verb","/ˈbɒrəʊ/","قرض گرفتن","Could I borrow your pen?","می‌شود خودکارت را قرض بگیرم؟","a hand reaching to accept an offered pen"),
 ("lend","verb","/lend/","قرض دادن","Could you lend me a chair?","می‌شود صندلی‌ای به من قرض بدهی؟","one adult in their thirties passing a chair to another"),
 ("pass","verb","/pɑːs/","دادن، رد کردن","Could you pass the salt?","می‌شود نمک را بدهی؟","a hand passing a small dish across a table"),
 ("hold","verb","/həʊld/","نگه داشتن","Could you hold this?","می‌شود این را نگه داری؟","a person handing a box to someone with both hands"),
 ("speak up","phrase","/spiːk ʌp/","بلندتر صحبت کردن","Could you speak up, please?","می‌شود بلندتر صحبت کنید؟","a man in his early thirties leaning forward to listen"),
 ("slow down","phrase","/sləʊ daʊn/","آهسته‌تر کردن","Could you slow down a bit?","می‌شود کمی آهسته‌تر بگویید؟","a woman in her early thirties raising a hand in a gentle pause gesture"),
 ("no problem","phrase","/nəʊ ˈprɒbləm/","مشکلی نیست","No problem at all.","اصلاً مشکلی نیست.","a man in his early thirties smiling with an open welcoming gesture"),
 ("certainly","adverb","/ˈsɜːtnli/","حتماً","Certainly, one moment.","حتماً، یک لحظه.","a receptionist in their thirties nodding helpfully"),
 ("polite","adjective","/pəˈlaɪt/","مؤدب","He's very polite.","خیلی مؤدب است.","a man in his early thirties holding a door open for someone"),
 ("formal","adjective","/ˈfɔːml/","رسمی","It's a formal letter.","نامه رسمی‌ای است.","a neatly typed letter on a desk"),
 ("informal","adjective","/ɪnˈfɔːml/","غیررسمی","We can be informal here.","اینجا می‌توانیم راحت باشیم.","two colleagues in their thirties chatting casually with cups of tea"),
 ("apologise","verb","/əˈpɒlədʒaɪz/","عذرخواهی کردن","I apologise for the delay.","بابت تأخیر عذرخواهی می‌کنم.","a man in his early thirties speaking with a regretful open gesture"),
 ("thank you for","phrase","/ˈθæŋk juː fə/","ممنون بابت","Thank you for your help.","ممنون بابت کمکت.","two adults in their thirties shaking hands warmly"),
 ("excuse me","phrase","/ɪkˈskjuːz miː/","ببخشید","Excuse me, could I ask something?","ببخشید، می‌شود چیزی بپرسم؟","a woman in her early thirties approaching a desk with a raised hand"),
 ("of course not","phrase","/əv kɔːs nɒt/","اصلاً","Of course not, go ahead.","اصلاً، بفرمایید.","a man in his early thirties gesturing welcomingly toward a chair"),
]

V[24] = [
 ("would like","phrase","/wʊd laɪk/","مایل بودن","I'd like to book a room.","مایلم اتاقی رزرو کنم.","a traveller in their thirties speaking at a hotel reception"),
 ("reservation","noun","/ˌrezəˈveɪʃn/","رزرو","I have a reservation.","رزرو دارم.","a reception desk with a small open register"),
 ("single room","phrase","/ˈsɪŋɡl ruːm/","اتاق یک‌نفره","A single room, please.","یک اتاق یک‌نفره، لطفاً.","a simple hotel room with one bed"),
 ("double room","phrase","/ˈdʌbl ruːm/","اتاق دونفره","We'd like a double room.","اتاق دونفره می‌خواهیم.","a hotel room with a wide bed and two side tables"),
 ("night","noun","/naɪt/","شب","For three nights, please.","برای سه شب، لطفاً.","a hotel window showing a city at night"),
 ("floor","noun","/flɔː/","طبقه","It's on the third floor.","طبقه سوم است.","a lift panel with numbered buttons"),
 ("key","noun","/kiː/","کلید","Here's your key.","این کلید شماست.","a hand passing a room key across a counter"),
 ("luggage","noun","/ˈlʌɡɪdʒ/","چمدان","Where can I leave my luggage?","چمدانم را کجا بگذارم؟","two suitcases standing beside a reception desk"),
 ("reception","noun","/rɪˈsepʃn/","پذیرش","Ask at reception.","از پذیرش بپرس.","a hotel reception counter with a member of staff in their thirties"),
 ("check in","phrase","/tʃek ɪn/","تحویل گرفتن اتاق","We'd like to check in.","می‌خواهیم اتاق تحویل بگیریم.","a traveller in their thirties signing at a hotel desk"),
 ("check out","phrase","/tʃek aʊt/","تخلیه اتاق","Check out is at noon.","تخلیه اتاق ظهر است.","a suitcase by an open hotel room door"),
 ("included","adjective","/ɪnˈkluːdɪd/","شامل","Is breakfast included?","صبحانه شامل می‌شود؟","a simple breakfast tray on a table"),
 ("service","noun","/ˈsɜːvɪs/","خدمات","The service was excellent.","خدمات عالی بود.","a member of staff in their thirties carrying a tray"),
 ("bill","noun","/bɪl/","صورت‌حساب","Could I have the bill?","می‌شود صورت‌حساب را بدهید؟","a small folder with a printed slip on a table"),
 ("towel","noun","/ˈtaʊəl/","حوله","Could we have more towels?","می‌شود حوله بیشتری بدهید؟","folded towels stacked on a shelf"),
 ("view","noun","/vjuː/","منظره","The room has a nice view.","اتاق منظره خوبی دارد.","a window looking out over rooftops"),
 ("noisy","adjective","/ˈnɔɪzi/","پرسروصدا","The room was a bit noisy.","اتاق کمی پرسروصدا بود.","a hotel window facing a busy street"),
 ("comfortable bed","phrase","/ˈkʌmftəbl bed/","تخت راحت","The bed was very comfortable.","تخت خیلی راحت بود.","a neatly made bed with soft pillows"),
 ("complain","verb","/kəmˈpleɪn/","شکایت کردن","I'd like to complain.","می‌خواهم شکایت کنم.","a guest in their thirties speaking seriously at a reception desk"),
 ("recommend","verb","/ˌrekəˈmend/","پیشنهاد کردن","Can you recommend a restaurant?","می‌توانید رستورانی پیشنهاد کنید؟","a member of staff in their thirties pointing at a map for a guest"),
]

V[25] = [
 ("symptom","noun","/ˈsɪmptəm/","علامت بیماری","Describe your symptoms.","علائمت را توصیف کن.","a patient in their thirties speaking to a doctor across a desk"),
 ("cough","noun","/kɒf/","سرفه","I have a bad cough.","سرفه بدی دارم.","a man in his early thirties covering his mouth with his hand"),
 ("cold","noun","/kəʊld/","سرماخوردگی","I've got a cold.","سرما خورده‌ام.","a woman in her early thirties holding a tissue with a blanket around her"),
 ("flu","noun","/fluː/","آنفلوآنزا","She has the flu.","آنفلوآنزا گرفته.","a person resting in bed with a cup on the side table"),
 ("prescription","noun","/prɪˈskrɪpʃn/","نسخه","Here's your prescription.","این نسخه شماست.","a doctor in their thirties handing a small sheet to a patient"),
 ("pharmacy","noun","/ˈfɑːməsi/","داروخانه","The pharmacy is next door.","داروخانه کنارش است.","shelves of unlabelled medicine boxes behind a counter"),
 ("nurse","noun","/nɜːs/","پرستار","The nurse will see you.","پرستار شما را می‌بیند.","a nurse in their thirties preparing a blood-pressure cuff"),
 ("treatment","noun","/ˈtriːtmənt/","درمان","The treatment takes a week.","درمان یک هفته طول می‌کشد.","a doctor in their thirties explaining a plan to a seated person"),
 ("injury","noun","/ˈɪndʒəri/","آسیب","It's a small injury.","آسیب کوچکی است.","a bandaged hand resting on a table"),
 ("blood","noun","/blʌd/","خون","They took a blood test.","آزمایش خون گرفتند.","a small sealed sample tube on a tray"),
 ("test","noun","/test/","آزمایش","The test result was fine.","نتیجه آزمایش خوب بود.","a folded report sheet on a clinic desk"),
 ("hurt","verb","/hɜːt/","درد کردن","My back hurts.","کمرم درد می‌کند.","a man in his early thirties pressing a hand to his lower back"),
 ("feel","verb","/fiːl/","احساس کردن","I feel much better.","خیلی بهتر احساس می‌کنم.","a woman in her early thirties looking relieved and rested"),
 ("breathe","verb","/briːð/","نفس کشیدن","Breathe slowly, please.","لطفاً آهسته نفس بکش.","a doctor in their thirties holding a stethoscope to a patient's back"),
 ("recover","verb","/rɪˈkʌvə/","بهبود یافتن","He recovered quickly.","سریع بهبود یافت.","a man in his early thirties walking outdoors looking well"),
 ("check-up","noun","/ˈtʃekʌp/","معاینه","I have a check-up today.","امروز معاینه دارم.","a doctor in their thirties writing while a patient sits nearby"),
 ("insurance","noun","/ɪnˈʃʊərəns/","بیمه","Do you have insurance?","بیمه دارید؟","a plain card being handed across a clinic counter"),
 ("clinic","noun","/ˈklɪnɪk/","درمانگاه","The clinic opens at eight.","درمانگاه هشت باز می‌شود.","a small clinic entrance with a bench outside"),
 ("ambulance","noun","/ˈæmbjələns/","آمبولانس","Call an ambulance!","آمبولانس خبر کن!","an ambulance parked outside a hospital entrance"),
 ("get well","phrase","/ɡet wel/","خوب شدن","I hope you get well.","امیدوارم خوب شوی.","a small card and flowers on a bedside table"),
]

V[26] = [
 ("enjoy","verb","/ɪnˈdʒɔɪ/","لذت بردن","I enjoy reading.","از کتاب خواندن لذت می‌برم.","a woman in her early thirties reading contentedly in an armchair"),
 ("avoid","verb","/əˈvɔɪd/","اجتناب کردن","I avoid driving at night.","از رانندگی شبانه اجتناب می‌کنم.","a man in his early thirties choosing a bus over a car at dusk"),
 ("finish doing","phrase","/ˈfɪnɪʃ ˈduːɪŋ/","تمام کردنِ کاری","I finished cleaning.","تمیز کردن را تمام کردم.","a tidy room with cleaning items being put away"),
 ("mind doing","phrase","/maɪnd ˈduːɪŋ/","اشکال داشتنِ کاری","I don't mind waiting.","صبر کردن برایم اشکالی ندارد.","a man in his early thirties waiting calmly with a book"),
 ("decide to","phrase","/dɪˈsaɪd tuː/","تصمیم گرفتن به","I decided to study more.","تصمیم گرفتم بیشتر درس بخوانم.","a woman in her early thirties opening a study book with resolve"),
 ("hope to","phrase","/həʊp tuː/","امیدوار بودن به","I hope to travel soon.","امیدوارم به‌زودی سفر کنم.","a man in his early thirties looking at a wall map"),
 ("learn to","phrase","/lɜːn tuː/","یاد گرفتنِ","I want to learn to swim.","می‌خواهم شنا یاد بگیرم.","an adult in their thirties at the edge of a pool with an instructor"),
 ("hate","verb","/heɪt/","متنفر بودن","I hate waiting in queues.","از صف ایستادن متنفرم.","a long queue of adults waiting at a counter"),
 ("love","verb","/lʌv/","عاشق بودن","I love cooking.","عاشق آشپزی‌ام.","a woman in her early thirties happily preparing food"),
 ("practise","verb","/ˈpræktɪs/","تمرین کردن","I practise every morning.","هر صبح تمرین می‌کنم.","a man in his early thirties repeating an exercise with a notebook"),
 ("hobby","noun","/ˈhɒbi/","سرگرمی","Photography is my hobby.","عکاسی سرگرمی من است.","a camera resting beside printed photographs"),
 ("interest","noun","/ˈɪntrəst/","علاقه","We share the same interests.","علاقه‌های یکسانی داریم.","two adults in their thirties looking at the same book together"),
 ("music","noun","/ˈmjuːzɪk/","موسیقی","I listen to music every day.","هر روز موسیقی گوش می‌دهم.","headphones resting on a wooden table"),
 ("painting","noun","/ˈpeɪntɪŋ/","نقاشی","She's good at painting.","در نقاشی خوب است.","a woman in her early thirties working at an easel"),
 ("swimming","noun","/ˈswɪmɪŋ/","شنا","Swimming is good exercise.","شنا ورزش خوبی است.","calm lane markers in an indoor pool"),
 ("reading","noun","/ˈriːdɪŋ/","کتاب خواندن","Reading helps me relax.","کتاب خواندن آرامم می‌کند.","an open book beside a warm lamp"),
 ("cooking","noun","/ˈkʊkɪŋ/","آشپزی","Cooking takes time.","آشپزی وقت می‌برد.","fresh ingredients arranged on a kitchen counter"),
 ("bored","adjective","/bɔːd/","بی‌حوصله","I get bored easily.","زود بی‌حوصله می‌شوم.","a man in his early thirties resting his chin on his hand"),
 ("keen on","phrase","/kiːn ɒn/","علاقه‌مند به","I'm keen on football.","به فوتبال علاقه‌مندم.","a man in his early thirties watching a match with interest"),
 ("good at","phrase","/ɡʊd ət/","خوب بودن در","She's good at languages.","در زبان‌ها خوب است.","a woman in her early thirties speaking confidently with notes in hand"),
]

V[27] = [
 ("told","verb","/təʊld/","گفت (به کسی)","He told me to wait.","به من گفت صبر کنم.","a man in his early thirties speaking directly to another person"),
 ("said","verb","/sed/","گفت","She said she was busy.","گفت سرش شلوغ است.","a woman in her early thirties speaking while another listens"),
 ("asked","verb","/ɑːskt/","پرسید","He asked where I lived.","پرسید کجا زندگی می‌کنم.","two adults in their thirties in a questioning conversation"),
 ("answered","verb","/ˈɑːnsəd/","پاسخ داد","I answered honestly.","صادقانه پاسخ دادم.","a man in his early thirties replying with an open gesture"),
 ("advised","verb","/ədˈvaɪzd/","توصیه کرد","The doctor advised rest.","دکتر استراحت را توصیه کرد.","a doctor in their thirties speaking to a seated patient"),
 ("warned","verb","/wɔːnd/","هشدار داد","She warned me about the traffic.","درباره ترافیک بهم هشدار داد.","a woman in her early thirties pointing seriously at a road ahead"),
 ("promised to","phrase","/ˈprɒmɪst tuː/","قول داد که","He promised to call.","قول داد زنگ بزند.","two adults in their thirties in a serious handshake"),
 ("refused","verb","/rɪˈfjuːzd/","رد کرد","He refused politely.","مؤدبانه رد کرد.","a man in his early thirties raising a hand in a polite refusal"),
 ("agreed to","phrase","/əˈɡriːd tuː/","موافقت کرد با","They agreed to help.","موافقت کردند کمک کنند.","two adults in their thirties nodding together over a plan"),
 ("explained that","phrase","/ɪkˈspleɪnd ðæt/","توضیح داد که","She explained that it was late.","توضیح داد که دیر شده.","a woman in her early thirties drawing a simple diagram while talking"),
 ("message","noun","/ˈmesɪdʒ/","پیام","I left a message.","پیام گذاشتم.","a folded note left on a desk"),
 ("news","noun","/njuːz/","خبر","I heard good news.","خبر خوبی شنیدم.","two adults in their thirties reacting happily to something shared"),
 ("truth","noun","/truːθ/","حقیقت","Tell me the truth.","حقیقت را بگو.","two adults in their thirties in a direct serious conversation"),
 ("lie","noun","/laɪ/","دروغ","That isn't a lie.","آن دروغ نیست.","a man in his early thirties looking away uncomfortably"),
 ("secret","noun","/ˈsiːkrət/","راز","It's a secret.","راز است.","two adults in their thirties speaking closely and quietly"),
 ("opinion","noun","/əˈpɪnjən/","نظر","What's your opinion?","نظرت چیست؟","two adults in their thirties in a thoughtful discussion"),
 ("according to","phrase","/əˈkɔːdɪŋ tuː/","به گفته","According to Ali, it's closed.","به گفته علی، بسته است.","a man in his early thirties relaying information to another"),
 ("in other words","phrase","/ɪn ˈʌðə wɜːdz/","به عبارت دیگر","In other words, we can't go.","به عبارت دیگر، نمی‌توانیم برویم.","a woman in her early thirties rephrasing something with a clear gesture"),
 ("apparently","adverb","/əˈpærəntli/","ظاهراً","Apparently, it's free.","ظاهراً رایگان است.","two adults in their thirties looking at a notice together"),
 ("exactly what","phrase","/ɪɡˈzæktli wɒt/","دقیقاً همان چیزی که","That's exactly what he said.","دقیقاً همان چیزی است که گفت.","a man in his early thirties confirming with a firm nod"),
]

V[28] = [
 ("too","adverb","/tuː/","بیش از حد","It's too expensive.","بیش از حد گران است.","a price tag beside an item a shopper is putting back"),
 ("enough time","phrase","/ɪˈnʌf taɪm/","وقت کافی","We don't have enough time.","وقت کافی نداریم.","a woman in her early thirties hurrying past a wall clock"),
 ("space","noun","/speɪs/","فضا","There isn't enough space.","فضای کافی نیست.","a crowded shelf with no room left"),
 ("crowd","noun","/kraʊd/","جمعیت","The crowd was too big.","جمعیت خیلی زیاد بود.","a dense group of adults filling a square"),
 ("full","adjective","/fʊl/","پر","The bus is full.","اتوبوس پر است.","a bus with every seat occupied"),
 ("empty","adjective","/ˈempti/","خالی","The room was empty.","اتاق خالی بود.","an empty room with bare walls"),
 ("tight","adjective","/taɪt/","تنگ","These shoes are too tight.","این کفش‌ها خیلی تنگ‌اند.","a person in their thirties struggling to put on a shoe"),
 ("loose","adjective","/luːs/","گشاد","The shirt is too loose.","پیراهن خیلی گشاد است.","a shirt hanging loosely on a hanger"),
 ("strong","adjective","/strɒŋ/","قوی، پررنگ","The tea is too strong.","چای خیلی پررنگ است.","a very dark cup of tea on a saucer"),
 ("weak","adjective","/wiːk/","ضعیف، کم‌رنگ","The signal is weak here.","سیگنال اینجا ضعیف است.","a phone held up near a window"),
 ("hot","adjective","/hɒt/","داغ","The soup is too hot.","سوپ خیلی داغ است.","steam rising from a bowl of soup"),
 ("far enough","phrase","/fɑːr ɪˈnʌf/","به‌اندازه کافی دور","It isn't far enough.","به‌اندازه کافی دور نیست.","two markers a short distance apart on a path"),
 ("fast enough","phrase","/fɑːst ɪˈnʌf/","به‌اندازه کافی سریع","We aren't fast enough.","به‌اندازه کافی سریع نیستیم.","two adults in their thirties hurrying toward a closing door"),
 ("amount","noun","/əˈmaʊnt/","مقدار","That's a large amount.","مقدار زیادی است.","a heaped measuring cup on a counter"),
 ("extra","adjective","/ˈekstrə/","اضافی","We need extra chairs.","صندلی اضافی لازم داریم.","two spare chairs stacked beside a table"),
 ("less","determiner","/les/","کمتر","Use less salt.","نمک کمتری بریز.","a small pinch of salt above a pan"),
 ("more than","phrase","/mɔː ðæn/","بیش از","It costs more than that.","بیشتر از آن هزینه دارد.","two stacks of banknotes of clearly different heights"),
 ("reduce","verb","/rɪˈdjuːs/","کم کردن","We should reduce the cost.","باید هزینه را کم کنیم.","a hand lowering a marker on a simple chart"),
 ("increase","verb","/ɪnˈkriːs/","زیاد کردن","They increased the price.","قیمت را زیاد کردند.","a hand raising a marker on a simple chart"),
 ("fit","verb","/fɪt/","اندازه بودن","These don't fit me.","اندازه‌ام نیست.","a person in their thirties holding a garment against themselves"),
]

V[29] = [
 ("someone","pronoun","/ˈsʌmwʌn/","یک نفر","Someone left this here.","یک نفر این را اینجا گذاشته.","an unattended bag on a bench"),
 ("anyone","pronoun","/ˈeniwʌn/","هیچ‌کس، هرکس","Is anyone there?","کسی آنجاست؟","an empty corridor with an open door at the end"),
 ("no one","pronoun","/ˈnəʊ wʌn/","هیچ‌کس","No one answered.","هیچ‌کس جواب نداد.","a closed door with a hand about to knock again"),
 ("everybody","pronoun","/ˈevribɒdi/","همه","Everybody arrived early.","همه زود رسیدند.","a group of adults in their thirties gathered in a room"),
 ("something","pronoun","/ˈsʌmθɪŋ/","چیزی","I heard something.","چیزی شنیدم.","a woman in her early thirties turning her head to listen"),
 ("anything","pronoun","/ˈeniθɪŋ/","هیچ‌چیز، هر چیزی","I didn't buy anything.","هیچ‌چیز نخریدم.","a person in their thirties leaving a shop empty-handed"),
 ("nothing","pronoun","/ˈnʌθɪŋ/","هیچ‌چیز","There's nothing here.","اینجا هیچ‌چیز نیست.","an empty drawer pulled open"),
 ("everything","pronoun","/ˈevriθɪŋ/","همه‌چیز","Everything is ready.","همه‌چیز آماده است.","a fully set table before guests arrive"),
 ("somewhere","adverb","/ˈsʌmweə/","جایی","I left it somewhere.","جایی گذاشتمش.","a man in his early thirties searching a shelf"),
 ("anywhere","adverb","/ˈeniweə/","هیچ‌جا، هرجا","I can't find it anywhere.","هیچ‌جا پیدایش نمی‌کنم.","a woman in her early thirties looking under furniture"),
 ("nowhere","adverb","/ˈnəʊweə/","هیچ‌جا","There's nowhere to sit.","جایی برای نشستن نیست.","a waiting area with every seat taken"),
 ("everywhere","adverb","/ˈevriweə/","همه‌جا","I looked everywhere.","همه‌جا را گشتم.","a room with drawers and cupboards left open"),
 ("belong","verb","/bɪˈlɒŋ/","متعلق بودن","Does this belong to you?","این مال شماست؟","a hand holding up a found item questioningly"),
 ("notice","verb","/ˈnəʊtɪs/","متوجه شدن","I didn't notice it.","متوجهش نشدم.","a woman in her early thirties glancing back in surprise"),
 ("search","verb","/sɜːtʃ/","جست‌وجو کردن","We searched the whole room.","تمام اتاق را جست‌وجو کردیم.","two adults in their thirties looking through shelves"),
 ("find out","phrase","/faɪnd aʊt/","پی بردن","I'll find out tomorrow.","فردا پی می‌برم.","a man in his early thirties reading a notice closely"),
 ("owner of","phrase","/ˈəʊnər əv/","صاحبِ","Who's the owner of this bag?","صاحب این کیف کیست؟","a bag held up in front of a small group"),
 ("lost property","phrase","/lɒst ˈprɒpəti/","اشیای گمشده","Ask at lost property.","از بخش اشیای گمشده بپرس.","a counter with a shelf of unclaimed items behind it"),
 ("by mistake","phrase","/baɪ mɪˈsteɪk/","اشتباهی","I took it by mistake.","اشتباهی برداشتمش.","two identical bags side by side, one being picked up"),
 ("on purpose","phrase","/ɒn ˈpɜːpəs/","عمداً","He didn't do it on purpose.","عمداً این کار را نکرد.","a man in his early thirties gesturing apologetically"),
]

V[30] = [
 ("progress report","phrase","/ˈprəʊɡres rɪˈpɔːt/","گزارش پیشرفت","Here's my progress report.","این گزارش پیشرفت من است.","a simple chart showing a rising line"),
 ("level","noun","/ˈlevl/","سطح","You've finished this level.","این سطح را تمام کرده‌ای.","a marked step at the top of a short staircase"),
 ("goal","noun","/ɡəʊl/","هدف","What's your next goal?","هدف بعدی‌ات چیست؟","a marked flag at the end of a path"),
 ("achieve","verb","/əˈtʃiːv/","به دست آوردن","You've achieved a lot.","خیلی چیزها به دست آورده‌ای.","a woman in her early thirties looking satisfied at completed work"),
 ("confident","adjective","/ˈkɒnfɪdənt/","با اعتماد به نفس","I feel more confident now.","حالا اعتماد به نفس بیشتری دارم.","a man in his early thirties speaking to a group without notes"),
 ("fluent","adjective","/ˈfluːənt/","روان","She speaks fluent English.","انگلیسی را روان صحبت می‌کند.","a woman in her early thirties in easy conversation with two others"),
 ("practice","noun","/ˈpræktɪs/","تمرین","Practice makes it easier.","تمرین کار را آسان‌تر می‌کند.","a worn notebook filled with repeated written lines"),
 ("mistakes happen","phrase","/mɪˈsteɪks ˈhæpən/","اشتباه پیش می‌آید","Mistakes happen — keep going.","اشتباه پیش می‌آید — ادامه بده.","a man in his early thirties calmly crossing out a line and rewriting"),
 ("step by step","phrase","/step baɪ step/","قدم‌به‌قدم","Learn step by step.","قدم‌به‌قدم یاد بگیر.","a series of stone steps rising gently"),
 ("keep going","phrase","/kiːp ˈɡəʊɪŋ/","ادامه دادن","Keep going, you're close.","ادامه بده، نزدیکی.","a walker in their thirties on a path near a visible summit"),
 ("feedback","noun","/ˈfiːdbæk/","بازخورد","The feedback was positive.","بازخورد مثبت بود.","two adults in their thirties looking together at a marked page"),
 ("summary","noun","/ˈsʌməri/","خلاصه","Here's a short summary.","این یک خلاصه کوتاه است.","a single page with a few short lines on a desk"),
 ("next level","phrase","/nekst ˈlevl/","سطح بعد","You're ready for the next level.","برای سطح بعد آماده‌ای.","an open door leading to a brighter room"),
 ("certificate","noun","/səˈtɪfɪkət/","گواهی","I got a certificate.","گواهی گرفتم.","a plain framed document held in two hands"),
 ("proud","adjective","/praʊd/","سربلند","I'm proud of you.","به تو افتخار می‌کنم.","two adults in their thirties, one congratulating the other"),
 ("challenge","noun","/ˈtʃælɪndʒ/","چالش","It was a real challenge.","چالش واقعی بود.","a man in his early thirties studying a difficult diagram"),
 ("useful phrase","phrase","/ˈjuːsfl freɪz/","عبارت کاربردی","Write down useful phrases.","عبارت‌های کاربردی را یادداشت کن.","a notebook page with a short list of lines"),
 ("daily habit","phrase","/ˈdeɪli ˈhæbɪt/","عادت روزانه","Make it a daily habit.","آن را عادت روزانه کن.","a wall calendar with several days ticked in a row"),
 ("well done","phrase","/wel dʌn/","آفرین","Well done! You finished.","آفرین! تمامش کردی.","two adults in their thirties clapping for a third"),
 ("what's next","phrase","/wɒts nekst/","بعدش چه","So, what's next?","خب، بعدش چه؟","a path continuing beyond a marked point"),
]
