# -*- coding: utf-8 -*-
"""واژگان دروس ۱۱ تا ۲۰ سطح B2 — فشرده‌سازی، تأکید، احتیاط، گفتمان رسمی."""

V = {}

V[11] = [
 ("having finished","phrase","/ˈhævɪŋ ˈfɪnɪʃt/","پس از تمام کردن","Having finished, she left.","پس از تمام کردن، رفت.","a woman in her early thirties closing a laptop and standing up"),
 ("upon arrival","phrase","/əˈpɒn əˈraɪvl/","به‌محض رسیدن","Upon arrival, please register.","به‌محض رسیدن ثبت‌نام کنید.","a reception desk with a visitor's badge tray"),
 ("while working","phrase","/waɪl ˈwɜːkɪŋ/","حین کار کردن","While working, he noticed it.","حین کار کردن متوجهش شد.","a man in his early thirties pausing at a workbench"),
 ("once completed","phrase","/wʌns kəmˈpliːtɪd/","پس از تکمیل","Once completed, send it to me.","پس از تکمیل برایم بفرست.","a finished form placed in an outgoing tray"),
 ("concise","adjective","/kənˈsaɪs/","موجز","Keep the report concise.","گزارش را موجز نگه دار.","a single dense page beside a thick folder"),
 ("redundant","adjective","/rɪˈdʌndənt/","زائد","That sentence is redundant.","آن جمله زائد است.","a crossed-out repeated line on a page"),
 ("wordy","adjective","/ˈwɜːdi/","پرگو","The draft is too wordy.","پیش‌نویس زیادی پرگوست.","a tightly packed page of dense text"),
 ("draft","noun","/drɑːft/","پیش‌نویس","This is the first draft.","این پیش‌نویس اول است.","a heavily marked-up page on a desk"),
 ("revision","noun","/rɪˈvɪʒn/","بازنگری","It needs another revision.","به بازنگری دیگری نیاز دارد.","two versions of a page side by side"),
 ("edit","verb","/ˈedɪt/","ویرایش کردن","I edited the whole text.","تمام متن را ویرایش کردم.","a hand striking lines through a printed page"),
 ("condense","verb","/kənˈdens/","فشرده کردن","Can you condense it?","می‌شود فشرده‌اش کنی؟","a long page reduced to a short one"),
 ("omit","verb","/əˈmɪt/","حذف کردن","We omitted the details.","جزئیات را حذف کردیم.","a paragraph blanked out on a page"),
 ("merge","verb","/mɜːdʒ/","ادغام کردن","We merged the two sections.","دو بخش را ادغام کردیم.","two streams joining into one"),
 ("streamline","verb","/ˈstriːmlaɪn/","روان‌سازی کردن","We streamlined the process.","فرایند را روان‌سازی کردیم.","a winding path replaced by a direct one"),
 ("flow","noun","/fləʊ/","روانی متن","The flow is much better now.","روانی متن حالا خیلی بهتر است.","a smooth continuous line drawn on a page"),
 ("structure","noun","/ˈstrʌktʃə/","ساختار","The structure is clear.","ساختار روشن است.","a simple outline drawn on a whiteboard"),
 ("paragraph","noun","/ˈpærəɡrɑːf/","پاراگراف","Start a new paragraph here.","اینجا پاراگراف تازه‌ای شروع کن.","a page with clearly separated blocks of text"),
 ("linking word","phrase","/ˈlɪŋkɪŋ wɜːd/","کلمه ربط","Use a linking word here.","اینجا از کلمه ربط استفاده کن.","two sentence cards joined by a connector"),
 ("cut down","phrase","/kʌt daʊn/","کوتاه کردن","Cut it down by half.","نصفش کن.","a long page folded to half its length"),
 ("polish","verb","/ˈpɒlɪʃ/","صیقل دادن","I polished the final version.","نسخه نهایی را صیقل دادم.","a clean finished page beside earlier drafts"),
]

V[12] = [
 ("never have I","phrase","/ˈnevə hæv aɪ/","هرگز ندیده‌ام","Never have I seen such a thing.","هرگز چنین چیزی ندیده‌ام.","a person in their thirties staring in astonishment"),
 ("rarely","adverb","/ˈreəli/","به‌ندرت","Rarely does he complain.","به‌ندرت شکایت می‌کند.","a man in his early thirties working calmly without fuss"),
 ("seldom","adverb","/ˈseldəm/","کم پیش می‌آید","Seldom do we agree.","کم پیش می‌آید موافق باشیم.","two adults in their thirties on opposite sides of a table"),
 ("no sooner","phrase","/nəʊ ˈsuːnə/","به‌محض اینکه","No sooner had we left than it rained.","تا رفتیم باران گرفت.","rain beginning on an empty street"),
 ("hardly","adverb","/ˈhɑːdli/","به‌سختی، تازه","Hardly had he spoken when the phone rang.","تازه حرف زده بود که تلفن زنگ خورد.","a phone ringing beside a person mid-sentence"),
 ("not only","phrase","/nɒt ˈəʊnli/","نه‌تنها","Not only did he help, he stayed late.","نه‌تنها کمک کرد، دیر هم ماند.","a colleague in their thirties working late beside a finished task"),
 ("at no time","phrase","/ət nəʊ taɪm/","در هیچ زمانی","At no time did he agree.","در هیچ زمانی موافقت نکرد.","a man in his early thirties with arms folded at a table"),
 ("emphasis","noun","/ˈemfəsɪs/","تأکید","The emphasis is on quality.","تأکید بر کیفیت است.","one word underlined heavily on a page"),
 ("astonishing","adjective","/əˈstɒnɪʃɪŋ/","حیرت‌آور","The result was astonishing.","نتیجه حیرت‌آور بود.","a chart line far above the expected range"),
 ("remarkable","adjective","/rɪˈmɑːkəbl/","قابل توجه","It's a remarkable achievement.","دستاورد قابل توجهی است.","a framed award standing alone on a shelf"),
 ("striking","adjective","/ˈstraɪkɪŋ/","چشمگیر","There's a striking difference.","تفاوت چشمگیری هست.","two objects of clearly different size side by side"),
 ("extraordinary","adjective","/ɪkˈstrɔːdnri/","خارق‌العاده","It was an extraordinary case.","مورد خارق‌العاده‌ای بود.","a single unusual item among ordinary ones"),
 ("unprecedented","adjective","/ʌnˈpresɪdentɪd/","بی‌سابقه","The demand was unprecedented.","تقاضا بی‌سابقه بود.","a queue stretching beyond the frame"),
 ("scarcely","adverb","/ˈskeəsli/","به‌زحمت","I could scarcely believe it.","به‌زحمت باورم می‌شد.","a woman in her early thirties with wide eyes at a document"),
 ("indeed","adverb","/ɪnˈdiːd/","به‌راستی","It was indeed surprising.","به‌راستی غافلگیرکننده بود.","a man in his early thirties nodding with raised eyebrows"),
 ("by no means","phrase","/baɪ nəʊ miːnz/","به‌هیچ‌وجه","It's by no means certain.","به‌هیچ‌وجه قطعی نیست.","a scale hovering between two marks"),
 ("little did we know","phrase","/ˈlɪtl dɪd wi nəʊ/","نمی‌دانستیم که","Little did we know what followed.","نمی‌دانستیم بعدش چه می‌شود.","two adults in their thirties walking toward a bend in a road"),
 ("only then","phrase","/ˈəʊnli ðen/","تنها آن وقت","Only then did we understand.","تنها آن وقت فهمیدیم.","two adults in their thirties reacting to a revealed diagram"),
 ("in no way","phrase","/ɪn nəʊ weɪ/","به هیچ عنوان","In no way is this acceptable.","این به هیچ عنوان پذیرفتنی نیست.","a document firmly set aside"),
 ("stress","verb","/stres/","تأکید کردن","I want to stress this point.","می‌خواهم بر این نکته تأکید کنم.","a hand pressing a marker firmly on one line"),
]

V[13] = [
 ("it was you who","phrase","/ɪt wəz juː huː/","این تو بودی که","It was you who said it.","این تو بودی که گفتی.","one person in a group being pointed to"),
 ("it is here that","phrase","/ɪt ɪz hɪə ðæt/","همین‌جاست که","It is here that the problem starts.","همین‌جاست که مشکل شروع می‌شود.","a marked point on a long diagram"),
 ("the reason why","phrase","/ðə ˈriːzn waɪ/","دلیلی که","The reason why I left is simple.","دلیلی که رفتم ساده است.","a man in his early thirties explaining with a calm gesture"),
 ("the thing is","phrase","/ðə θɪŋ ɪz/","مسئله این است که","The thing is, we have no time.","مسئله این است که وقت نداریم.","a clock beside an unfinished plan"),
 ("all I want","phrase","/ɔːl aɪ wɒnt/","تنها چیزی که می‌خواهم","All I want is a clear answer.","تنها چیزی که می‌خواهم پاسخ روشن است.","a single blank line awaiting one word"),
 ("clarify a point","phrase","/ˈklærɪfaɪ ə pɔɪnt/","روشن کردن نکته","Let me clarify a point.","بگذار نکته‌ای را روشن کنم.","a hand underlining a line for a listener"),
 ("misquote","verb","/ˌmɪsˈkwəʊt/","نادرست نقل کردن","I was misquoted.","حرفم نادرست نقل شد.","two versions of the same line, one altered"),
 ("insistence","noun","/ɪnˈsɪstəns/","اصرار","His insistence surprised us.","اصرارش غافلگیرمان کرد.","a man in his early thirties repeating a point firmly"),
 ("credit","noun","/ˈkredɪt/","اعتبار، سهم","She deserves the credit.","اعتبارش به او می‌رسد.","a colleague in their thirties being applauded"),
 ("blame someone for","phrase","/bleɪm ˈsʌmwʌn fɔː/","کسی را بابت … سرزنش کردن","Don't blame me for the delay.","مرا بابت تأخیر سرزنش نکن.","two adults in their thirties in a tense exchange"),
 ("bring to attention","phrase","/brɪŋ tuː əˈtenʃn/","به توجه رساندن","I brought it to their attention.","به توجهشان رساندم.","a document placed prominently on a desk"),
 ("draw attention to","phrase","/drɔː əˈtenʃn tuː/","توجه را جلب کردن به","She drew attention to the cost.","توجه را به هزینه جلب کرد.","a woman in her early thirties circling a figure on a chart"),
 ("set the record straight","phrase","/set ðə ˈrekɔːd streɪt/","حقیقت را روشن کردن","Let me set the record straight.","بگذار حقیقت را روشن کنم.","a corrected line replacing a crossed-out one"),
 ("take credit for","phrase","/teɪk ˈkredɪt fɔː/","اعتبار چیزی را برداشتن","He took credit for it.","اعتبارش را برداشت.","one person accepting applause for a group's work"),
 ("owe","verb","/əʊ/","مدیون بودن","We owe her a lot.","خیلی به او مدیونیم.","colleagues in their thirties thanking one person"),
 ("acknowledge","verb","/əkˈnɒlɪdʒ/","به رسمیت شناختن","He acknowledged the mistake.","اشتباه را پذیرفت.","a man in his early thirties nodding at a marked page"),
 ("deliberate","adjective","/dɪˈlɪbərət/","عمدی","It wasn't deliberate.","عمدی نبود.","an accidental spill beside an apologetic gesture"),
 ("accidental","adjective","/ˌæksɪˈdentl/","تصادفی","It was purely accidental.","کاملاً تصادفی بود.","a knocked-over cup on a desk"),
 ("precisely","adverb","/prɪˈsaɪsli/","دقیقاً","That's precisely my point.","دقیقاً منظور من همین است.","a man in his early thirties pointing at one line in agreement"),
 ("namely","adverb","/ˈneɪmli/","یعنی، به‌نام","One issue, namely cost.","یک مسئله، یعنی هزینه.","one item highlighted in a short list"),
]

V[14] = [
 ("what matters is","phrase","/wɒt ˈmætəz ɪz/","آنچه مهم است","What matters is trust.","آنچه مهم است اعتماد است.","two adults in their thirties shaking hands firmly"),
 ("what I mean is","phrase","/wɒt aɪ miːn ɪz/","منظورم این است که","What I mean is, we should wait.","منظورم این است که باید صبر کنیم.","a person in their thirties rephrasing with an open gesture"),
 ("what happened was","phrase","/wɒt ˈhæpənd wɒz/","آنچه شد این بود که","What happened was simple.","آنچه شد ساده بود.","a short sequence of steps drawn on a page"),
 ("value","noun","/ˈvæljuː/","ارزش","Honesty is a core value.","صداقت ارزشی بنیادی است.","a single word card placed at the centre of a diagram"),
 ("integrity","noun","/ɪnˈteɡrəti/","درستکاری","Integrity matters most.","درستکاری از همه مهم‌تر است.","a person in their thirties returning a found wallet"),
 ("trust","noun","/trʌst/","اعتماد","Trust takes years to build.","اعتماد سال‌ها ساخته می‌شود.","two adults in their thirties working closely together"),
 ("loyalty","noun","/ˈlɔɪəlti/","وفاداری","Loyalty is rare.","وفاداری کمیاب است.","a long-standing team of adults in their thirties"),
 ("fairness","noun","/ˈfeənəs/","انصاف","Fairness is essential.","انصاف ضروری است.","a level balance scale on a plain table"),
 ("priority","noun","/praɪˈɒrəti/","اولویت","Safety is the top priority.","ایمنی اولویت نخست است.","a first item marked at the top of a list"),
 ("core","adjective","/kɔː/","بنیادی","These are our core principles.","این‌ها اصول بنیادی ما هستند.","a central circle in a simple diagram"),
 ("essentials","noun","/ɪˈsenʃlz/","ضروریات","Let's cover the essentials.","بیا ضروریات را بپوشانیم.","a small set of basic tools laid out"),
 ("secondary","adjective","/ˈsekəndri/","فرعی","Cost is secondary here.","اینجا هزینه فرعی است.","one item placed behind another"),
 ("matter","verb","/ˈmætə/","اهمیت داشتن","Details matter.","جزئیات اهمیت دارند.","a magnifying view of a small component"),
 ("count","verb","/kaʊnt/","به حساب آمدن","Every hour counts.","هر ساعت به حساب می‌آید.","a clock beside a filling progress bar"),
 ("outweigh","verb","/ˌaʊtˈweɪ/","سنگین‌تر بودن از","Trust outweighs speed.","اعتماد بر سرعت می‌چربد.","a balance tipping toward one side"),
 ("come first","phrase","/kʌm fɜːst/","اول بودن","Safety comes first.","ایمنی اول است.","a safety helmet placed before other equipment"),
 ("at the heart of","phrase","/ət ðə hɑːt əv/","در قلبِ","Trust is at the heart of it.","اعتماد در قلب آن است.","a marked centre point of a diagram"),
 ("boil down","phrase","/bɔɪl daʊn/","خلاصه شدن","It all boils down to this.","همه‌اش به این خلاصه می‌شود.","a large diagram reduced to a single line"),
 ("stand for","phrase","/stænd fɔː/","نماینده … بودن","What do you stand for?","نماینده چه ارزشی هستی؟","a person in their thirties standing firmly beside a written statement"),
 ("above all","phrase","/əˈbʌv ɔːl/","بیش از همه","Above all, be honest.","بیش از همه صادق باش.","one line raised above others on a page"),
]

V[15] = [
 ("make a point","phrase","/meɪk ə pɔɪnt/","نکته‌ای را رساندن","He made a good point.","نکته خوبی گفت.","a man in his early thirties speaking at a meeting table"),
 ("get straight to the point","phrase","/ɡet streɪt tə ðə pɔɪnt/","مستقیم سر اصل مطلب رفتن","Let's get straight to the point.","بیا مستقیم سر اصل مطلب برویم.","a short agenda with one item"),
 ("beat around the bush","phrase","/biːt əˈraʊnd ðə bʊʃ/","حاشیه رفتن","Don't beat around the bush.","حاشیه نرو.","a winding path beside a direct one"),
 ("assertive","adjective","/əˈsɜːtɪv/","قاطع و محترمانه","Be assertive, not aggressive.","قاطع باش، نه پرخاشگر.","a woman in her early thirties speaking calmly but firmly"),
 ("aggressive","adjective","/əˈɡresɪv/","پرخاشگر","His tone was aggressive.","لحنش پرخاشگرانه بود.","a man in his early thirties leaning forward tensely"),
 ("blunt","adjective","/blʌnt/","رک","She was rather blunt.","نسبتاً رک بود.","a woman in her early thirties speaking without softening"),
 ("tactful","adjective","/ˈtæktfl/","با ملاحظه","He was very tactful.","خیلی با ملاحظه بود.","a man in his early thirties delivering news gently"),
 ("diplomatic","adjective","/ˌdɪpləˈmætɪk/","دیپلماتیک","Try to be diplomatic.","سعی کن دیپلماتیک باشی.","two adults in their thirties finding middle ground"),
 ("firmly","adverb","/ˈfɜːmli/","محکم","She stated it firmly.","محکم بیانش کرد.","a woman in her early thirties with a steady raised hand"),
 ("politely but firmly","phrase","/pəˈlaɪtli bʌt ˈfɜːmli/","مؤدبانه اما محکم","I refused politely but firmly.","مؤدبانه اما محکم رد کردم.","a person in their thirties declining with a calm gesture"),
 ("stand your ground","phrase","/stænd jɔː ɡraʊnd/","بر موضع خود ایستادن","She stood her ground.","بر موضعش ایستاد.","a woman in her early thirties standing steady in a discussion"),
 ("give way","phrase","/ɡɪv weɪ/","کوتاه آمدن","He wouldn't give way.","حاضر نبود کوتاه بیاید.","a man in his early thirties holding his position at a table"),
 ("emphasise","verb","/ˈemfəsaɪz/","تأکید کردن","I'd like to emphasise this.","می‌خواهم بر این تأکید کنم.","a hand pressing a marker on one line"),
 ("repeat for effect","phrase","/rɪˈpiːt fər ɪˈfekt/","تکرار برای تأکید","He repeated it for effect.","برای تأکید تکرارش کرد.","the same line written twice on a whiteboard"),
 ("pause","noun","/pɔːz/","مکث","A short pause helps.","مکث کوتاه کمک می‌کند.","a person in their thirties pausing mid-presentation"),
 ("tone","noun","/təʊn/","لحن","Watch your tone.","مواظب لحنت باش.","two adults in their thirties reacting to the same words differently"),
 ("body language","phrase","/ˈbɒdi ˈlæŋɡwɪdʒ/","زبان بدن","Her body language was open.","زبان بدنش باز بود.","a woman in her early thirties with relaxed open posture"),
 ("eye contact","phrase","/aɪ ˈkɒntækt/","تماس چشمی","Keep eye contact.","تماس چشمی را حفظ کن.","two adults in their thirties looking directly at each other"),
 ("convince","verb","/kənˈvɪns/","قانع کردن","He convinced the whole team.","تمام تیم را قانع کرد.","a group of adults in their thirties nodding together"),
 ("come across as","phrase","/kʌm əˈkrɒs əz/","به‌نظر رسیدن","He came across as confident.","بااعتماد به نفس به‌نظر رسید.","a man in his early thirties presenting without notes"),
]

V[16] = [
 ("tend to","phrase","/tend tuː/","معمولاً … می‌شود","Prices tend to rise in winter.","قیمت‌ها معمولاً زمستان بالا می‌رود.","a chart line rising each winter"),
 ("it tends to be the case","phrase","/ɪt tendz tə bi ðə keɪs/","معمولاً چنین است","It tends to be the case here.","اینجا معمولاً چنین است.","a repeating pattern across a chart"),
 ("on the whole","phrase","/ɒn ðə həʊl/","روی هم رفته","On the whole, it works.","روی هم رفته جواب می‌دهد.","a summary line beneath a set of results"),
 ("generally speaking","phrase","/ˈdʒenrəli ˈspiːkɪŋ/","به‌طور کلی","Generally speaking, it's safe.","به‌طور کلی امن است.","a wide view of an orderly workshop"),
 ("as a rule","phrase","/əz ə ruːl/","قاعدتاً","As a rule, we don't do that.","قاعدتاً این کار را نمی‌کنیم.","a printed policy sheet on a wall"),
 ("in most cases","phrase","/ɪn məʊst ˈkeɪsɪz/","در بیشتر موارد","In most cases, it's fine.","در بیشتر موارد مشکلی نیست.","a bar chart with one small exception"),
 ("arguably","adverb","/ˈɑːɡjuəbli/","می‌توان گفت","It's arguably the best option.","می‌توان گفت بهترین گزینه است.","two adults in their thirties debating over two items"),
 ("seemingly","adverb","/ˈsiːmɪŋli/","ظاهراً","A seemingly small change.","تغییری ظاهراً کوچک.","a tiny adjustment with a large visible result"),
 ("relatively","adverb","/ˈrelətɪvli/","نسبتاً","It's relatively cheap.","نسبتاً ارزان است.","two price tags with one clearly lower"),
 ("somewhat","adverb","/ˈsʌmwɒt/","تا حدودی","It's somewhat unclear.","تا حدودی مبهم است.","a partly blurred diagram"),
 ("appear to","phrase","/əˈpɪə tuː/","به‌نظر رسیدن","It appears to be working.","به‌نظر می‌رسد کار می‌کند.","a machine running smoothly on a bench"),
 ("suggest that","phrase","/səˈdʒest ðæt/","حاکی از آن است که","The data suggests that costs rose.","داده‌ها حاکی از افزایش هزینه است.","a chart with an upward line"),
 ("indicate","verb","/ˈɪndɪkeɪt/","نشان دادن","The results indicate a problem.","نتایج نشان‌دهنده مشکل‌اند.","a warning marker on a chart"),
 ("imply","verb","/ɪmˈplaɪ/","دلالت کردن بر","That implies a delay.","این بر تأخیر دلالت دارد.","an arrow leading to a stopped clock"),
 ("assume","verb","/əˈsjuːm/","فرض کردن","Let's not assume too much.","بیا زیاد فرض نکنیم.","a diagram with one box marked uncertain"),
 ("overstate","verb","/ˌəʊvəˈsteɪt/","بزرگ‌نمایی کردن","I don't want to overstate it.","نمی‌خواهم بزرگ‌نمایی کنم.","a small object beside an oversized shadow"),
 ("cautious claim","phrase","/ˈkɔːʃəs kleɪm/","ادعای محتاطانه","That's a cautious claim.","ادعای محتاطانه‌ای است.","a carefully worded line on a page"),
 ("with the exception of","phrase","/wɪð ði ɪkˈsepʃn əv/","به‌جزِ","With the exception of Friday, we're free.","به‌جز جمعه آزادیم.","a weekly planner with one day marked"),
 ("by and large","phrase","/baɪ ənd lɑːdʒ/","عمدتاً","By and large, we agree.","عمدتاً موافقیم.","most of a group nodding together"),
 ("more often than not","phrase","/mɔːr ˈɒfn ðən nɒt/","بیشتر اوقات","More often than not, it works.","بیشتر اوقات جواب می‌دهد.","a chart with most points above a line"),
]

V[17] = [
 ("approximately","adverb","/əˈprɒksɪmətli/","تقریباً","Approximately two hundred came.","تقریباً دویست نفر آمدند.","a large gathering seen from above"),
 ("roughly speaking","phrase","/ˈrʌfli ˈspiːkɪŋ/","تقریباً بگویم","Roughly speaking, it's half.","تقریباً بگویم نصف است.","a shape divided into two near-equal parts"),
 ("give or take","phrase","/ɡɪv ɔː teɪk/","کم‌وبیش","Ten days, give or take.","ده روز، کم‌وبیش.","a calendar span with soft edges marked"),
 ("in the region of","phrase","/ɪn ðə ˈriːdʒən əv/","در حدودِ","In the region of a thousand.","در حدود هزار.","a large crowd filling a square"),
 ("estimate","verb","/ˈestɪmeɪt/","تخمین زدن","We estimated the cost.","هزینه را تخمین زدیم.","a hand writing figures on a notepad"),
 ("calculate","verb","/ˈkælkjuleɪt/","محاسبه کردن","Let me calculate it.","بگذار محاسبه‌اش کنم.","a calculator beside a written column of numbers"),
 ("measure","verb","/ˈmeʒə/","اندازه گرفتن","We measured the room.","اتاق را اندازه گرفتیم.","a tape measure stretched along a wall"),
 ("exceed","verb","/ɪkˈsiːd/","فراتر رفتن از","It exceeded our estimate.","از تخمین ما فراتر رفت.","a chart line passing above a marked target"),
 ("fall short of","phrase","/fɔːl ʃɔːt əv/","کمتر از … بودن","It fell short of the target.","کمتر از هدف بود.","a chart line stopping below a marked line"),
 ("margin","noun","/ˈmɑːdʒɪn/","حاشیه، اختلاف","We won by a small margin.","با اختلاف کمی بردیم.","two bars with a very small gap"),
 ("accuracy","noun","/ˈækjərəsi/","دقت","Accuracy is important here.","اینجا دقت مهم است.","a precise instrument on a bench"),
 ("estimate range","phrase","/ˈestɪmət reɪndʒ/","بازه تخمین","Give me an estimate range.","بازه تخمین را بگو.","two markers on a scale with a span between them"),
 ("at most","phrase","/ət məʊst/","حداکثر","At most, it takes an hour.","حداکثر یک ساعت طول می‌کشد.","a clock with one hour marked"),
 ("at least","phrase","/ət liːst/","حداقل","It costs at least that much.","حداقل همین‌قدر هزینه دارد.","a lower marker on a price scale"),
 ("up to","phrase","/ʌp tuː/","تا سقفِ","Up to fifty people can attend.","تا سقف پنجاه نفر می‌توانند بیایند.","a room with a marked seating limit"),
 ("well over","phrase","/wel ˈəʊvə/","خیلی بیشتر از","Well over a hundred applied.","خیلی بیشتر از صد نفر درخواست دادند.","a long queue extending out of a doorway"),
 ("just under","phrase","/dʒʌst ˈʌndə/","کمی کمتر از","Just under two hours.","کمی کمتر از دو ساعت.","a clock just short of a marked point"),
 ("precise figure","phrase","/prɪˈsaɪs ˈfɪɡə/","رقم دقیق","I don't have the precise figure.","رقم دقیق را ندارم.","a partly filled table of numbers"),
 ("ballpark","noun","/ˈbɔːlpɑːk/","حدودی","Give me a ballpark number.","یک عدد حدودی بده.","a rough figure sketched on a notepad"),
 ("negligible","adjective","/ˈneɡlɪdʒəbl/","ناچیز","The difference is negligible.","تفاوت ناچیز است.","two nearly identical bars on a chart"),
]

V[18] = [
 ("assuming that","phrase","/əˈsjuːmɪŋ ðæt/","با فرض اینکه","Assuming that's true, we agree.","با فرض درست بودنش موافقیم.","a diagram with one box marked as given"),
 ("given that","phrase","/ˈɡɪvn ðæt/","با توجه به اینکه","Given that it's late, let's stop.","با توجه به اینکه دیر است بس کنیم.","a clock past working hours beside a closed folder"),
 ("in light of","phrase","/ɪn laɪt əv/","در پرتوِ","In light of the results, we changed.","در پرتو نتایج تغییر دادیم.","a chart lit by a desk lamp"),
 ("it follows that","phrase","/ɪt ˈfɒləʊz ðæt/","نتیجه می‌شود که","It follows that we must wait.","نتیجه می‌شود که باید صبر کنیم.","an arrow leading from two boxes to a third"),
 ("infer","verb","/ɪnˈfɜː/","استنباط کردن","What can we infer from this?","از این چه استنباط می‌کنیم؟","a person in their thirties studying a chart closely"),
 ("deduce","verb","/dɪˈdjuːs/","استنتاج کردن","We deduced the cause.","علت را استنتاج کردیم.","a diagram with a completed chain of arrows"),
 ("premise","noun","/ˈpremɪs/","مقدمه، پیش‌فرض","The premise is questionable.","پیش‌فرض قابل تردید است.","the base block of a stacked diagram marked"),
 ("logic","noun","/ˈlɒdʒɪk/","منطق","The logic is sound.","منطقش درست است.","a clean chain of connected boxes"),
 ("flaw","noun","/flɔː/","ایراد","There's a flaw in the argument.","استدلال ایرادی دارد.","a single crack in a solid surface"),
 ("valid","adjective","/ˈvælɪd/","معتبر","That's a valid point.","نکته معتبری است.","a stamped approved page"),
 ("questionable","adjective","/ˈkwestʃənəbl/","قابل تردید","The data is questionable.","داده‌ها قابل تردیدند.","a chart with a question mark space beside it"),
 ("consistent","adjective","/kənˈsɪstənt/","سازگار","The results are consistent.","نتایج سازگارند.","several identical readings on a bench"),
 ("contradictory","adjective","/ˌkɒntrəˈdɪktəri/","متناقض","The two reports are contradictory.","دو گزارش متناقض‌اند.","two charts with opposite trends"),
 ("hypothesis","noun","/haɪˈpɒθəsɪs/","فرضیه","Let's test the hypothesis.","بیا فرضیه را آزمایش کنیم.","a labelled test setup on a bench"),
 ("verify a claim","phrase","/ˈverɪfaɪ ə kleɪm/","راستی‌آزمایی ادعا","We should verify the claim.","باید ادعا را راستی‌آزمایی کنیم.","two documents compared side by side"),
 ("jump to conclusions","phrase","/dʒʌmp tə kənˈkluːʒnz/","نتیجه‌گیری شتاب‌زده","Don't jump to conclusions.","شتاب‌زده نتیجه نگیر.","a person in their thirties pausing before a half-read report"),
 ("on the assumption that","phrase","/ɒn ði əˈsʌmpʃn ðæt/","با این فرض که","We planned on the assumption that it'd rain.","با این فرض برنامه ریختیم که باران بیاید.","a plan beside a weather chart"),
 ("as a corollary","phrase","/əz ə kəˈrɒləri/","به‌عنوان نتیجه فرعی","As a corollary, costs fell.","به‌عنوان نتیجه فرعی، هزینه‌ها افت کرد.","a small branch arrow off a main conclusion"),
 ("all else being equal","phrase","/ɔːl els ˈbiːɪŋ ˈiːkwəl/","با ثابت بودن بقیه شرایط","All else being equal, it's better.","با ثابت بودن بقیه شرایط بهتر است.","two identical setups with one variable changed"),
 ("sound reasoning","phrase","/saʊnd ˈriːzənɪŋ/","استدلال درست","That's sound reasoning.","استدلال درستی است.","a well-structured page of connected points"),
]

V[19] = [
 ("to some extent","phrase","/tə sʌm ɪkˈstent/","تا حدی","I agree to some extent.","تا حدی موافقم.","a marker placed partway along a scale"),
 ("to a large extent","phrase","/tə ə lɑːdʒ ɪkˈstent/","تا حد زیادی","To a large extent, that's true.","تا حد زیادی درست است.","a marker near the far end of a scale"),
 ("up to a point","phrase","/ʌp tuː ə pɔɪnt/","تا یک جایی","I agree up to a point.","تا یک جایی موافقم.","a line stopping at a marked point"),
 ("partly true","phrase","/ˈpɑːtli truː/","تا حدی درست","That's partly true.","تا حدی درست است.","a half-shaded circle"),
 ("with reservations","phrase","/wɪð ˌrezəˈveɪʃnz/","با تحفظ","I accept it with reservations.","با تحفظ می‌پذیرمش.","a signed page with a marginal note"),
 ("in principle","phrase","/ɪn ˈprɪnsəpl/","در اصل","In principle, I agree.","در اصل موافقم.","two adults in their thirties nodding over a broad outline"),
 ("in practice","phrase","/ɪn ˈpræktɪs/","در عمل","In practice, it's harder.","در عمل سخت‌تر است.","a workbench with a partly assembled device"),
 ("broadly","adverb","/ˈbrɔːdli/","به‌طور کلی","I broadly agree.","به‌طور کلی موافقم.","a wide view of a shared plan"),
 ("largely","adverb","/ˈlɑːdʒli/","عمدتاً","It's largely correct.","عمدتاً درست است.","a chart mostly matching a target line"),
 ("essentially","adverb","/ɪˈsenʃəli/","اساساً","Essentially, we agree.","اساساً موافقیم.","two nearly identical diagrams"),
 ("qualify a statement","phrase","/ˈkwɒlɪfaɪ ə ˈsteɪtmənt/","مشروط کردن یک گفته","Let me qualify that statement.","بگذار آن گفته را مشروط کنم.","a line with an added footnote"),
 ("concede","verb","/kənˈsiːd/","پذیرفتن (در بحث)","I concede that point.","آن نکته را می‌پذیرم.","a man in his early thirties nodding at an opponent's note"),
 ("reservation","noun","/ˌrezəˈveɪʃn/","تحفظ، تردید","I have one reservation.","یک تحفظ دارم.","a single marginal note on an approved page"),
 ("common ground","phrase","/ˈkɒmən ɡraʊnd/","نقطه مشترک","We found common ground.","نقطه مشترک پیدا کردیم.","two overlapping circles on a page"),
 ("middle ground","phrase","/ˈmɪdl ɡraʊnd/","حد وسط","Let's find middle ground.","بیا حد وسط را پیدا کنیم.","a marker set between two positions"),
 ("nuanced","adjective","/ˈnjuːɑːnst/","ظریف و چندلایه","It's a nuanced issue.","مسئله ظریفی است.","a gradient between two colours"),
 ("black and white","phrase","/blæk ənd waɪt/","سیاه و سفید","It isn't black and white.","سیاه و سفید نیست.","a grey gradient between two extremes"),
 ("see both sides","phrase","/siː bəʊθ saɪdz/","هر دو طرف را دیدن","I can see both sides.","هر دو طرف را می‌بینم.","a person in their thirties standing between two documents"),
 ("depends on how","phrase","/dɪˈpendz ɒn haʊ/","بستگی دارد چطور","It depends on how you define it.","بستگی دارد چطور تعریفش کنی.","a word card read two different ways"),
 ("fair point","phrase","/feə pɔɪnt/","نکته منصفانه","That's a fair point.","نکته منصفانه‌ای است.","a man in his early thirties acknowledging a colleague's note"),
]

V[20] = [
 ("I'd like to begin by","phrase","/aɪd laɪk tə bɪˈɡɪn baɪ/","می‌خواهم با … شروع کنم","I'd like to begin by thanking you.","می‌خواهم با تشکر از شما شروع کنم.","a presenter in their thirties addressing a small audience"),
 ("outline","verb","/ˈaʊtlaɪn/","کلیات را گفتن","Let me outline the plan.","بگذارید کلیات برنامه را بگویم.","a simple outline drawn on a whiteboard"),
 ("agenda item","phrase","/əˈdʒendə ˈaɪtəm/","بند دستور جلسه","The first agenda item is cost.","اولین بند دستور جلسه هزینه است.","a numbered list on a meeting table"),
 ("move on to","phrase","/muːv ɒn tuː/","رفتن به سراغِ","Let's move on to the figures.","بیایید سراغ ارقام برویم.","a presenter in their thirties turning to a new chart"),
 ("turning to","phrase","/ˈtɜːnɪŋ tuː/","با رجوع به","Turning to the second point…","با رجوع به نکته دوم…","a hand indicating the next section of a slide"),
 ("as you can see","phrase","/əz juː kən siː/","همان‌طور که می‌بینید","As you can see, sales rose.","همان‌طور که می‌بینید فروش بالا رفت.","a presenter in their thirties pointing at a rising chart"),
 ("to sum up","phrase","/tə sʌm ʌp/","برای جمع‌بندی","To sum up, we're on track.","برای جمع‌بندی، در مسیریم.","a final summary slide with three short lines"),
 ("handout","noun","/ˈhændaʊt/","جزوه","There's a handout for everyone.","برای همه جزوه هست.","a stack of printed sheets on a table"),
 ("slide","noun","/slaɪd/","اسلاید","The next slide shows the data.","اسلاید بعدی داده‌ها را نشان می‌دهد.","a projected chart on a screen"),
 ("audience","noun","/ˈɔːdiəns/","حضار","The audience asked questions.","حضار سؤال پرسیدند.","a small seated audience of adults in their thirties"),
 ("question and answer","phrase","/ˈkwestʃən ənd ˈɑːnsə/","پرسش و پاسخ","We'll have question and answer at the end.","پایان کار پرسش و پاسخ داریم.","a raised hand in a seated audience"),
 ("take questions","phrase","/teɪk ˈkwestʃənz/","پاسخ به سؤال","I'll take questions now.","حالا به سؤالات پاسخ می‌دهم.","a presenter in their thirties gesturing toward the audience"),
 ("go over time","phrase","/ɡəʊ ˈəʊvə taɪm/","از وقت گذشتن","We went over time.","از وقت گذشتیم.","a clock past a marked end time"),
 ("keep to time","phrase","/kiːp tə taɪm/","سر وقت ماندن","Please keep to time.","لطفاً سر وقت بمانید.","a timer placed beside a lectern"),
 ("rehearse","verb","/rɪˈhɜːs/","تمرین کردن (ارائه)","I rehearsed it twice.","دو بار تمرینش کردم.","a person in their thirties practising in an empty room"),
 ("nervousness","noun","/ˈnɜːvəsnəs/","اضطراب","Nervousness is normal.","اضطراب طبیعی است.","a presenter in their thirties taking a steadying breath"),
 ("engage","verb","/ɪnˈɡeɪdʒ/","درگیر کردن","Engage the audience early.","حضار را زود درگیر کن.","an audience leaning forward with interest"),
 ("visual aid","phrase","/ˈvɪʒuəl eɪd/","کمک بصری","Use a visual aid.","از کمک بصری استفاده کن.","a clear diagram shown on a screen"),
 ("key message","phrase","/kiː ˈmesɪdʒ/","پیام کلیدی","What's the key message?","پیام کلیدی چیست؟","one line highlighted on a slide"),
 ("wrap up","phrase","/ræp ʌp/","جمع کردن","Let's wrap up here.","بیایید اینجا جمع کنیم.","a presenter in their thirties closing a folder")
]
