# -*- coding: utf-8 -*-
"""واژگان دروس ۲۱ تا ۳۰ سطح B1 — مجهول غیرشخصی، عبارت وصفی، استدلال."""

V = {}

V[21] = [
 ("it is said","phrase","/ɪt ɪz sed/","گفته می‌شود","It is said that prices will rise.","گفته می‌شود قیمت‌ها بالا می‌رود.","a printed page with an unattributed headline space"),
 ("it is believed","phrase","/ɪt ɪz bɪˈliːvd/","اعتقاد بر این است","It is believed to be old.","اعتقاد بر این است که قدیمی است.","an ancient stone structure in daylight"),
 ("reportedly","adverb","/rɪˈpɔːtɪdli/","بنا بر گزارش‌ها","He reportedly left the country.","بنا بر گزارش‌ها کشور را ترک کرد.","an empty departure gate at an airport"),
 ("allegedly","adverb","/əˈledʒɪdli/","بنا به ادعا","The money was allegedly missing.","بنا به ادعا پول گم شده بود.","an open empty cash drawer"),
 ("allegation","noun","/ˌælɪˈɡeɪʃn/","ادعا، اتهام","The allegation was never proved.","ادعا هرگز ثابت نشد.","a single unsigned page on a desk"),
 ("headline","noun","/ˈhedlaɪn/","تیتر","The headline was misleading.","تیتر گمراه‌کننده بود.","a folded newspaper with a blank banner area"),
 ("media","noun","/ˈmiːdiə/","رسانه","The media covered the story.","رسانه‌ها خبر را پوشش دادند.","several cameras pointed toward a podium"),
 ("public opinion","phrase","/ˈpʌblɪk əˈpɪnjən/","افکار عمومی","Public opinion changed quickly.","افکار عمومی سریع عوض شد.","a crowd of adults in a public square"),
 ("spread","verb","/spred/","پخش شدن","The news spread fast.","خبر سریع پخش شد.","ripples moving outward on still water"),
 ("confirm officially","phrase","/kənˈfɜːm əˈfɪʃəli/","رسماً تأیید کردن","Nothing has been confirmed officially.","چیزی رسماً تأیید نشده.","a stamped but unsigned document"),
 ("deny publicly","phrase","/dɪˈnaɪ ˈpʌblɪkli/","علناً تکذیب کردن","They denied it publicly.","علناً تکذیبش کردند.","a person in their thirties speaking at a podium"),
 ("source of information","phrase","/sɔːs əv ˌɪnfəˈmeɪʃn/","منبع خبر","What's the source of information?","منبع خبر چیست؟","a folded note passed between two hands"),
 ("trustworthy","adjective","/ˈtrʌstwɜːði/","قابل اعتماد","Is the site trustworthy?","سایت قابل اعتماد است؟","a sealed certified document on a desk"),
 ("exaggerated","adjective","/ɪɡˈzædʒəreɪtɪd/","اغراق‌شده","The report was exaggerated.","گزارش اغراق‌شده بود.","a small object beside a hugely oversized shadow"),
 ("widespread","adjective","/ˈwaɪdspred/","گسترده","The belief is widespread.","این باور گسترده است.","many identical notices on a long wall"),
 ("according to sources","phrase","/əˈkɔːdɪŋ tə ˈsɔːsɪz/","بنا بر منابع","According to sources, it's true.","بنا بر منابع درست است.","two adults in their thirties conferring quietly"),
 ("turn out to be","phrase","/tɜːn aʊt tə bi/","از آب درآمدن","It turned out to be false.","نادرست از آب درآمد.","a crossed-out line on a printed page"),
 ("take with a pinch of salt","phrase","/teɪk wɪð ə pɪntʃ əv sɔːlt/","با احتیاط پذیرفتن","Take it with a pinch of salt.","با احتیاط بپذیرش.","a person in their thirties reading a page with a doubtful look"),
 ("verify","verb","/ˈverɪfaɪ/","راستی‌آزمایی کردن","We should verify it first.","اول باید راستی‌آزمایی کنیم.","a hand comparing two documents side by side"),
 ("false","adjective","/fɔːls/","نادرست","The rumour was false.","شایعه نادرست بود.","a crossed-out notice on a board"),
]

V[22] = [
 ("have something done","phrase","/hæv ˈsʌmθɪŋ dʌn/","کاری را انجام دادن (توسط دیگری)","I had the car repaired.","خودرو را دادم تعمیر کنند.","a mechanic in their thirties closing a car bonnet while the owner waits"),
 ("get something done","phrase","/ɡet ˈsʌmθɪŋ dʌn/","کاری را رساندن به انجام","I got my hair cut.","موهایم را کوتاه کردم (کوتاه کردند).","a barber in their thirties finishing a haircut"),
 ("repair","noun","/rɪˈpeə/","تعمیر","The repair took a week.","تعمیر یک هفته طول کشید.","tools laid out beside a partly opened device"),
 ("service","verb","/ˈsɜːvɪs/","سرویس کردن","I had the car serviced.","خودرو را سرویس دادم.","a car raised on a workshop lift"),
 ("install","verb","/ɪnˈstɔːl/","نصب کردن","We had a new system installed.","سامانه تازه‌ای نصب کردیم.","technicians in their thirties fitting equipment to a wall"),
 ("decorate","verb","/ˈdekəreɪt/","تزیین، نقاشی کردن","We had the flat decorated.","آپارتمان را دادیم رنگ کنند.","a freshly painted room with covered furniture"),
 ("deliver","verb","/dɪˈlɪvə/","تحویل دادن","We had it delivered.","دادیم تحویلش بدهند.","a courier in their thirties handing over a parcel"),
 ("dry-clean","verb","/ˌdraɪˈkliːn/","خشک‌شویی کردن","I had my coat dry-cleaned.","پالتویم را دادم خشک‌شویی.","a coat in a clear cover hanging on a rail"),
 ("plumber","noun","/ˈplʌmə/","لوله‌کش","We called a plumber.","لوله‌کش خبر کردیم.","a plumber in their thirties working under a sink"),
 ("electrician","noun","/ɪlekˈtrɪʃn/","برق‌کار","The electrician came yesterday.","برق‌کار دیروز آمد.","an electrician in their thirties working at a fuse box"),
 ("technician","noun","/tekˈnɪʃn/","تکنسین","A technician checked it.","تکنسینی بررسی‌اش کرد.","a technician in their thirties testing a device with a meter"),
 ("invoice","noun","/ˈɪnvɔɪs/","صورت‌حساب","Can I have an invoice?","می‌شود صورت‌حساب بدهید؟","a printed bill on a workshop counter"),
 ("quote","noun","/kwəʊt/","قیمت پیشنهادی","They sent a quote.","قیمت پیشنهادی فرستادند.","a printed sheet handed across a counter"),
 ("charge","verb","/tʃɑːdʒ/","هزینه گرفتن","How much do you charge?","چقدر می‌گیرید؟","a card being tapped on a payment terminal"),
 ("leak","noun","/liːk/","نشتی","There's a leak under the sink.","زیر سینک نشتی هست.","water dripping from a pipe under a sink"),
 ("under warranty","phrase","/ˈʌndə ˈwɒrənti/","تحت گارانتی","It's still under warranty.","هنوز تحت گارانتی است.","a small card attached to a boxed product"),
 ("out of order","phrase","/aʊt əv ˈɔːdə/","خراب","The lift is out of order.","آسانسور خراب است.","a lift door with a plain notice taped to it"),
 ("look after","phrase","/lʊk ˈɑːftə/","مراقبت کردن از","Who looks after the building?","چه کسی از ساختمان مراقبت می‌کند؟","a caretaker in their thirties checking a corridor"),
 ("sort out","phrase","/sɔːt aʊt/","حل و فصل کردن","I'll sort it out today.","امروز حلش می‌کنم.","a person in their thirties organising a cluttered shelf"),
 ("in working order","phrase","/ɪn ˈwɜːkɪŋ ˈɔːdə/","سالم و کارکن","Everything is in working order.","همه‌چیز سالم است.","a tidy workshop with all tools in place"),
]

V[23] = [
 ("errand","noun","/ˈerənd/","کار بیرون","I have a few errands today.","امروز چند کار بیرون دارم.","a person in their thirties walking with a bag and a list"),
 ("appointment slot","phrase","/əˈpɔɪntmənt slɒt/","نوبت زمانی","I booked an appointment slot.","نوبت گرفتم.","a booking sheet with one time marked"),
 ("queue up","phrase","/kjuː ʌp/","در صف ایستادن","We had to queue up.","مجبور شدیم در صف بایستیم.","a line of adults waiting at a counter"),
 ("paperwork","noun","/ˈpeɪpəwɜːk/","کاغذبازی","There's a lot of paperwork.","کاغذبازی زیادی هست.","a thick stack of forms on a desk"),
 ("form","noun","/fɔːm/","فرم","Fill in the form, please.","لطفاً فرم را پر کن.","a blank printed form with a pen"),
 ("fill in","phrase","/fɪl ɪn/","پر کردن","I filled in the details.","جزئیات را پر کردم.","a hand writing in the boxes of a form"),
 ("hand in","phrase","/hænd ɪn/","تحویل دادن","Hand it in by Friday.","تا جمعه تحویلش بده.","a form being placed in a tray"),
 ("pick up","phrase","/pɪk ʌp/","تحویل گرفتن","I'll pick it up tomorrow.","فردا تحویلش می‌گیرم.","a parcel being collected at a counter"),
 ("drop off","phrase","/drɒp ɒf/","رساندن، تحویل دادن","I dropped it off this morning.","امروز صبح رساندمش.","a package left at a reception desk"),
 ("renew","verb","/rɪˈnjuː/","تمدید کردن","I need to renew my card.","باید کارتم را تمدید کنم.","a plain card being handed across a counter"),
 ("register","verb","/ˈredʒɪstə/","ثبت‌نام کردن","You must register first.","اول باید ثبت‌نام کنی.","a person in their thirties entering details at a desk"),
 ("apply for","phrase","/əˈplaɪ fɔː/","درخواست دادن برای","I applied for a permit.","برای مجوز درخواست دادم.","a completed application on a counter"),
 ("permit","noun","/ˈpɜːmɪt/","مجوز","You need a permit.","به مجوز نیاز داری.","a stamped card on a desk"),
 ("deadline extension","phrase","/ˈdedlaɪn ɪkˈstenʃn/","تمدید مهلت","We asked for a deadline extension.","تمدید مهلت خواستیم.","a calendar with a later date circled"),
 ("proof","noun","/pruːf/","مدرک","Bring proof of address.","مدرک نشانی بیاور.","a printed letter and a card side by side"),
 ("copy","noun","/ˈkɒpi/","رونوشت","Keep a copy for yourself.","یک رونوشت برای خودت نگه دار.","two identical printed pages"),
 ("original","noun","/əˈrɪdʒənl/","نسخه اصلی","Bring the original too.","نسخه اصلی را هم بیاور.","a stamped document in a protective sleeve"),
 ("straightforward","adjective","/ˌstreɪtˈfɔːwəd/","سرراست","The process is straightforward.","فرایند سرراست است.","a simple numbered list of three steps"),
 ("time-consuming","adjective","/ˈtaɪm kənˌsjuːmɪŋ/","وقت‌گیر","It's a time-consuming job.","کار وقت‌گیری است.","a clock beside a large pile of forms"),
 ("get it over with","phrase","/ɡet ɪt ˈəʊvə wɪð/","تمامش کردن و خلاص","Let's get it over with.","بیا تمامش کنیم و خلاص.","a person in their thirties finishing a last form with relief"),
]

V[24] = [
 ("whose","pronoun","/huːz/","که … ـَش","The man whose car broke down.","مردی که خودروش خراب شد.","a man in his early thirties standing beside a stopped car"),
 ("which is why","phrase","/wɪtʃ ɪz waɪ/","به همین دلیل","It rained, which is why we stayed.","باران بارید، به همین دلیل ماندیم.","two adults in their thirties watching rain from indoors"),
 ("relative","adjective","/ˈrelətɪv/","نسبی، وصفی","This is a relative clause.","این یک عبارت وصفی است.","two sentence cards joined by a single connector"),
 ("clause","noun","/klɔːz/","بند، جمله‌واره","The second clause explains it.","بند دوم توضیحش می‌دهد.","a long sentence split visibly into two parts"),
 ("define","verb","/dɪˈfaɪn/","تعریف کردن","This clause defines the noun.","این بند اسم را تعریف می‌کند.","a single item circled among several similar ones"),
 ("identify","verb","/aɪˈdentɪfaɪ/","شناسایی کردن","Can you identify the man?","می‌توانی آن مرد را شناسایی کنی؟","a person in their thirties picking one photo from several"),
 ("landlord","noun","/ˈlændlɔːd/","صاحبخانه","The landlord who lives upstairs.","صاحبخانه‌ای که طبقه بالا زندگی می‌کند.","a person in their thirties standing at a flat door with keys"),
 ("tenant","noun","/ˈtenənt/","مستأجر","The tenant whose lease ended.","مستأجری که اجاره‌اش تمام شد.","a person in their thirties carrying boxes out of a flat"),
 ("neighbourhood","noun","/ˈneɪbəhʊd/","محله","It's a quiet neighbourhood.","محله آرامی است.","a tree-lined residential street"),
 ("resident","noun","/ˈrezɪdənt/","ساکن","The residents complained.","ساکنان شکایت کردند.","several adults in their thirties talking outside a building"),
 ("property","noun","/ˈprɒpəti/","ملک","The property was sold.","ملک فروخته شد.","a house seen from the street"),
 ("estate agent","phrase","/ɪˈsteɪt ˌeɪdʒənt/","بنگاه املاک","The estate agent called back.","بنگاه املاک تماس گرفت.","a person in their thirties showing a floor plan to a couple"),
 ("lease","noun","/liːs/","اجاره‌نامه","The lease runs for a year.","اجاره‌نامه یک ساله است.","a signed multi-page document on a table"),
 ("furnished","adjective","/ˈfɜːnɪʃt/","مبله","It's a furnished flat.","آپارتمان مبله است.","a fully furnished living room"),
 ("spacious","adjective","/ˈspeɪʃəs/","جادار","The rooms are spacious.","اتاق‌ها جادارند.","a wide bright room with few pieces of furniture"),
 ("run-down","adjective","/ˌrʌnˈdaʊn/","فرسوده","The building is run-down.","ساختمان فرسوده است.","a weathered building facade with peeling paint"),
 ("central","adjective","/ˈsentrəl/","مرکزی","It's in a central area.","در منطقه مرکزی است.","a busy city crossroads"),
 ("move in","phrase","/muːv ɪn/","اسباب‌کشی کردن به","We moved in last month.","ماه پیش اسباب‌کشی کردیم.","two adults in their thirties carrying boxes into a flat"),
 ("get on with","phrase","/ɡet ɒn wɪð/","کنار آمدن با","We get on with our neighbours.","با همسایه‌هایمان کنار می‌آییم.","two adults in their thirties chatting on a shared landing"),
 ("put up with","phrase","/pʊt ʌp wɪð/","تحمل کردن","I can't put up with the noise.","سروصدا را تحمل نمی‌کنم.","a person in their thirties covering their ears near a window"),
]

V[25] = [
 ("used to","phrase","/ˈjuːst tuː/","قبلاً … می‌کردم","I used to walk to school.","قبلاً پیاده مدرسه می‌رفتم.","a child-height view of a tree-lined school street"),
 ("would","modal","/wʊd/","(عادت گذشته) می‌کرد","Every summer we would visit.","هر تابستان می‌رفتیم دیدنشان.","a family home seen through summer trees"),
 ("childhood","noun","/ˈtʃaɪldhʊd/","کودکی","My childhood was happy.","کودکی‌ام شاد بود.","an old photograph of a garden in summer"),
 ("memory","noun","/ˈmeməri/","خاطره","I have good memories.","خاطرات خوبی دارم.","a small box of old photographs"),
 ("nostalgia","noun","/nɒˈstældʒə/","حس نوستالژی","There's some nostalgia in it.","کمی حس نوستالژی دارد.","a person in their thirties holding an old family photo"),
 ("generation","noun","/ˌdʒenəˈreɪʃn/","نسل","My generation grew up differently.","نسل من جور دیگری بزرگ شد.","three adults of clearly different ages seated together"),
 ("tradition","noun","/trəˈdɪʃn/","سنت","It was a family tradition.","سنت خانوادگی بود.","a table laid in a traditional style"),
 ("neighbour","noun","/ˈneɪbə/","همسایه","Our neighbours were kind.","همسایه‌هایمان مهربان بودند.","two adults in their thirties talking over a garden fence"),
 ("backyard","noun","/ˌbækˈjɑːd/","حیاط پشتی","We played in the backyard.","در حیاط پشتی بازی می‌کردیم.","a small enclosed yard with a tree"),
 ("bicycle","noun","/ˈbaɪsɪkl/","دوچرخه","I had an old bicycle.","دوچرخه قدیمی‌ای داشتم.","an old bicycle leaning against a wall"),
 ("summer holiday","phrase","/ˈsʌmə ˈhɒlədeɪ/","تعطیلات تابستان","Summer holidays were long.","تعطیلات تابستان طولانی بود.","a sunlit empty schoolyard"),
 ("grow up","phrase","/ɡrəʊ ʌp/","بزرگ شدن","I grew up in a small town.","در شهر کوچکی بزرگ شدم.","a modest town street with low buildings"),
 ("look back","phrase","/lʊk bæk/","به گذشته نگاه کردن","When I look back, I smile.","وقتی به گذشته نگاه می‌کنم لبخند می‌زنم.","a person in their thirties smiling at an old album"),
 ("long for","phrase","/lɒŋ fɔː/","دلتنگ … بودن","I long for those days.","دلتنگ آن روزهایم.","an empty swing in a quiet park"),
 ("change beyond recognition","phrase","/tʃeɪndʒ bɪˈjɒnd ˌrekəɡˈnɪʃn/","تا حد ناشناختنی عوض شدن","The street has changed beyond recognition.","خیابان تا حد ناشناختنی عوض شده.","an old low street beside tall new buildings"),
 ("the same as before","phrase","/ðə seɪm əz bɪˈfɔː/","مثل قبل","Nothing is the same as before.","هیچ‌چیز مثل قبل نیست.","a renovated shopfront on an old street"),
 ("simple","adjective","/ˈsɪmpl/","ساده","Life was simpler then.","زندگی آن موقع ساده‌تر بود.","a plain kitchen with few objects"),
 ("carefree","adjective","/ˈkeəfriː/","بی‌دغدغه","Those were carefree years.","آن سال‌ها بی‌دغدغه بود.","children running in an open field"),
 ("strict","adjective","/strɪkt/","سخت‌گیر","My teachers were strict.","معلم‌هایم سخت‌گیر بودند.","a plain classroom with orderly desks"),
 ("used to be","phrase","/ˈjuːst tə bi/","قبلاً بود","There used to be a shop here.","قبلاً اینجا مغازه‌ای بود.","an empty shopfront on a quiet street"),
]

V[26] = [
 ("despite","preposition","/dɪˈspaɪt/","با وجودِ","Despite the rain, we went.","با وجود باران رفتیم.","two adults in their thirties walking under one umbrella"),
 ("in spite of","phrase","/ɪn spaɪt əv/","علی‌رغمِ","In spite of the cost, we bought it.","علی‌رغم هزینه خریدیمش.","a receipt beside a chosen item"),
 ("whereas","conjunction","/weərˈæz/","در حالی که","He likes cities, whereas I prefer villages.","او شهر دوست دارد، در حالی که من روستا را ترجیح می‌دهم.","a city skyline beside a rural landscape"),
 ("while","conjunction","/waɪl/","هرچند","While the price is high, the quality is good.","هرچند قیمت بالاست، کیفیت خوب است.","a price tag beside a well-made product"),
 ("nevertheless","adverb","/ˌnevəðəˈles/","با این حال","It was late; nevertheless, we continued.","دیر بود؛ با این حال ادامه دادیم.","two adults in their thirties walking on at dusk"),
 ("on the contrary","phrase","/ɒn ðə ˈkɒntrəri/","برعکس","On the contrary, it helped.","برعکس، کمک کرد.","a chart line rising where a fall was expected"),
 ("similarly","adverb","/ˈsɪmələli/","به‌همین‌ترتیب","Similarly, the second test failed.","به‌همین‌ترتیب آزمایش دوم هم شکست خورد.","two identical charts side by side"),
 ("likewise","adverb","/ˈlaɪkwaɪz/","همچنین","Likewise, we changed the plan.","همچنین برنامه را عوض کردیم.","two matching notes pinned side by side"),
 ("contrast","noun","/ˈkɒntrɑːst/","تضاد","There's a clear contrast.","تضاد روشنی هست.","a light object beside a very dark one"),
 ("similarity","noun","/ˌsɪməˈlærəti/","شباهت","There are many similarities.","شباهت‌های زیادی هست.","two nearly identical objects side by side"),
 ("comparison","noun","/kəmˈpærɪsn/","مقایسه","Let's make a comparison.","بیا مقایسه کنیم.","two columns of items laid out for comparison"),
 ("difference in","phrase","/ˈdɪfrəns ɪn/","تفاوت در","The difference in price is small.","تفاوت در قیمت کم است.","two price tags with nearly identical marks"),
 ("compared with","phrase","/kəmˈpeəd wɪð/","در مقایسه با","Compared with last year, it's better.","در مقایسه با پارسال بهتر است.","two charts from different years side by side"),
 ("unlike","preposition","/ʌnˈlaɪk/","برخلافِ","Unlike me, she enjoys it.","برخلاف من، او لذت می‌برد.","two adults in their thirties reacting differently to the same thing"),
 ("apart from","phrase","/əˈpɑːt frəm/","به‌جز","Apart from the price, it's fine.","به‌جز قیمت، خوب است.","one item set slightly apart from a group"),
 ("as well as","phrase","/əz wel əz/","و همچنین","We need time as well as money.","هم وقت لازم داریم هم پول.","a clock and banknotes side by side"),
 ("although","conjunction","/ɔːlˈðəʊ/","اگرچه","Although it was hard, we finished.","اگرچه سخت بود تمام کردیم.","two adults in their thirties completing a difficult task"),
 ("however","adverb","/haʊˈevə/","اما","However, the cost was high.","اما هزینه بالا بود.","a completed project beside a large receipt"),
 ("on the other hand","phrase","/ɒn ði ˈʌðə hænd/","از سوی دیگر","On the other hand, it's faster.","از سوی دیگر سریع‌تر است.","two paths, one visibly shorter"),
 ("even so","phrase","/ˈiːvn səʊ/","با این وجود","Even so, I'd do it again.","با این وجود دوباره انجامش می‌دادم.","a person in their thirties setting out on the same path again"),
]

V[27] = [
 ("the sooner the better","phrase","/ðə ˈsuːnə ðə ˈbetə/","هرچه زودتر بهتر","The sooner, the better.","هرچه زودتر بهتر.","a clock beside a ready-to-start project"),
 ("the more the better","phrase","/ðə mɔː ðə ˈbetə/","هرچه بیشتر بهتر","The more we practise, the better we get.","هرچه بیشتر تمرین کنیم بهتر می‌شویم.","a stack of completed practice pages growing"),
 ("by far","phrase","/baɪ fɑː/","به‌مراتب","This is by far the best.","این به‌مراتب بهترین است.","one item clearly outstanding among several"),
 ("far more","phrase","/fɑː mɔː/","خیلی بیشتر","It costs far more.","خیلی بیشتر هزینه دارد.","two stacks of banknotes of very different heights"),
 ("slightly","adverb","/ˈslaɪtli/","کمی","It's slightly cheaper.","کمی ارزان‌تر است.","two price tags differing by a small amount"),
 ("considerably","adverb","/kənˈsɪdərəbli/","به‌طور قابل توجه","It's considerably faster.","به‌طور قابل توجه سریع‌تر است.","two bars on a chart with a large gap"),
 ("nearly as","phrase","/ˈnɪəli əz/","تقریباً به‌اندازه","It's nearly as good.","تقریباً به‌اندازه خوب است.","two similar items with one marginally better"),
 ("not nearly as","phrase","/nɒt ˈnɪəli əz/","اصلاً به‌اندازه … نه","It's not nearly as fast.","اصلاً به آن سرعت نیست.","a slow-moving vehicle beside a fast one"),
 ("preference","noun","/ˈprefrəns/","ترجیح","What's your preference?","ترجیحت چیست؟","two items presented equally to a person"),
 ("criteria","noun","/kraɪˈtɪəriə/","معیارها","What are the criteria?","معیارها چیست؟","a checklist beside two candidate items"),
 ("trade-off","noun","/ˈtreɪd ɒf/","بده‌بستان","It's a trade-off.","بده‌بستان است.","a two-pan balance with different items"),
 ("value for money","phrase","/ˈvæljuː fə ˈmʌni/","صرفه اقتصادی","It's good value for money.","صرفه اقتصادی خوبی دارد.","a modest product beside a small stack of banknotes"),
 ("rank","verb","/ræŋk/","رتبه‌بندی کردن","Rank them by price.","بر اساس قیمت رتبه‌بندی‌شان کن.","three items arranged in a clear order"),
 ("prioritise","verb","/praɪˈɒrɪtaɪz/","اولویت‌بندی کردن","We need to prioritise.","باید اولویت‌بندی کنیم.","a list with one item moved to the top"),
 ("outweigh","verb","/ˌaʊtˈweɪ/","سنگین‌تر بودن از","The benefits outweigh the costs.","فایده‌ها بر هزینه‌ها می‌چربد.","a balance scale tipping to one side"),
 ("settle for","phrase","/ˈsetl fɔː/","به … رضایت دادن","We settled for the cheaper one.","به ارزان‌تره رضایت دادیم.","a person in their thirties accepting a modest item"),
 ("go for","phrase","/ɡəʊ fɔː/","انتخاب کردن","I'd go for the second one.","دومی را انتخاب می‌کردم.","a hand reaching for one of two items"),
 ("optimal","adjective","/ˈɒptɪməl/","بهینه","It's the optimal choice.","انتخاب بهینه است.","a marked peak point on a simple curve"),
 ("acceptable","adjective","/əkˈseptəbl/","قابل قبول","The result is acceptable.","نتیجه قابل قبول است.","a result marked with a plain tick"),
 ("second best","phrase","/ˈsekənd best/","دومین بهترین","It's the second best option.","دومین گزینه بهتر است.","two items with one placed slightly ahead"),
]

V[28] = [
 ("in my opinion","phrase","/ɪn maɪ əˈpɪnjən/","به نظر من","In my opinion, it's fair.","به نظر من منصفانه است.","a person in their thirties speaking with a measured gesture"),
 ("personally","adverb","/ˈpɜːsənəli/","شخصاً","Personally, I disagree.","شخصاً مخالفم.","a woman in her early thirties speaking candidly at a table"),
 ("as far as I'm concerned","phrase","/əz fɑːr əz aɪm kənˈsɜːnd/","تا جایی که به من مربوط است","As far as I'm concerned, it's done.","تا جایی که به من مربوط است تمام شده.","a man in his early thirties closing a folder decisively"),
 ("I'd say","phrase","/aɪd seɪ/","می‌گویم","I'd say it's too early.","می‌گویم زود است.","a person in their thirties gesturing thoughtfully"),
 ("I doubt","phrase","/aɪ daʊt/","بعید می‌دانم","I doubt it will work.","بعید می‌دانم جواب دهد.","a woman in her early thirties frowning at a plan"),
 ("absolutely","adverb","/ˈæbsəluːtli/","کاملاً","Absolutely, I agree.","کاملاً موافقم.","two adults in their thirties nodding together"),
 ("exactly","adverb","/ɪɡˈzæktli/","دقیقاً","Exactly — that's my point.","دقیقاً — منظور من همین است.","a man in his early thirties pointing in agreement"),
 ("partly","adverb","/ˈpɑːtli/","تا حدی","I partly agree.","تا حدی موافقم.","a hand tilting slightly toward one side"),
 ("point of disagreement","phrase","/pɔɪnt əv ˌdɪsəˈɡriːmənt/","نقطه اختلاف","That's the point of disagreement.","نقطه اختلاف همین است.","two documents with one line circled on each"),
 ("fair enough","phrase","/feər ɪˈnʌf/","قبول است","Fair enough, let's try it.","قبول است، امتحانش کنیم.","a man in his early thirties conceding with an open gesture"),
 ("I see your point","phrase","/aɪ siː jɔː pɔɪnt/","منظورت را می‌فهمم","I see your point, but…","منظورت را می‌فهمم، اما…","two adults in their thirties listening attentively to each other"),
 ("I'm not sure about","phrase","/aɪm nɒt ʃʊər əˈbaʊt/","مطمئن نیستم درباره","I'm not sure about that.","درباره‌اش مطمئن نیستم.","a woman in her early thirties tilting her head doubtfully"),
 ("strongly","adverb","/ˈstrɒŋli/","به‌شدت","I strongly disagree.","به‌شدت مخالفم.","a man in his early thirties speaking firmly with a raised hand"),
 ("convincing","adjective","/kənˈvɪnsɪŋ/","قانع‌کننده","That's a convincing argument.","استدلال قانع‌کننده‌ای است.","a clear well-drawn diagram on a whiteboard"),
 ("biased","adjective","/ˈbaɪəst/","جانب‌دارانه","The report seems biased.","گزارش جانب‌دارانه به‌نظر می‌رسد.","a scale tipped by an unseen weight"),
 ("objective","adjective","/əbˈdʒektɪv/","بی‌طرفانه","Try to be objective.","سعی کن بی‌طرف باشی.","a level balance scale on a plain table"),
 ("argument","noun","/ˈɑːɡjumənt/","استدلال","It's a strong argument.","استدلال محکمی است.","a clearly structured page of points"),
 ("viewpoint","noun","/ˈvjuːpɔɪnt/","دیدگاه","I respect your viewpoint.","به دیدگاهت احترام می‌گذارم.","two adults in their thirties seated facing each other"),
 ("common ground","phrase","/ˈkɒmən ɡraʊnd/","نقطه مشترک","We found common ground.","نقطه مشترک پیدا کردیم.","two overlapping circles drawn on a page"),
 ("agree to disagree","phrase","/əˈɡriː tə ˌdɪsəˈɡriː/","توافق بر سر اختلاف","Let's agree to disagree.","بیا بر سر اختلافمان توافق کنیم.","two adults in their thirties parting on friendly terms"),
]

V[29] = [
 ("on the one hand","phrase","/ɒn ðə wʌn hænd/","از یک سو","On the one hand, it's cheap.","از یک سو ارزان است.","one open palm held out to the side"),
 ("firstly","adverb","/ˈfɜːstli/","نخست","Firstly, consider the cost.","نخست هزینه را در نظر بگیر.","a numbered first item on a plain list"),
 ("secondly","adverb","/ˈsekəndli/","دوم اینکه","Secondly, we lack time.","دوم اینکه وقت کم داریم.","a numbered second item on a list"),
 ("finally","adverb","/ˈfaɪnəli/","در نهایت","Finally, we must decide.","در نهایت باید تصمیم بگیریم.","a last item ticked on a list"),
 ("moreover","adverb","/mɔːˈrəʊvə/","افزون بر این","Moreover, it saves time.","افزون بر این وقت صرفه‌جویی می‌کند.","two supporting points written under one heading"),
 ("furthermore","adverb","/ˈfɜːðəmɔː/","علاوه بر این","Furthermore, it's safer.","علاوه بر این امن‌تر است.","a list growing with an added line"),
 ("therefore","adverb","/ˈðeəfɔː/","بنابراین","Therefore, we chose the second.","بنابراین دومی را انتخاب کردیم.","an arrow leading from two points to a conclusion"),
 ("thus","adverb","/ðʌs/","از این رو","Thus, the plan changed.","از این رو برنامه عوض شد.","a redrawn line on a plan"),
 ("evidence for","phrase","/ˈevɪdəns fɔː/","شواهد برای","There's evidence for both sides.","برای هر دو طرف شواهد هست.","two folders placed on either side of a table"),
 ("counter-argument","noun","/ˈkaʊntər ˌɑːɡjumənt/","استدلال متقابل","There's a counter-argument.","استدلال متقابلی هست.","two pages facing each other on a desk"),
 ("weakness in","phrase","/ˈwiːknəs ɪn/","ضعف در","There's a weakness in the plan.","ضعفی در برنامه هست.","a single crack in an otherwise solid surface"),
 ("assumption behind","phrase","/əˈsʌmpʃn bɪˈhaɪnd/","فرض پشتِ","What's the assumption behind it?","فرض پشتش چیست؟","a diagram with one hidden layer revealed"),
 ("conclude","verb","/kənˈkluːd/","نتیجه گرفتن","We concluded that it works.","نتیجه گرفتیم که جواب می‌دهد.","a person in their thirties closing a folder with a decided look"),
 ("justify","verb","/ˈdʒʌstɪfaɪ/","توجیه کردن","Can you justify the cost?","می‌توانی هزینه را توجیه کنی؟","a man in his early thirties presenting figures on a chart"),
 ("support a view","phrase","/səˈpɔːt ə vjuː/","از نظری پشتیبانی کردن","The data supports this view.","داده‌ها از این نظر پشتیبانی می‌کند.","a chart with a clearly rising line"),
 ("overall","adverb","/ˌəʊvərˈɔːl/","روی هم رفته","Overall, it's worth it.","روی هم رفته ارزشش را دارد.","a summary line at the bottom of a chart"),
 ("in conclusion","phrase","/ɪn kənˈkluːʒn/","در نتیجه‌گیری","In conclusion, we should wait.","در نتیجه‌گیری، باید صبر کنیم.","a final paragraph on a written page"),
 ("balanced","adjective","/ˈbælənst/","متوازن","It's a balanced view.","دیدگاه متوازنی است.","a level balance scale"),
 ("one-sided","adjective","/ˌwʌnˈsaɪdɪd/","یک‌طرفه","The article is one-sided.","مقاله یک‌طرفه است.","a scale tipped fully to one side"),
 ("all in all","phrase","/ɔːl ɪn ɔːl/","در مجموع","All in all, it went well.","در مجموع خوب پیش رفت.","two adults in their thirties nodding over finished work"),
]

V[30] = [
 ("intermediate","adjective","/ˌɪntəˈmiːdiət/","متوسط (سطح)","You've finished the intermediate level.","سطح متوسط را تمام کرده‌ای.","a marked midpoint on a long rising path"),
 ("fluency","noun","/ˈfluːənsi/","روانی","My fluency has improved.","روانی‌ام بهتر شده.","a woman in her early thirties speaking easily to a group"),
 ("accuracy","noun","/ˈækjərəsi/","دقت","Accuracy matters too.","دقت هم مهم است.","a precise measuring instrument on a bench"),
 ("range","noun","/reɪndʒ/","دامنه","I have a wider range now.","حالا دامنه گسترده‌تری دارم.","a wide spread of tools laid out neatly"),
 ("complex","adjective","/ˈkɒmpleks/","پیچیده","I can handle complex topics.","از پس موضوعات پیچیده برمی‌آیم.","a detailed multi-layer diagram"),
 ("natural","adjective","/ˈnætʃrəl/","طبیعی","It sounds natural now.","حالا طبیعی به‌نظر می‌رسد.","two adults in their thirties in easy relaxed conversation"),
 ("express yourself","phrase","/ɪkˈspres jɔːˈself/","بیان کردن خود","I can express myself better.","بهتر می‌توانم خودم را بیان کنم.","a man in his early thirties speaking confidently with open hands"),
 ("hold a conversation","phrase","/həʊld ə ˌkɒnvəˈseɪʃn/","گفت‌وگو را ادامه دادن","I can hold a conversation now.","حالا می‌توانم گفت‌وگو را ادامه دهم.","two adults in their thirties talking over tea"),
 ("follow a discussion","phrase","/ˈfɒləʊ ə dɪˈskʌʃn/","دنبال کردن بحث","I can follow a discussion.","می‌توانم بحث را دنبال کنم.","a person in their thirties listening attentively in a group"),
 ("take part in","phrase","/teɪk pɑːt ɪn/","شرکت کردن در","I take part in meetings now.","حالا در جلسات شرکت می‌کنم.","a person in their thirties speaking at a meeting table"),
 ("build on","phrase","/bɪld ɒn/","بنا کردن بر","Build on what you know.","بر آنچه می‌دانی بنا کن.","new blocks added to an existing structure"),
 ("brush up","phrase","/brʌʃ ʌp/","صیقل دادن","I need to brush up my grammar.","باید گرامرم را صیقل بدهم.","a well-used grammar notebook open on a desk"),
 ("consolidate","verb","/kənˈsɒlɪdeɪt/","تثبیت کردن","Review helps consolidate it.","مرور به تثبیتش کمک می‌کند.","several loose pages gathered into one folder"),
 ("advanced level","phrase","/ədˈvɑːnst ˈlevl/","سطح پیشرفته","The advanced level is next.","سطح پیشرفته بعدی است.","a higher step on a rising staircase"),
 ("milestone reached","phrase","/ˈmaɪlstəʊn riːtʃt/","نقطه مهم طی‌شده","Another milestone reached.","نقطه مهم دیگری طی شد.","a marked stone beside a path with a view ahead"),
 ("keep practising","phrase","/kiːp ˈpræktɪsɪŋ/","تمرین را ادامه دادن","Keep practising every day.","هر روز تمرین را ادامه بده.","a notebook with daily dated entries"),
 ("realistic goal","phrase","/ˌrɪəˈlɪstɪk ɡəʊl/","هدف واقع‌بینانه","Set a realistic goal.","هدف واقع‌بینانه‌ای بگذار.","a modest flag placed partway along a path"),
 ("steady","adjective","/ˈstedi/","پیوسته","Steady progress is enough.","پیشرفت پیوسته کافی است.","a gently rising line on a chart"),
 ("capable","adjective","/ˈkeɪpəbl/","توانا","You're capable of more.","توانِ بیشتری داری.","a woman in her early thirties looking up at a higher step"),
 ("well done","phrase","/wel dʌn/","آفرین","Well done — level complete.","آفرین — سطح تمام شد.","colleagues in their thirties applauding one of them"),
]
