# -*- coding: utf-8 -*-
"""واژگان دروس ۱ تا ۱۰ سطح B2 — مفاهیم انتزاعی، روند، علت، شرطی سوم."""

V = {}

V[1] = [
 ("perspective","noun","/pəˈspektɪv/","دیدگاه","It depends on your perspective.","به دیدگاهت بستگی دارد.","two adults in their thirties viewing the same object from opposite sides"),
 ("assumption","noun","/əˈsʌmpʃn/","فرض","That's a fair assumption.","فرض منصفانه‌ای است.","a diagram with one layer marked as unproven"),
 ("interpretation","noun","/ɪnˌtɜːprɪˈteɪʃn/","برداشت","There's another interpretation.","برداشت دیگری هم هست.","the same chart read by two people with different notes"),
 ("implication","noun","/ˌɪmplɪˈkeɪʃn/","پیامد ضمنی","What are the implications?","پیامدهایش چیست؟","a single action shown branching into several outcomes"),
 ("nuance","noun","/ˈnjuːɑːns/","ظرافت معنایی","There's a nuance here.","اینجا ظرافتی هست.","two nearly identical colour swatches side by side"),
 ("context","noun","/ˈkɒntekst/","بافت، زمینه","It depends on the context.","به زمینه‌اش بستگی دارد.","a single word card placed in two different settings"),
 ("framework","noun","/ˈfreɪmwɜːk/","چارچوب","We need a clear framework.","به چارچوب روشنی نیاز داریم.","a simple structural grid drawn on a whiteboard"),
 ("principle","noun","/ˈprɪnsəpl/","اصل","It's a matter of principle.","مسئله اصولی است.","a single underlined line at the top of a page"),
 ("concept","noun","/ˈkɒnsept/","مفهوم","The concept is simple.","مفهومش ساده است.","a clean abstract diagram on a whiteboard"),
 ("abstract","adjective","/ˈæbstrækt/","انتزاعی","It's quite abstract.","نسبتاً انتزاعی است.","an unlabelled geometric diagram"),
 ("subjective","adjective","/səbˈdʒektɪv/","ذهنی","Taste is subjective.","سلیقه ذهنی است.","two adults in their thirties preferring different items"),
 ("relevant","adjective","/ˈreləvənt/","مرتبط","That isn't relevant here.","اینجا مرتبط نیست.","one item set aside from a focused group"),
 ("significant","adjective","/sɪɡˈnɪfɪkənt/","چشمگیر","It's a significant change.","تغییر چشمگیری است.","a chart line rising sharply"),
 ("underlying","adjective","/ˌʌndəˈlaɪɪŋ/","زیربنایی","The underlying cause is different.","علت زیربنایی متفاوت است.","a surface layer lifted to reveal structure beneath"),
 ("in essence","phrase","/ɪn ˈesns/","در اصل","In essence, it's the same.","در اصل یکی است.","two objects reduced to identical simple shapes"),
 ("in terms of","phrase","/ɪn tɜːmz əv/","از نظرِ","In terms of cost, it's fine.","از نظر هزینه خوب است.","a single item measured on one scale"),
 ("with regard to","phrase","/wɪð rɪˈɡɑːd tuː/","در خصوصِ","With regard to timing, we agree.","در خصوص زمان‌بندی موافقیم.","two adults in their thirties pointing at the same calendar entry"),
 ("boil down to","phrase","/bɔɪl daʊn tuː/","خلاصه شدن در","It boils down to trust.","خلاصه‌اش اعتماد است.","a large diagram reduced to a single word card"),
 ("bear in mind","phrase","/beər ɪn maɪnd/","در نظر داشتن","Bear in mind the deadline.","مهلت را در نظر داشته باش.","a calendar note kept visible beside a plan"),
 ("take into account","phrase","/teɪk ˈɪntuː əˈkaʊnt/","به حساب آوردن","We took the cost into account.","هزینه را به حساب آوردیم.","figures added into a running total"),
]

V[2] = [
 ("trend","noun","/trend/","روند","The trend is upward.","روند صعودی است.","a chart line rising steadily"),
 ("pattern","noun","/ˈpætn/","الگو","There's a clear pattern.","الگوی روشنی هست.","repeating shapes across a grid"),
 ("increase","verb","/ɪnˈkriːs/","افزایش یافتن","Sales increased sharply.","فروش به‌شدت افزایش یافت.","a steeply rising bar chart"),
 ("decline","verb","/dɪˈklaɪn/","کاهش یافتن","Numbers declined slowly.","اعداد آرام کاهش یافت.","a gently falling chart line"),
 ("fluctuate","verb","/ˈflʌktʃueɪt/","نوسان داشتن","Prices fluctuated all year.","قیمت‌ها تمام سال نوسان داشت.","a jagged up-and-down chart line"),
 ("stabilise","verb","/ˈsteɪbəlaɪz/","تثبیت شدن","The figures stabilised.","ارقام تثبیت شد.","a chart line flattening out"),
 ("peak","verb","/piːk/","به اوج رسیدن","It peaked in summer.","تابستان به اوج رسید.","a chart with one clear high point"),
 ("double","verb","/ˈdʌbl/","دو برابر شدن","The number doubled.","تعداد دو برابر شد.","two bars, one exactly twice the other"),
 ("halve","verb","/hɑːv/","نصف شدن","Costs halved last year.","هزینه‌ها پارسال نصف شد.","a bar reduced to half its previous height"),
 ("steadily","adverb","/ˈstedɪli/","پیوسته","It rose steadily.","پیوسته بالا رفت.","a smooth evenly rising line"),
 ("sharply","adverb","/ˈʃɑːpli/","به‌شدت","It fell sharply.","به‌شدت افت کرد.","a chart line dropping steeply"),
 ("gradually","adverb","/ˈɡrædʒuəli/","به‌تدریج","It changed gradually.","به‌تدریج تغییر کرد.","a very gentle slope on a chart"),
 ("significantly","adverb","/sɪɡˈnɪfɪkəntli/","به‌طور چشمگیر","It improved significantly.","به‌طور چشمگیر بهتر شد.","two bars with a large visible gap"),
 ("figure","noun","/ˈfɪɡə/","رقم","The figures speak for themselves.","ارقام خودشان گویا هستند.","a printed table of numbers"),
 ("proportion","noun","/prəˈpɔːʃn/","نسبت","A large proportion agreed.","نسبت بزرگی موافق بودند.","a pie chart with one large segment"),
 ("majority","noun","/məˈdʒɒrəti/","اکثریت","The majority preferred the first.","اکثریت اولی را ترجیح دادند.","a group of adults with most standing on one side"),
 ("minority","noun","/maɪˈnɒrəti/","اقلیت","Only a minority objected.","فقط اقلیتی مخالفت کردند.","a small group standing apart from a larger one"),
 ("average","noun","/ˈævərɪdʒ/","میانگین","The average is rising.","میانگین در حال بالا رفتن است.","a horizontal line drawn through a set of bars"),
 ("overall trend","phrase","/ˌəʊvərˈɔːl trend/","روند کلی","The overall trend is positive.","روند کلی مثبت است.","a long chart line rising despite small dips"),
 ("level off","phrase","/ˈlevl ɒf/","صاف شدن","Growth levelled off.","رشد صاف شد.","a rising line becoming horizontal"),
]

V[3] = [
 ("cause","noun","/kɔːz/","علت","What was the cause?","علتش چه بود؟","an arrow leading from one event to another"),
 ("effect","noun","/ɪˈfekt/","اثر","The effect was immediate.","اثرش فوری بود.","a ripple spreading from a single point"),
 ("consequence","noun","/ˈkɒnsɪkwəns/","پیامد","There were serious consequences.","پیامدهای جدی داشت.","dominoes falling in sequence"),
 ("factor","noun","/ˈfæktə/","عامل","Cost was the main factor.","هزینه عامل اصلی بود.","several inputs feeding into one outcome"),
 ("impact","noun","/ˈɪmpækt/","تأثیر","The impact was limited.","تأثیرش محدود بود.","a small ripple contained in a bowl of water"),
 ("outcome","noun","/ˈaʊtkʌm/","نتیجه","The outcome surprised us.","نتیجه غافلگیرمان کرد.","a finished result revealed on a table"),
 ("trigger","verb","/ˈtrɪɡə/","برانگیختن","The news triggered a reaction.","خبر واکنشی برانگیخت.","a single switch starting a chain of movement"),
 ("result in","phrase","/rɪˈzʌlt ɪn/","منجر شدن به","It resulted in a delay.","به تأخیر منجر شد.","an arrow leading to a stopped clock"),
 ("lead to","phrase","/liːd tuː/","باعث شدن","Poor planning leads to problems.","برنامه‌ریزی ضعیف باعث مشکل می‌شود.","a tangled path ending at a blocked door"),
 ("stem from","phrase","/stem frɒm/","ریشه داشتن در","The issue stems from cost.","مسئله ریشه در هزینه دارد.","a plant traced down to its root"),
 ("attribute to","phrase","/əˈtrɪbjuːt tuː/","نسبت دادن به","They attributed it to the weather.","آن را به هوا نسبت دادند.","a chart with an arrow pointing to a rain symbol"),
 ("account for","phrase","/əˈkaʊnt fɔː/","توضیح دادن، تشکیل دادن","That accounts for the delay.","این تأخیر را توضیح می‌دهد.","one segment highlighted in a pie chart"),
 ("contribute to","phrase","/kənˈtrɪbjuːt tuː/","سهم داشتن در","Several things contributed to it.","چند چیز در آن سهم داشتند.","several small streams joining one river"),
 ("due to","phrase","/djuː tuː/","به‌دلیلِ","It was cancelled due to the storm.","به‌دلیل طوفان لغو شد.","a closed gate under a stormy sky"),
 ("owing to","phrase","/ˈəʊɪŋ tuː/","به‌سببِ","Owing to the delay, we waited.","به‌سبب تأخیر منتظر ماندیم.","adults in their thirties waiting in a quiet station"),
 ("as a consequence","phrase","/əz ə ˈkɒnsɪkwəns/","در نتیجه","As a consequence, prices rose.","در نتیجه قیمت‌ها بالا رفت.","a chart line stepping upward after a marked point"),
 ("knock-on effect","phrase","/ˈnɒk ɒn ɪˈfekt/","اثر زنجیره‌ای","It had a knock-on effect.","اثر زنجیره‌ای داشت.","a long line of dominoes mid-fall"),
 ("root cause","phrase","/ruːt kɔːz/","علت ریشه‌ای","We found the root cause.","علت ریشه‌ای را پیدا کردیم.","a hand pointing at the base of a diagram"),
 ("side effect","phrase","/saɪd ɪˈfekt/","عارضه جانبی","There was one side effect.","یک عارضه جانبی داشت.","a main path with a small branch leading off"),
 ("inevitable","adjective","/ɪnˈevɪtəbl/","اجتناب‌ناپذیر","The delay was inevitable.","تأخیر اجتناب‌ناپذیر بود.","heavy rain over a closed worksite"),
]

V[4] = [
 ("had known","phrase","/hæd nəʊn/","اگر می‌دانستم","If I had known, I'd have come.","اگر می‌دانستم می‌آمدم.","a person in their thirties looking at a message received too late"),
 ("would have","phrase","/wʊd həv/","می‌شد که","I would have helped.","کمک می‌کردم.","a man in his early thirties reaching out to a task already finished"),
 ("hindsight","noun","/ˈhaɪndsaɪt/","نگاه به گذشته","With hindsight, it was clear.","با نگاه به گذشته روشن بود.","an old plan reviewed with fresh notes"),
 ("missed opportunity","phrase","/mɪst ˌɒpəˈtjuːnəti/","فرصت از دست رفته","It was a missed opportunity.","فرصت از دست رفته‌ای بود.","a closing door with light behind it"),
 ("turn down","phrase","/tɜːn daʊn/","رد کردن","I turned down the offer.","پیشنهاد را رد کردم.","a returned envelope on a desk"),
 ("hold back","phrase","/həʊld bæk/","خود را نگه داشتن","I held back for no reason.","بی‌دلیل خودم را نگه داشتم.","a person in their thirties pausing at the edge of a group"),
 ("go ahead with","phrase","/ɡəʊ əˈhed wɪð/","پیش رفتن با","We went ahead with it.","با آن پیش رفتیم.","a team in their thirties starting work together"),
 ("back down","phrase","/bæk daʊn/","عقب‌نشینی کردن","He backed down too soon.","خیلی زود عقب‌نشینی کرد.","a person in their thirties stepping away from a table"),
 ("regretful","adjective","/rɪˈɡretfl/","پشیمان","She sounded regretful.","پشیمان به‌نظر می‌رسید.","a woman in her early thirties looking down at an old letter"),
 ("bitter","adjective","/ˈbɪtə/","تلخ","It left a bitter feeling.","حس تلخی به جا گذاشت.","a cold untouched cup on an empty table"),
 ("avoidable","adjective","/əˈvɔɪdəbl/","قابل اجتناب","The mistake was avoidable.","اشتباه قابل اجتناب بود.","a clearly marked warning sign beside a wrong turn"),
 ("preventable","adjective","/prɪˈventəbl/","قابل پیشگیری","It was entirely preventable.","کاملاً قابل پیشگیری بود.","an unused safety barrier lying to one side"),
 ("if only","phrase","/ɪf ˈəʊnli/","کاش","If only I had asked.","کاش پرسیده بودم.","a person in their thirties looking at an unopened envelope"),
 ("kick myself","phrase","/kɪk maɪˈself/","از دست خود عصبانی بودن","I could kick myself.","از دست خودم عصبانی‌ام.","a man in his early thirties pressing a hand to his forehead"),
 ("in hindsight","phrase","/ɪn ˈhaɪndsaɪt/","حالا که نگاه می‌کنم","In hindsight, I was wrong.","حالا که نگاه می‌کنم اشتباه می‌کردم.","a person in their thirties reviewing an old page calmly"),
 ("learn the hard way","phrase","/lɜːn ðə hɑːd weɪ/","با تجربه تلخ یاد گرفتن","I learned it the hard way.","با تجربه تلخ یادش گرفتم.","a worn notebook with a heavily corrected page"),
 ("second-guess","verb","/ˈsekənd ɡes/","دوباره تردید کردن","Don't second-guess yourself.","به تصمیم خودت دوباره شک نکن.","a woman in her early thirties hesitating over a signed page"),
 ("dwell on","phrase","/dwel ɒn/","فکر کردن بیش از حد به","Don't dwell on it.","زیاد بهش فکر نکن.","a person in their thirties staring at a single old note"),
 ("let go","phrase","/let ɡəʊ/","رها کردن","It's time to let go.","وقتش است رهایش کنی.","a hand releasing a folded paper into the air"),
 ("water under the bridge","phrase","/ˈwɔːtər ˈʌndə ðə brɪdʒ/","گذشته‌ها گذشته","It's water under the bridge.","گذشته‌ها گذشته.","a river flowing steadily beneath an old bridge"),
]

V[5] = [
 ("scenario","noun","/səˈnɑːriəʊ/","سناریو","Consider the worst scenario.","بدترین سناریو را در نظر بگیر.","two branching paths drawn on a whiteboard"),
 ("hypothetical","adjective","/ˌhaɪpəˈθetɪkl/","فرضی","It's a hypothetical case.","مورد فرضی‌ای است.","a diagram drawn in dotted lines"),
 ("likelihood","noun","/ˈlaɪklihʊd/","احتمال","The likelihood is low.","احتمالش کم است.","a scale with a marker near the low end"),
 ("probability","noun","/ˌprɒbəˈbɪləti/","احتمال (آماری)","The probability is high.","احتمالش زیاد است.","a simple bell curve on a chart"),
 ("worst-case","adjective","/wɜːst keɪs/","بدترین حالت","Plan for the worst-case outcome.","برای بدترین حالت برنامه بریز.","a plan with a highlighted contingency box"),
 ("best-case","adjective","/best keɪs/","بهترین حالت","In the best case, we finish early.","در بهترین حالت زود تمام می‌کنیم.","a chart line reaching the highest marked point"),
 ("contingency","noun","/kənˈtɪndʒənsi/","پیش‌بینی احتیاطی","We need a contingency.","به پیش‌بینی احتیاطی نیاز داریم.","a sealed backup folder beside a main plan"),
 ("foresee","verb","/fɔːˈsiː/","پیش‌بینی کردن","Nobody could foresee it.","کسی نمی‌توانست پیش‌بینی‌اش کند.","a fogged road ahead of a parked car"),
 ("anticipate","verb","/ænˈtɪsɪpeɪt/","پیش‌بینی و آمادگی","We anticipated the delay.","تأخیر را پیش‌بینی کرده بودیم.","a person in their thirties setting out spare equipment"),
 ("rule out","phrase","/ruːl aʊt/","کنار گذاشتن","We can't rule it out.","نمی‌توانیم کنارش بگذاریم.","one option crossed out on a list of three"),
 ("weigh up","phrase","/weɪ ʌp/","سبک و سنگین کردن","Let's weigh up both cases.","بیا هر دو حالت را بسنجیم.","a two-pan balance with different items"),
 ("what if","phrase","/wɒt ɪf/","اگر … چه","What if it fails?","اگر شکست بخورد چه؟","a woman in her early thirties looking doubtfully at a plan"),
 ("suppose","verb","/səˈpəʊz/","فرض کن","Suppose we start today.","فرض کن امروز شروع کنیم.","a hand placing a marker at the start of a timeline"),
 ("assuming","conjunction","/əˈsjuːmɪŋ/","با فرض اینکه","Assuming that's true, we agree.","با فرض درست بودنش موافقیم.","a diagram with one box marked as given"),
 ("provided","conjunction","/prəˈvaɪdɪd/","به شرط اینکه","Provided we start early, it's fine.","به شرط شروع زود مشکلی نیست.","a marked early hour on a schedule"),
 ("in the event of","phrase","/ɪn ði ɪˈvent əv/","در صورت وقوعِ","In the event of a delay, call me.","در صورت تأخیر بهم زنگ بزن.","an emergency contact card on a desk"),
 ("fall through","phrase","/fɔːl θruː/","به نتیجه نرسیدن","The deal fell through.","معامله به نتیجه نرسید.","two unsigned copies left on a table"),
 ("pay off","phrase","/peɪ ɒf/","نتیجه دادن","The gamble paid off.","ریسک نتیجه داد.","a completed project beside discarded drafts"),
 ("backfire","verb","/ˌbækˈfaɪə/","نتیجه معکوس دادن","The plan backfired.","برنامه نتیجه معکوس داد.","an arrow curving back toward its source"),
 ("on reflection","phrase","/ɒn rɪˈflekʃn/","پس از تأمل","On reflection, it was right.","پس از تأمل درست بود.","a person in their thirties sitting quietly with an open notebook"),
]

V[6] = [
 ("consequence today","phrase","/ˈkɒnsɪkwəns təˈdeɪ/","پیامد امروزی","It has a consequence today.","امروز پیامدی دارد.","an old decision written on a page beside today's calendar"),
 ("career path","phrase","/kəˈrɪə pɑːθ/","مسیر شغلی","My career path would be different.","مسیر شغلی‌ام فرق می‌کرد.","a branching road drawn on a whiteboard"),
 ("qualification","noun","/ˌkwɒlɪfɪˈkeɪʃn/","مدرک","If I had the qualification, I'd apply.","اگر مدرک داشتم درخواست می‌دادم.","a framed certificate on a wall"),
 ("degree","noun","/dɪˈɡriː/","مدرک دانشگاهی","She has a degree in economics.","مدرک اقتصاد دارد.","a university building with adults outside"),
 ("apply for","phrase","/əˈplaɪ fɔː/","درخواست دادن برای","I'd have applied for it.","برایش درخواست می‌دادم.","a completed application on a counter"),
 ("major in","phrase","/ˈmeɪdʒər ɪn/","رشته اصلی داشتن","I majored in engineering.","رشته‌ام مهندسی بود.","technical drawings spread on a student desk"),
 ("end up","phrase","/end ʌp/","سر از جایی درآوردن","I ended up here.","سر از اینجا درآوردم.","a winding path arriving at a single door"),
 ("turning point","phrase","/ˈtɜːnɪŋ pɔɪnt/","نقطه عطف","That was the turning point.","نقطه عطف همان بود.","a sharp bend in a mountain road"),
 ("path not taken","phrase","/pɑːθ nɒt ˈteɪkən/","راه نرفته","I think about the path not taken.","به راه نرفته فکر می‌کنم.","a fork with one branch overgrown"),
 ("settle down","phrase","/ˈsetl daʊn/","مستقر شدن","We settled down here.","اینجا مستقر شدیم.","a furnished home with personal items in place"),
 ("relocate","verb","/ˌriːləʊˈkeɪt/","نقل مکان کردن","They relocated last year.","پارسال نقل مکان کردند.","a moving van outside a house"),
 ("commit to","phrase","/kəˈmɪt tuː/","متعهد شدن به","I committed to it fully.","کاملاً به آن متعهد شدم.","a signed agreement held in both hands"),
 ("hesitant","adjective","/ˈhezɪtənt/","مردد","I was hesitant at the time.","آن موقع مردد بودم.","a person in their thirties pausing before a doorway"),
 ("decisive","adjective","/dɪˈsaɪsɪv/","قاطع","She was decisive.","قاطع بود.","a woman in her early thirties signing without pause"),
 ("fortunate","adjective","/ˈfɔːtʃənət/","خوش‌شانس","I was fortunate.","خوش‌شانس بودم.","a person in their thirties smiling at an unexpected outcome"),
 ("stuck","adjective","/stʌk/","گیرکرده","I'd be stuck without it.","بدون آن گیر می‌کردم.","a car halted on a muddy track"),
 ("well off","phrase","/wel ɒf/","مرفه","We'd be better off now.","حالا وضعمان بهتر بود.","a comfortably furnished living room"),
 ("worse off","phrase","/wɜːs ɒf/","بدتر از نظر وضع","We'd be worse off.","وضعمان بدتر می‌شد.","a sparse room with few furnishings"),
 ("look back with","phrase","/lʊk bæk wɪð/","با … به گذشته نگاه کردن","I look back with gratitude.","با سپاس به گذشته نگاه می‌کنم.","a person in their thirties smiling at an old album"),
 ("no point in","phrase","/nəʊ pɔɪnt ɪn/","فایده‌ای ندارد","There's no point in regretting.","پشیمانی فایده‌ای ندارد.","a torn page dropped into a bin"),
]

V[7] = [
 ("but for","phrase","/bʌt fɔː/","اگر … نبود","But for the rain, we'd have gone.","اگر باران نبود می‌رفتیم.","two adults in their thirties watching heavy rain from indoors"),
 ("otherwise","adverb","/ˈʌðəwaɪz/","وگرنه","Hurry, otherwise we'll miss it.","عجله کن وگرنه از دستش می‌دهیم.","two adults in their thirties hurrying toward a closing gate"),
 ("supposing","conjunction","/səˈpəʊzɪŋ/","فرض کن که","Supposing it fails, what then?","فرض کن شکست بخورد، آن وقت چه؟","a whiteboard with a branching question mark space"),
 ("provided that","phrase","/prəˈvaɪdɪd ðæt/","به شرط اینکه","Provided that you agree, we'll start.","به شرط موافقتت شروع می‌کنیم.","two adults in their thirties shaking hands over a plan"),
 ("on condition that","phrase","/ɒn kənˈdɪʃn ðæt/","به این شرط که","He agreed on condition that we pay first.","به این شرط موافقت کرد که اول پرداخت کنیم.","a single clause underlined in a contract"),
 ("were it not for","phrase","/wɜːr ɪt nɒt fɔː/","اگر به‌خاطر … نبود","Were it not for her, we'd have failed.","اگر به‌خاطر او نبود شکست می‌خوردیم.","a woman in her early thirties steadying a leaning structure"),
 ("crucial","adjective","/ˈkruːʃl/","حیاتی","Her help was crucial.","کمکش حیاتی بود.","a single support holding a heavy beam"),
 ("essential","adjective","/ɪˈsenʃl/","ضروری","Preparation is essential.","آمادگی ضروری است.","tools laid out before a job begins"),
 ("optional","adjective","/ˈɒpʃənl/","اختیاری","That part is optional.","آن بخش اختیاری است.","one item set slightly apart from a required set"),
 ("dependent on","phrase","/dɪˈpendənt ɒn/","وابسته به","It's dependent on the weather.","به هوا وابسته است.","a plan beside a weather chart"),
 ("regardless of","phrase","/rɪˈɡɑːdləs əv/","صرف‌نظر از","We'll go regardless of the cost.","صرف‌نظر از هزینه می‌رویم.","a person in their thirties walking past a price tag"),
 ("as long as","phrase","/əz lɒŋ əz/","تا وقتی که","As long as it's safe, fine.","تا وقتی امن باشد اشکالی ندارد.","a helmet worn correctly on a worksite"),
 ("in the absence of","phrase","/ɪn ði ˈæbsəns əv/","در نبودِ","In the absence of data, we guessed.","در نبود داده حدس زدیم.","an empty chart with no plotted points"),
 ("failing that","phrase","/ˈfeɪlɪŋ ðæt/","اگر آن نشد","Failing that, we'll walk.","اگر آن نشد پیاده می‌رویم.","two adults in their thirties setting off on foot"),
 ("alternatively","adverb","/ɔːlˈtɜːnətɪvli/","به‌جای آن","Alternatively, we could wait.","به‌جای آن می‌توانیم صبر کنیم.","a second path branching from a main road"),
 ("narrowly","adverb","/ˈnærəʊli/","به‌سختی، با اختلاف کم","We narrowly avoided a delay.","به‌سختی از تأخیر جستیم.","two adults in their thirties passing through closing doors"),
 ("thanks to","phrase","/θæŋks tuː/","به لطفِ","Thanks to her, we finished.","به لطف او تمام کردیم.","a colleague in their thirties being thanked by two others"),
 ("at the last minute","phrase","/ət ðə lɑːst ˈmɪnɪt/","دقیقه آخر","It changed at the last minute.","دقیقه آخر عوض شد.","a hand rewriting a note quickly"),
 ("close call","phrase","/kləʊs kɔːl/","مو لای درزش نمی‌رفت","That was a close call.","مو لای درزش نمی‌رفت.","a car stopped just short of a barrier"),
 ("just as well","phrase","/dʒʌst əz wel/","چه بهتر که","It's just as well we waited.","چه بهتر که صبر کردیم.","two adults in their thirties looking relieved at a changed notice"),
]

V[8] = [
 ("would rather","phrase","/wʊd ˈrɑːðə/","ترجیح می‌دهم","I'd rather stay here.","ترجیح می‌دهم اینجا بمانم.","a person in their thirties settling comfortably into a chair"),
 ("had better","phrase","/hæd ˈbetə/","بهتر است","You'd better ask first.","بهتر است اول بپرسی.","a man in his early thirties raising a cautioning finger"),
 ("prefer to","phrase","/prɪˈfɜː tuː/","ترجیح دادن به","I prefer to walk.","ترجیح می‌دهم پیاده بروم.","a woman in her early thirties choosing a footpath over a bus"),
 ("insist","verb","/ɪnˈsɪst/","اصرار کردن","I insist on paying.","اصرار دارم من پرداخت کنم.","a hand firmly offering a payment card"),
 ("object","verb","/əbˈdʒekt/","اعتراض کردن","Nobody objected.","کسی اعتراض نکرد.","a room of adults in their thirties sitting silently"),
 ("advise against","phrase","/ədˈvaɪz əˈɡenst/","توصیه به نکردن","I'd advise against it.","توصیه می‌کنم انجامش ندهی.","a person in their thirties shaking their head at a plan"),
 ("urge","verb","/ɜːdʒ/","سخت توصیه کردن","I urge you to reconsider.","سخت توصیه می‌کنم تجدید نظر کنی.","a man in his early thirties speaking earnestly to a colleague"),
 ("discourage","verb","/dɪsˈkʌrɪdʒ/","دلسرد کردن","They discouraged us from trying.","ما را از تلاش دلسرد کردند.","a person in their thirties turning away from an offered tool"),
 ("reluctant","adjective","/rɪˈlʌktənt/","بی‌میل","She was reluctant to agree.","بی‌میل بود موافقت کند.","a woman in her early thirties hesitating over a pen"),
 ("keen","adjective","/kiːn/","مشتاق","He's keen to start.","مشتاق شروع است.","a man in his early thirties standing ready at a workbench"),
 ("firm","adverb","/fɜːmli/","محکم","She refused firmly.","محکم رد کرد.","a woman in her early thirties with a steady raised hand"),
 ("under no circumstances","phrase","/ˈʌndə nəʊ ˈsɜːkəmstənsɪz/","تحت هیچ شرایطی","Under no circumstances should you sign.","تحت هیچ شرایطی نباید امضا کنی.","a pen deliberately set aside from a document"),
 ("on second thoughts","phrase","/ɒn ˈsekənd θɔːts/","با فکر دوباره","On second thoughts, let's wait.","با فکر دوباره، صبر کنیم.","a person in their thirties pausing and putting a pen down"),
 ("think twice","phrase","/θɪŋk twaɪs/","دوبار فکر کردن","Think twice before you accept.","قبل از پذیرفتن دو بار فکر کن.","a woman in her early thirties studying a document closely"),
 ("talk into","phrase","/tɔːk ˈɪntuː/","راضی کردن به","He talked me into it.","راضی‌ام کرد.","one adult in their thirties persuading another with open hands"),
 ("talk out of","phrase","/tɔːk aʊt əv/","منصرف کردن از","She talked me out of it.","منصرفم کرد.","a person in their thirties gently guiding another away from a door"),
 ("preference","noun","/ˈprefrəns/","ترجیح","Do you have a preference?","ترجیحی داری؟","two items presented equally to one person"),
 ("recommendation","noun","/ˌrekəmenˈdeɪʃn/","توصیه","That's my recommendation.","توصیه من این است.","a marked option on a short list"),
 ("advisable","adjective","/ədˈvaɪzəbl/","توصیه‌شدنی","It's advisable to book early.","توصیه می‌شود زود رزرو کنی.","a calendar with an early date circled"),
 ("last resort","phrase","/lɑːst rɪˈzɔːt/","آخرین راه","That's a last resort.","آخرین راه است.","a sealed emergency box on a wall"),
]

V[9] = [
 ("it's no use","phrase","/ɪts nəʊ juːs/","فایده‌ای ندارد","It's no use complaining.","شکایت کردن فایده‌ای ندارد.","a person in their thirties setting aside a written complaint"),
 ("there's no point","phrase","/ðeəz nəʊ pɔɪnt/","دلیلی ندارد","There's no point in waiting.","صبر کردن دلیلی ندارد.","an empty waiting area with a closed counter"),
 ("worth doing","phrase","/wɜːθ ˈduːɪŋ/","ارزش انجام دادن","It's worth doing properly.","ارزش دارد درست انجام شود.","a carefully finished piece of work"),
 ("can't help","phrase","/kɑːnt help/","نمی‌توانم جلوی خودم را بگیرم","I can't help laughing.","نمی‌توانم جلوی خنده‌ام را بگیرم.","a woman in her early thirties laughing despite herself"),
 ("look forward to","phrase","/lʊk ˈfɔːwəd tuː/","مشتاقانه منتظر بودن","I look forward to hearing from you.","مشتاقانه منتظر خبرت هستم.","a person in their thirties glancing hopefully at a phone"),
 ("be used to","phrase","/bi ˈjuːst tuː/","عادت داشتن به","I'm used to working late.","به دیرکار کردن عادت دارم.","a lit desk lamp in a quiet evening office"),
 ("object to","phrase","/əbˈdʒekt tuː/","مخالفت کردن با","I object to being rushed.","با عجله‌ای شدن مخالفم.","a person in their thirties calmly resisting a hurried gesture"),
 ("get around to","phrase","/ɡet əˈraʊnd tuː/","بالاخره رسیدن به","I finally got around to fixing it.","بالاخره رسیدم درستش کنم.","a long-postponed item finally repaired"),
 ("give up","phrase","/ɡɪv ʌp/","دست کشیدن از","He gave up smoking.","سیگار را ترک کرد.","a crossed-out cigarette symbol on a wall"),
 ("keep on","phrase","/kiːp ɒn/","ادامه دادن به","She kept on trying.","به تلاش ادامه داد.","a woman in her early thirties repeating a difficult task"),
 ("end up doing","phrase","/end ʌp ˈduːɪŋ/","سر آخر … کردن","We ended up walking.","سر آخر پیاده رفتیم.","two adults in their thirties walking a long road"),
 ("acceptance","noun","/əkˈseptəns/","پذیرش","Acceptance takes time.","پذیرش زمان می‌برد.","a person in their thirties sitting calmly with a closed folder"),
 ("frustration","noun","/frʌˈstreɪʃn/","کلافگی","I understand your frustration.","کلافگی‌ات را می‌فهمم.","a man in his early thirties rubbing his temples"),
 ("patience","noun","/ˈpeɪʃns/","صبر","It takes patience.","صبر می‌خواهد.","a woman in her early thirties calmly repeating a careful task"),
 ("pointless","adjective","/ˈpɔɪntləs/","بی‌فایده","Arguing is pointless.","بحث کردن بی‌فایده است.","two adults in their thirties turning away from a stalled discussion"),
 ("inevitably","adverb","/ɪnˈevɪtəbli/","ناگزیر","Inevitably, we were late.","ناگزیر دیر رسیدیم.","a clock past the hour beside an open door"),
 ("come to terms with","phrase","/kʌm tə tɜːmz wɪð/","کنار آمدن با","He came to terms with it.","با آن کنار آمد.","a man in his early thirties looking calmly at an old photo"),
 ("move on from","phrase","/muːv ɒn frɒm/","گذشتن از","We moved on from that.","از آن گذشتیم.","a person in their thirties walking forward along a clear path"),
 ("make the best of","phrase","/meɪk ðə best əv/","بهترین استفاده را کردن از","Let's make the best of it.","بیا بهترین استفاده را از آن بکنیم.","two adults in their thirties working cheerfully in a small space"),
 ("that's life","phrase","/ðæts laɪf/","زندگی همین است","Well, that's life.","خب، زندگی همین است.","a person in their thirties shrugging with a calm smile"),
]

V[10] = [
 ("complex","adjective","/ˈkɒmpleks/","پیچیده","It's too complex to explain.","پیچیده‌تر از آن است که توضیح داده شود.","a detailed multi-layer technical diagram"),
 ("straightforward","adjective","/ˌstreɪtˈfɔːwəd/","سرراست","The rest is straightforward.","بقیه‌اش سرراست است.","three simple numbered steps on a page"),
 ("simplify","verb","/ˈsɪmplɪfaɪ/","ساده کردن","Let me simplify it.","بگذار ساده‌اش کنم.","a complicated diagram beside a simpler version"),
 ("break down","phrase","/breɪk daʊn/","تجزیه کردن","Let's break it down.","بیا تجزیه‌اش کنیم.","one large block separated into smaller pieces"),
 ("in order to","phrase","/ɪn ˈɔːdə tuː/","برای اینکه","In order to save time, we split up.","برای صرفه‌جویی در وقت جدا شدیم.","two adults in their thirties taking different routes"),
 ("so as to","phrase","/səʊ əz tuː/","به‌منظور","We left early so as to avoid traffic.","برای پرهیز از ترافیک زود رفتیم.","an empty road at dawn"),
 ("so that","conjunction","/səʊ ðæt/","تا اینکه","I wrote it down so that I'd remember.","نوشتمش تا یادم بماند.","a note stuck to a monitor"),
 ("enough to","phrase","/ɪˈnʌf tuː/","به‌اندازه کافی برای","It's clear enough to follow.","به‌اندازه کافی روشن است.","a clean readable diagram"),
 ("too … to","phrase","/tuː … tuː/","بیش از آن … که","It's too technical to follow.","بیش از آن فنی است که دنبال شود.","a dense page of technical notation"),
 ("clarity","noun","/ˈklærəti/","شفافیت","We need more clarity.","به شفافیت بیشتری نیاز داریم.","a blurred page beside a sharp one"),
 ("ambiguity","noun","/ˌæmbɪˈɡjuːəti/","ابهام","There's some ambiguity here.","اینجا کمی ابهام هست.","a sign pointing in two directions at once"),
 ("terminology","noun","/ˌtɜːmɪˈnɒlədʒi/","اصطلاحات تخصصی","The terminology is difficult.","اصطلاحات تخصصی دشوارند.","a glossary page in a technical manual"),
 ("layman's terms","phrase","/ˈleɪmənz tɜːmz/","زبان ساده","Explain it in layman's terms.","به زبان ساده توضیحش بده.","a technician in their thirties drawing a simple sketch for a listener"),
 ("get across","phrase","/ɡet əˈkrɒs/","رساندن (مفهوم)","I couldn't get it across.","نتوانستم مفهوم را برسانم.","a person in their thirties gesturing to a puzzled listener"),
 ("follow","verb","/ˈfɒləʊ/","دنبال کردن (فهمیدن)","I couldn't follow the argument.","نتوانستم استدلال را دنبال کنم.","a listener in their thirties frowning at a dense diagram"),
 ("grasp","verb","/ɡrɑːsp/","درک کردن","I grasped the idea eventually.","سرانجام ایده را درک کردم.","a man in his early thirties nodding at a clarified sketch"),
 ("elaborate","verb","/ɪˈlæbəreɪt/","بسط دادن","Could you elaborate?","می‌شود بیشتر توضیح دهید؟","a person in their thirties adding detail to a sketch"),
 ("summarise","verb","/ˈsʌməraɪz/","خلاصه کردن","Let me summarise.","بگذار خلاصه کنم.","a single page beside a thick report"),
 ("technical","adjective","/ˈteknɪkl/","فنی","It's a technical document.","سند فنی‌ای است.","a schematic drawing on a workbench"),
 ("accessible","adjective","/əkˈsesəbl/","قابل فهم","The guide is accessible.","راهنما قابل فهم است.","a clearly illustrated instruction sheet"),
]
