# -*- coding: utf-8 -*-
"""
واژگان دروس ۲۱ تا ۳۰ سطح A1.

با این ده درس، A1 ما ۳۰ درس می‌شود در برابر ۲۰ درس رقیب — و چون کاربر
تازه از همین سطح شروع می‌کند، قضاوتش درباره «این اپ جدی هست یا نه»
دقیقاً همین‌جا شکل می‌گیرد.

قواعد صحنه تصویر همان دروس قبل: بزرگسال ۲۵ تا ۳۵ ساله، پوشش کامل،
بدون هیچ متنی، و صحنه‌ای که معنی واژه را نشان بدهد نه فقط فضا را.
"""

# (واژه, بخش کلام, IPA, فارسی, جمله انگلیسی, ترجمه, صحنه تصویر)
V = {}

V[21] = [
 ("street","noun","/striːt/","خیابان","Turn left at the street.","سر خیابان بپیچ چپ.","a quiet city street with pavements and shopfronts in daylight"),
 ("road","noun","/rəʊd/","جاده","The road is very long.","جاده خیلی طولانی است.","a long straight road stretching towards distant hills"),
 ("bus","noun","/bʌs/","اتوبوس","Take the bus number five.","اتوبوس شماره پنج را بگیر.","a city bus stopped at a kerb with its doors open"),
 ("train","noun","/treɪn/","قطار","The train leaves at six.","قطار ساعت شش حرکت می‌کند.","a passenger train waiting at a station platform"),
 ("taxi","noun","/ˈtæksi/","تاکسی","Let's take a taxi.","بیا تاکسی بگیریم.","a yellow taxi waiting at the side of a city street"),
 ("corner","noun","/ˈkɔːnə/","نبش، گوشه","The shop is on the corner.","مغازه سر نبش است.","a small shop at the corner of two streets"),
 ("bicycle","noun","/ˈbaɪsɪkl/","دوچرخه","She goes by bicycle.","با دوچرخه می‌رود.","a bicycle leaning against a wall on a city pavement"),
 ("station","noun","/ˈsteɪʃn/","ایستگاه","The station is near here.","ایستگاه همین نزدیکی است.","a clean train station entrance with wide doors"),
 ("ticket","noun","/ˈtɪkɪt/","بلیت","Buy a ticket first.","اول بلیت بخر.","a hand holding a small blank paper ticket at a station"),
 ("airport","noun","/ˈeəpɔːt/","فرودگاه","We go to the airport.","به فرودگاه می‌رویم.","a modern airport terminal with wide windows and travellers"),
 ("stop","verb","/stɒp/","ایستادن","Stop at the red light.","سر چراغ قرمز بایست.","a car stopped at a pedestrian crossing on a city street"),
 ("show","verb","/ʃəʊ/","نشان دادن","Show me the way, please.","لطفاً راه را نشانم بده.","a man in his early thirties pointing out a direction to another person on a street"),
 ("cross","verb","/krɒs/","عبور کردن","Cross the street here.","اینجا از خیابان عبور کن.","a marked pedestrian crossing on a quiet street"),
 ("left","adverb","/left/","چپ","Turn left here.","اینجا بپیچ چپ.","a driver in their early thirties turning a steering wheel to the left"),
 ("right","adverb","/raɪt/","راست","Turn right at the bank.","سر بانک بپیچ راست.","a woman in her early thirties pointing to the right at a street junction"),
 ("straight","adverb","/streɪt/","مستقیم","Go straight on.","مستقیم برو.","a long straight pavement leading directly forward"),
 ("leave","verb","/liːv/","ترک کردن، رفتن","The bus leaves at six.","اتوبوس ساعت شش حرکت می‌کند.","a bus pulling away from a stop"),
 ("bridge","noun","/brɪdʒ/","پل","Go over the bridge.","از روی پل برو.","a simple bridge crossing a river"),
 ("turn","verb","/tɜːn/","پیچیدن","Turn left, please.","لطفاً بپیچ چپ.","a man in his early thirties gesturing a left turn at a corner"),
 ("traffic","noun","/ˈtræfɪk/","ترافیک","There is a lot of traffic.","ترافیک زیادی هست.","cars queued along a city street"),
]

V[22] = [
 ("cry","verb","/kraɪ/","گریه کردن","The baby is crying.","نوزاد دارد گریه می‌کند.","a small child crying while an adult comforts them"),
 ("shout","verb","/ʃaʊt/","فریاد زدن","He is shouting.","دارد فریاد می‌زند.","a man in his early thirties calling out across a field"),
 ("think","verb","/θɪŋk/","فکر کردن","I am thinking about it.","دارم درباره‌اش فکر می‌کنم.","a man in his early thirties resting his chin on his hand in thought"),
 ("smile","verb","/smaɪl/","لبخند زدن","She is smiling.","دارد لبخند می‌زند.","a woman in her early thirties smiling warmly"),
 ("wait","verb","/weɪt/","منتظر ماندن","They are waiting outside.","بیرون منتظرند.","two adults in their thirties standing patiently outside a doorway"),
 ("talk","verb","/tɔːk/","صحبت کردن","He is talking on the phone.","دارد با تلفن حرف می‌زند.","a man in his early thirties speaking on a mobile phone while standing"),
 ("knock","verb","/nɒk/","در زدن","She is knocking on the door.","دارد در می‌زند.","a hand knocking on a wooden door"),
 ("push","verb","/pʊʃ/","هل دادن","He is pushing the door.","دارد در را هل می‌دهد.","a man in his early thirties pushing a heavy door"),
 ("pull","verb","/pʊl/","کشیدن","She is pulling the box.","دارد جعبه را می‌کشد.","a woman in her early thirties pulling a large box across a floor"),
 ("cut","verb","/kʌt/","بریدن","He is cutting the bread.","دارد نان را می‌برد.","a man in his early thirties slicing bread on a board"),
 ("paint","verb","/peɪnt/","رنگ کردن","They are painting the wall.","دارند دیوار را رنگ می‌کنند.","two adults in their thirties painting a wall with rollers"),
 ("carry","verb","/ˈkæri/","حمل کردن","She is carrying a bag.","دارد کیفی حمل می‌کند.","a woman in her early thirties carrying a shopping bag"),
 ("hold","verb","/həʊld/","نگه داشتن","He is holding a cup.","فنجانی در دست دارد.","a man in his early thirties holding a cup with both hands"),
 ("wave","verb","/weɪv/","دست تکان دادن","They are waving.","دارند دست تکان می‌دهند.","two adults in their thirties waving from a doorway"),
 ("clean","verb","/kliːn/","تمیز کردن","I am cleaning the kitchen.","دارم آشپزخانه را تمیز می‌کنم.","a man in his early thirties wiping a kitchen counter with a cloth"),
 ("laugh","verb","/lɑːf/","خندیدن","They are laughing.","دارند می‌خندند.","three adults in their thirties laughing together around a table"),
 ("look","verb","/lʊk/","نگاه کردن","Look at the sky!","به آسمان نگاه کن!","a woman in her early thirties looking upward with interest"),
 ("point","verb","/pɔɪnt/","اشاره کردن","He is pointing at the map.","دارد به نقشه اشاره می‌کند.","a man in his early thirties pointing at a wall map"),
 ("build","verb","/bɪld/","ساختن","They are building a house.","دارند خانه‌ای می‌سازند.","workers in their thirties building a brick wall"),
 ("quiet","adjective","/ˈkwaɪət/","ساکت","The room is quiet.","اتاق ساکت است.","an empty quiet room with soft light and no movement"),
]

V[23] = [
 ("moment","noun","/ˈməʊmənt/","لحظه","Wait a moment, please.","لطفاً یک لحظه صبر کن.","a hand raised in a polite pause gesture"),
 ("hardly ever","phrase","/ˈhɑːdli ˈevə/","به‌ندرت","I hardly ever watch TV.","به‌ندرت تلویزیون می‌بینم.","a switched-off television in a tidy living room"),
 ("once","adverb","/wʌns/","یک بار","I go there once a week.","هفته‌ای یک بار آنجا می‌روم.","a single mark on one square of a weekly planner"),
 ("twice","adverb","/twaɪs/","دو بار","We meet twice a month.","ماهی دو بار همدیگر را می‌بینیم.","two marks on a monthly calendar page"),
 ("at the moment","phrase","/ət ðə ˈməʊmənt/","در این لحظه","I am busy at the moment.","در این لحظه سرم شلوغ است.","a woman in her early thirties working at a full desk"),
 ("right now","phrase","/raɪt naʊ/","همین حالا","He is sleeping right now.","همین حالا خواب است.","a man resting on a sofa in a quiet room"),
 ("routine","noun","/ruːˈtiːn/","روال روزانه","My routine is simple.","روال روزانه‌ام ساده است.","a man in his early thirties following his familiar morning steps at home"),
 ("all day","phrase","/ɔːl deɪ/","تمام روز","I worked all day.","تمام روز کار کردم.","a desk lamp lit over papers as daylight fades outside"),
 ("at night","phrase","/ət naɪt/","شب‌ها","I read at night.","شب‌ها کتاب می‌خوانم.","a bedside lamp lighting an open book at night"),
 ("in the evening","phrase","/ɪn ði ˈiːvnɪŋ/","عصرها","We walk in the evening.","عصرها پیاده‌روی می‌کنیم.","two adults in their thirties walking a path at golden hour"),
 ("after work","phrase","/ˈɑːftə wɜːk/","بعد از کار","I study after work.","بعد از کار درس می‌خوانم.","a person in their thirties opening a notebook at a kitchen table in the evening"),
 ("get up","verb","/ˌɡet ˈʌp/","بیدار شدن","She gets up at six.","ساعت شش بیدار می‌شود.","a woman in her early thirties sitting up on the edge of a bed in the morning"),
 ("every week","phrase","/ˈevri wiːk/","هر هفته","She calls every week.","هر هفته زنگ می‌زند.","a weekly planner with the same day marked repeatedly"),
 ("every month","phrase","/ˈevri mʌnθ/","هر ماه","We pay every month.","هر ماه پرداخت می‌کنیم.","a calendar showing several months side by side"),
 ("on Mondays","phrase","/ɒn ˈmʌndeɪz/","دوشنبه‌ها","I swim on Mondays.","دوشنبه‌ها شنا می‌کنم.","a single weekday column marked on a planner"),
 ("every morning","phrase","/ˈevri ˈmɔːnɪŋ/","هر صبح","I walk every morning.","هر صبح پیاده‌روی می‌کنم.","a person in their thirties walking a quiet street at sunrise"),
 ("this week","phrase","/ðɪs wiːk/","این هفته","I am busy this week.","این هفته سرم شلوغ است.","a full weekly planner page"),
 ("these days","phrase","/ðiːz deɪz/","این روزها","These days I walk to work.","این روزها پیاده سر کار می‌روم.","a person in their thirties walking a city pavement in the morning"),
 ("at the weekend","phrase","/ət ðə ˈwiːkend/","آخر هفته","We rest at the weekend.","آخر هفته استراحت می‌کنیم.","two adults in their thirties relaxing at home with tea"),
 ("before work","phrase","/bɪˈfɔː wɜːk/","قبل از کار","I run before work.","قبل از کار می‌دوم.","a person in their thirties running on an empty street at dawn"),
]

V[24] = [
 ("last night","phrase","/lɑːst naɪt/","دیشب","I was at home last night.","دیشب خانه بودم.","a lit window of a house at night"),
 ("worried","adjective","/ˈwʌrid/","نگران","She was worried.","نگران بود.","a woman in her early thirties with a concerned expression"),
 ("ago","adverb","/əˈɡəʊ/","پیش","Two days ago it was cold.","دو روز پیش سرد بود.","a bare winter street under a grey sky"),
 ("before","preposition","/bɪˈfɔː/","قبل از","I was there before nine.","قبل از نُه آنجا بودم.","a woman in her early thirties arriving at an office before others"),
 ("after","preposition","/ˈɑːftə/","بعد از","We were free after work.","بعد از کار آزاد بودیم.","two colleagues in their thirties leaving an office building together"),
 ("was","verb","/wɒz/","بود","He was at school.","او مدرسه بود.","a man in his early thirties standing in front of a school building"),
 ("were","verb","/wɜː/","بودند","They were very happy.","خیلی خوشحال بودند.","three adults in their thirties laughing together outdoors"),
 ("born","verb","/bɔːn/","متولد شده","I was born in Tehran.","در تهران متولد شدم.","a wide view of a city skyline in warm light"),
 ("last week","phrase","/lɑːst wiːk/","هفته گذشته","We were busy last week.","هفته گذشته سرمان شلوغ بود.","a planner page with the previous week filled in"),
 ("angry","adjective","/ˈæŋɡri/","عصبانی","He was angry.","عصبانی بود.","a man in his early thirties with a tense, frowning expression"),
 ("excited","adjective","/ɪkˈsaɪtɪd/","هیجان‌زده","They were excited.","هیجان‌زده بودند.","two adults in their thirties reacting with delight"),
 ("afraid","adjective","/əˈfreɪd/","ترسیده","I was afraid of dogs.","از سگ‌ها می‌ترسیدم.","a woman in her early thirties stepping back cautiously"),
 ("absent","adjective","/ˈæbsənt/","غایب","He was absent yesterday.","دیروز غایب بود.","an empty chair at a table of seated adults"),
 ("free","adjective","/friː/","آزاد، بیکار","Were you free yesterday?","دیروز آزاد بودی؟","a man in his early thirties relaxing with nothing scheduled"),
 ("surprised","adjective","/səˈpraɪzd/","غافلگیر","I was surprised.","غافلگیر شدم.","a woman in her early thirties with wide eyes and raised eyebrows"),
 ("asleep","adjective","/əˈsliːp/","خواب","The baby was asleep.","نوزاد خواب بود.","a sleeping child in a softly lit room"),
 ("noisy","adjective","/ˈnɔɪzi/","پرسروصدا","The street was noisy.","خیابان پرسروصدا بود.","a busy street with heavy traffic"),
 ("empty","adjective","/ˈempti/","خالی","The bus was empty.","اتوبوس خالی بود.","an empty bus interior with rows of free seats"),
 ("holiday","noun","/ˈhɒlədeɪ/","تعطیلات","It was a short holiday.","تعطیلات کوتاهی بود.","a packed suitcase beside an open door"),
 ("full","adjective","/fʊl/","پر","The room was full.","اتاق پر بود.","a room with every chair occupied by adults"),
]

V[25] = [
 ("played","verb","/pleɪd/","بازی کرد","We played football.","فوتبال بازی کردیم.","several adults in their thirties playing football on a grass pitch"),
 ("watched","verb","/wɒtʃt/","تماشا کرد","I watched a film.","فیلم تماشا کردم.","a man in his early thirties watching a screen in a dim room"),
 ("worked","verb","/wɜːkt/","کار کرد","She worked all day.","تمام روز کار کرد.","a woman in her early thirties at a desk covered with finished work"),
 ("studied","verb","/ˈstʌdid/","درس خواند","He studied English.","انگلیسی خواند.","a man in his early thirties closing a study notebook"),
 ("cooked","verb","/kʊkt/","پخت","We cooked dinner.","شام پختیم.","two adults in their thirties finishing cooking a meal together"),
 ("walked","verb","/wɔːkt/","راه رفت","They walked to the park.","تا پارک پیاده رفتند.","two adults in their thirties walking together along a park path"),
 ("visited","verb","/ˈvɪzɪtɪd/","دیدن رفت","I visited my family.","به دیدن خانواده‌ام رفتم.","a woman in her early thirties being welcomed at a family doorway"),
 ("helped","verb","/helpt/","کمک کرد","She helped her friend.","به دوستش کمک کرد.","a woman in her early thirties helping another carry boxes"),
 ("listened","verb","/ˈlɪsnd/","گوش داد","We listened to music.","موسیقی گوش دادیم.","two adults in their thirties listening to music together in a room"),
 ("wanted","verb","/ˈwɒntɪd/","خواست","He wanted a new bike.","دوچرخه نو می‌خواست.","a man in his early thirties looking at a bicycle in a shop window"),
 ("liked","verb","/laɪkt/","دوست داشت","I liked the film.","فیلم را دوست داشتم.","a woman in her early thirties smiling as she leaves a cinema"),
 ("started","verb","/ˈstɑːtɪd/","شروع کرد","The class started at nine.","کلاس ساعت نُه شروع شد.","adults in their thirties taking seats as a class begins"),
 ("finished","verb","/ˈfɪnɪʃt/","تمام کرد","We finished the work.","کار را تمام کردیم.","two colleagues in their thirties shaking hands over a completed task"),
 ("stayed","verb","/steɪd/","ماند","I stayed at home.","خانه ماندم.","a man in his early thirties reading at home on a rainy day"),
 ("called","verb","/kɔːld/","تماس گرفت","She called her mother.","به مادرش زنگ زد.","a woman in her early thirties speaking warmly on a phone"),
 ("concert","noun","/ˈkɒnsət/","کنسرت","We went to a concert.","به کنسرت رفتیم.","a small audience of adults watching musicians on a stage"),
 ("football","noun","/ˈfʊtbɔːl/","فوتبال","Football is popular here.","فوتبال اینجا محبوب است.","a football resting on green grass in a park"),
 ("park","noun","/pɑːk/","پارک","The park was full.","پارک شلوغ بود.","a green park with paths and adults walking"),
 ("match","noun","/mætʃ/","مسابقه","We watched a match.","مسابقه‌ای تماشا کردیم.","two adults in their thirties watching a football match on a screen"),
 ("picnic","noun","/ˈpɪknɪk/","پیک‌نیک","We had a picnic.","پیک‌نیک رفتیم.","a spread blanket with simple food in a green park"),
]

V[26] = [
 ("went","verb","/went/","رفت","I went to Tehran.","به تهران رفتم.","a man in his early thirties boarding a train with a bag"),
 ("saw","verb","/sɔː/","دید","We saw the sea.","دریا را دیدیم.","two adults in their thirties looking out at a calm sea"),
 ("ate","verb","/eɪt/","خورد","She ate breakfast early.","صبحانه را زود خورد.","a woman in her early thirties finishing breakfast at a table"),
 ("drank","verb","/dræŋk/","نوشید","He drank a lot of water.","آب زیادی نوشید.","a man in his early thirties drinking from a water bottle after a walk"),
 ("took","verb","/tʊk/","گرفت، برداشت","I took the bus.","اتوبوس گرفتم.","a woman in her early thirties stepping onto a bus"),
 ("made","verb","/meɪd/","ساخت، درست کرد","We made a cake.","کیک درست کردیم.","two adults in their thirties presenting a finished cake"),
 ("bought","verb","/bɔːt/","خرید","She bought a coat.","پالتو خرید.","a woman in her early thirties leaving a shop with a bag"),
 ("came","verb","/keɪm/","آمد","They came late.","دیر آمدند.","two adults in their thirties arriving at a doorway in the evening"),
 ("got","verb","/ɡɒt/","گرفت","He got a new job.","کار جدیدی گرفت.","a man in his early thirties shaking hands in an office"),
 ("gave","verb","/ɡeɪv/","داد","I gave her a book.","به او کتابی دادم.","a woman in her early thirties handing a book to a friend"),
 ("wrote","verb","/rəʊt/","نوشت","She wrote a letter.","نامه‌ای نوشت.","a woman in her early thirties writing on paper at a desk"),
 ("drove","verb","/drəʊv/","رانندگی کرد","We drove to the city.","تا شهر رانندگی کردیم.","a car on an open road seen from behind"),
 ("slept","verb","/slept/","خوابید","I slept for eight hours.","هشت ساعت خوابیدم.","a made bed in a bright morning bedroom"),
 ("met","verb","/met/","ملاقات کرد","We met at the station.","در ایستگاه همدیگر را دیدیم.","two adults in their thirties meeting on a station platform"),
 ("flew","verb","/fluː/","پرواز کرد","We flew to Shiraz.","به شیراز پرواز کردیم.","an aircraft climbing above the clouds"),
 ("sea","noun","/siː/","دریا","The sea was beautiful.","دریا زیبا بود.","a calm blue sea meeting a sandy shore"),
 ("mountain","noun","/ˈmaʊntɪn/","کوه","We climbed a mountain.","از کوهی بالا رفتیم.","a tall mountain under a clear sky"),
 ("found","verb","/faʊnd/","پیدا کرد","I found my keys.","کلیدهایم را پیدا کردم.","a hand lifting a set of keys from a table"),
 ("paid","verb","/peɪd/","پرداخت","I paid for the tickets.","پول بلیت‌ها را دادم.","a hand passing banknotes across a counter"),
 ("trip","noun","/trɪp/","سفر","It was a short trip.","سفر کوتاهی بود.","a small travel bag beside a bus window seat"),
]

V[27] = [
 ("did","verb","/dɪd/","انجام داد","What did you do?","چه کار کردی؟","a woman in her early thirties asking a question with an open gesture"),
 ("beach","noun","/biːtʃ/","ساحل","We went to the beach.","به ساحل رفتیم.","a wide sandy beach with gentle waves"),
 ("hotel","noun","/həʊˈtel/","هتل","The hotel was clean.","هتل تمیز بود.","a tidy hotel room with a made bed and a window"),
 ("boat","noun","/bəʊt/","قایق","We went by boat.","با قایق رفتیم.","a small boat on calm water"),
 ("say","verb","/seɪ/","گفتن","What did you say?","چه گفتی؟","a woman in her early thirties speaking while another leans in to listen"),
 ("photo","noun","/ˈfəʊtəʊ/","عکس","I took many photos.","عکس‌های زیادی گرفتم.","a woman in her early thirties taking a photo with a phone outdoors"),
 ("suitcase","noun","/ˈsuːtkeɪs/","چمدان","My suitcase was heavy.","چمدانم سنگین بود.","a large suitcase standing beside a doorway"),
 ("passport","noun","/ˈpɑːspɔːt/","گذرنامه","Don't forget your passport.","گذرنامه‌ات را فراموش نکن.","a closed plain travel document held in a hand"),
 ("flight","noun","/flaɪt/","پرواز","The flight was long.","پرواز طولانی بود.","an aircraft wing seen through a cabin window above clouds"),
 ("tell","verb","/tel/","تعریف کردن","Tell me about your trip.","از سفرت برایم بگو.","two adults in their thirties talking warmly over cups of tea"),
 ("enjoy","verb","/ɪnˈdʒɔɪ/","لذت بردن","Did you enjoy the trip?","از سفر لذت بردی؟","two adults in their thirties smiling while sightseeing"),
 ("stay","verb","/steɪ/","اقامت کردن","We stayed for five days.","پنج روز ماندیم.","a hotel room with an open suitcase and personal items"),
 ("guide","noun","/ɡaɪd/","راهنما","We had a guide.","راهنما داشتیم.","a guide in their thirties pointing out a sight to visitors"),
 ("arrive","verb","/əˈraɪv/","رسیدن","We arrived at night.","شب رسیدیم.","two adults in their thirties arriving at a lit hotel entrance at night"),
 ("camera","noun","/ˈkæmrə/","دوربین","I took my camera.","دوربینم را بردم.","a small camera resting on a table beside a bag"),
 ("island","noun","/ˈaɪlənd/","جزیره","We visited an island.","به جزیره‌ای رفتیم.","a small green island surrounded by calm sea"),
 ("crowded","adjective","/ˈkraʊdɪd/","شلوغ","The beach was crowded.","ساحل شلوغ بود.","a busy beach with many adults under sunshades"),
 ("desert","noun","/ˈdezət/","کویر","The desert was hot.","کویر گرم بود.","wide sand dunes under a clear sky"),
 ("tent","noun","/tent/","چادر","We slept in a tent.","در چادر خوابیدیم.","a small tent pitched in a green field"),
 ("perfect","adjective","/ˈpɜːfɪkt/","عالی","It was a perfect day.","روز عالی‌ای بود.","two adults in their thirties enjoying a bright pleasant day outdoors"),
]

V[28] = [
 ("next week","phrase","/nekst wiːk/","هفته آینده","I'm going to start next week.","هفته آینده شروع می‌کنم.","a planner open at the coming week"),
 ("next month","phrase","/nekst mʌnθ/","ماه آینده","I'm going to travel next month.","ماه آینده سفر می‌کنم.","a calendar turned to the following month"),
 ("plan","noun","/plæn/","برنامه","What is your plan?","برنامه‌ات چیست؟","a woman in her early thirties writing on a blank notepad"),
 ("future","noun","/ˈfjuːtʃə/","آینده","I think about the future.","به آینده فکر می‌کنم.","a man in his early thirties looking thoughtfully out of a window"),
 ("next year","phrase","/nekst jɪə/","سال آینده","We're going to move next year.","سال آینده نقل مکان می‌کنیم.","a calendar turned to a future year"),
 ("university","noun","/ˌjuːnɪˈvɜːsəti/","دانشگاه","He's going to university.","قرار است به دانشگاه برود.","a university building with wide steps and adult students"),
 ("course","noun","/kɔːs/","دوره","I'm going to start a course.","قرار است دوره‌ای شروع کنم.","adults in their thirties seated in a modern classroom"),
 ("exam","noun","/ɪɡˈzæm/","امتحان","The exam is next month.","امتحان ماه آینده است.","a quiet exam room with separated desks"),
 ("goal","noun","/ɡəʊl/","هدف","I have a goal.","هدفی دارم.","a marked flag at the end of a path"),
 ("save","verb","/seɪv/","پس‌انداز کردن","I'm going to save money.","می‌خواهم پول پس‌انداز کنم.","coins being dropped into a small jar"),
 ("later","adverb","/ˈleɪtə/","بعداً","I'll do it later.","بعداً انجامش می‌دهم.","a note left on a desk beside a closed notebook"),
 ("move","verb","/muːv/","نقل مکان کردن","We're going to move.","قرار است اسباب‌کشی کنیم.","two adults in their thirties carrying boxes into a new home"),
 ("learn","verb","/lɜːn/","یاد گرفتن","She's going to learn French.","قرار است فرانسه یاد بگیرد.","a woman in her early thirties studying a language notebook"),
 ("sure","adjective","/ʃʊə/","مطمئن","I'm sure about it.","درباره‌اش مطمئنم.","a man in his early thirties nodding firmly"),
 ("soon","adverb","/suːn/","به‌زودی","We're going to travel soon.","به‌زودی سفر می‌کنیم.","a packed bag waiting by a door"),
 ("hope","verb","/həʊp/","امیدوار بودن","I hope to see you.","امیدوارم ببینمت.","a woman in her early thirties smiling hopefully at an open door"),
 ("idea","noun","/aɪˈdɪə/","ایده","I have a new idea.","ایده تازه‌ای دارم.","a notebook open at a fresh page beside a pen"),
 ("dream","noun","/driːm/","رویا","It is my dream.","رویای من است.","a person in their thirties looking out at a wide horizon"),
 ("maybe","adverb","/ˈmeɪbi/","شاید","Maybe I'm going to travel.","شاید قرار است سفر کنم.","a man in his early thirties with an uncertain thoughtful expression"),
 ("busy week","phrase","/ˈbɪzi wiːk/","هفته شلوغ","Next week is a busy week.","هفته آینده هفته شلوغی است.","a weekly planner filled with entries"),
]

V[29] = [
 ("safe","adjective","/seɪf/","امن","This road is safer.","این جاده امن‌تر است.","a well-lit street with a clear pavement"),
 ("bigger","adjective","/ˈbɪɡə/","بزرگ‌تر","Tehran is bigger than Yazd.","تهران از یزد بزرگ‌تر است.","two buildings of clearly different sizes side by side"),
 ("heavy","adjective","/ˈhevi/","سنگین","This box is heavier.","این جعبه سنگین‌تر است.","a man in his early thirties lifting a large box with effort"),
 ("smaller","adjective","/ˈsmɔːlə/","کوچک‌تر","This room is smaller.","این اتاق کوچک‌تر است.","two rooms of noticeably different sizes seen together"),
 ("light","adjective","/laɪt/","سبک","This bag is lighter.","این کیف سبک‌تر است.","a woman in her early thirties carrying a small bag easily"),
 ("taller","adjective","/ˈtɔːlə/","بلندتر","He is taller than me.","از من بلندتر است.","two adults in their thirties of clearly different heights standing together"),
 ("quick","adjective","/kwɪk/","تند","This way is quicker.","این راه تندتر است.","two paths side by side, one direct and one winding"),
 ("older","adjective","/ˈəʊldə/","مسن‌تر","My brother is older.","برادرم مسن‌تر است.","two adult brothers of different ages standing together"),
 ("slow","adjective","/sləʊ/","کند","This bus is slower.","این اتوبوس کندتر است.","a bus moving slowly in heavy traffic"),
 ("dirty","adjective","/ˈdɜːti/","کثیف","This car is dirtier.","این خودرو کثیف‌تر است.","a dusty car parked on a rough road"),
 ("good","adjective","/ɡʊd/","خوب","The food is good.","غذا خوب است.","a well-presented plate of food on a table"),
 ("better","adjective","/ˈbetə/","بهتر","This tea is better.","این چای بهتر است.","two cups of tea side by side, one clearly more appealing"),
 ("bad","adjective","/bæd/","بد","The weather is bad.","هوا بد است.","a grey stormy sky over a street"),
 ("worse","adjective","/wɜːs/","بدتر","Today is worse than yesterday.","امروز از دیروز بدتر است.","heavy rain and wind on a dark street"),
 ("strong","adjective","/strɒŋ/","قوی","He is stronger than me.","از من قوی‌تر است.","a man in his early thirties lifting a heavy crate easily"),
 ("wide","adjective","/waɪd/","پهن","This street is wider.","این خیابان پهن‌تر است.","a road that visibly widens ahead"),
 ("than","conjunction","/ðæn/","از (در مقایسه)","She is taller than him.","او از او بلندتر است.","two adults in their thirties standing back to back to compare height"),
 ("same","adjective","/seɪm/","یکسان","These two are the same.","این دو یکسان هستند.","two identical items placed side by side"),
 ("different","adjective","/ˈdɪfrənt/","متفاوت","They are very different.","خیلی متفاوت هستند.","two clearly dissimilar objects side by side"),
 ("compare","verb","/kəmˈpeə/","مقایسه کردن","Let's compare the prices.","بیا قیمت‌ها را مقایسه کنیم.","a woman in her early thirties holding two items and looking between them"),
]

V[30] = [
 ("best","adjective","/best/","بهترین","It was the best day.","بهترین روز بود.","a woman in her early thirties with a joyful expression on a bright day"),
 ("worst","adjective","/wɜːst/","بدترین","That was the worst film.","آن بدترین فیلم بود.","a man in his early thirties looking thoroughly unimpressed"),
 ("biggest","adjective","/ˈbɪɡɪst/","بزرگ‌ترین","It is the biggest city.","بزرگ‌ترین شهر است.","a vast city skyline stretching to the horizon"),
 ("smallest","adjective","/ˈsmɔːlɪst/","کوچک‌ترین","This is the smallest room.","این کوچک‌ترین اتاق است.","a very compact room with a single window"),
 ("oldest","adjective","/ˈəʊldɪst/","قدیمی‌ترین","It is the oldest building here.","قدیمی‌ترین ساختمان اینجاست.","a very old historic building among newer ones"),
 ("newest","adjective","/ˈnjuːɪst/","جدیدترین","This is the newest model.","این جدیدترین مدل است.","a shiny new object displayed on a clean surface"),
 ("clever","adjective","/ˈklevə/","باهوش","She is very clever.","خیلی باهوش است.","a woman in her early thirties solving a puzzle with a focused look"),
 ("most","determiner","/məʊst/","بیشترین","Most people agree.","بیشتر مردم موافقند.","a group of adults in their thirties nodding in agreement"),
 ("beginning","noun","/bɪˈɡɪnɪŋ/","آغاز","This is just the beginning.","این تازه آغاز است.","a woman in her early thirties standing at the start of a long path"),
 ("end","noun","/end/","پایان","We are at the end of level one.","به پایان سطح یک رسیده‌ایم.","a man in his early thirties reaching the end of a path with open sky ahead"),
 ("progress","noun","/ˈprəʊɡres/","پیشرفت","Your progress is good.","پیشرفتت خوب است.","a woman in her early thirties looking satisfied at a completed workbook"),
 ("level","noun","/ˈlevl/","سطح","You finished level A1.","سطح A1 را تمام کردی.","a set of ascending steps leading upward in bright light"),
 ("mistake","noun","/mɪˈsteɪk/","اشتباه","A mistake is not a problem.","اشتباه مشکلی نیست.","a man in his early thirties calmly correcting something in a notebook"),
 ("practice","noun","/ˈpræktɪs/","تمرین","Practice every day.","هر روز تمرین کن.","a woman in her early thirties doing a daily study routine at a desk"),
 ("remember","verb","/rɪˈmembə/","به یاد آوردن","Do you remember this word?","این واژه را به یاد داری؟","a man in his early thirties pausing thoughtfully with a finger raised"),
 ("forget","verb","/fəˈɡet/","فراموش کردن","Don't forget to practise.","تمرین را فراموش نکن.","a woman in her early thirties with a hand on her forehead, remembering something"),
 ("continue","verb","/kənˈtɪnjuː/","ادامه دادن","Continue to the next level.","به سطح بعد ادامه بده.","a man in his early thirties walking confidently up a set of steps"),
 ("improve","verb","/ɪmˈpruːv/","بهتر شدن","My English is improving.","انگلیسی‌ام بهتر می‌شود.","a woman in her early thirties speaking confidently to a small group"),
 ("proud","adjective","/praʊd/","سربلند","I am proud of you.","به تو افتخار می‌کنم.","a man in his early thirties with a warm proud expression"),
 ("brave","adjective","/breɪv/","شجاع","He was brave.","شجاع بود.","a man in his early thirties standing firm with a steady expression"),
]
